<?php

namespace Database\Seeders;

use App\Models\Court;
use Illuminate\Database\Seeder;

class CourtSeeder extends Seeder
{
    public function run(): void
    {
        $courts = [
            [
                'name' => 'FYC Badminton',
                'name_en' => 'FYC Badminton',
                'field_total' => 7,
                'play_price' => 120,
                'court_type' => 'rubber',
                'operation_days' => 'Every Day',
                'operation_hours' => '16:00 - 24:00',
                'shoe_rental' => 50,
                'racket_rental' => 20,
                'phone' => '088-2672579',
                'google_map_url' => 'https://maps.app.goo.gl/SsWyf3xWEqqKpxRX7',
                'has_buffet_session' => true,
                'buffet_days' => 'Tue Thu Sat Sun',
                'buffet_start_time' => '18:00',
                'buffet_entry_fee' => 38,
                'buffet_shuttle_fee' => 20,
            ],
            [
                'name' => 'CNX Badminton',
                'name_en' => 'CNX Badminton',
                'field_total' => 7,
                'play_price' => 140,
                'court_type' => 'rubber',
                'operation_days' => 'Every Day',
                'operation_hours' => '09:00 - 24:00',
                'phone' => '094-6127979',
                'google_map_url' => 'https://maps.app.goo.gl/Zspkhvo3tzbsqxmC7',
                'has_buffet_session' => true,
                'buffet_days' => 'Mon Wed Fri Sat Sun',
                'buffet_start_time' => '18:00',
                'buffet_entry_fee' => 50,
                'buffet_shuttle_fee' => 20,
            ],
            [
                'name' => 'CMI Badminton',
                'name_en' => 'CMI Badminton',
                'field_total' => 15,
                'play_price' => 140,
                'court_type' => 'rubber',
                'operation_days' => 'Every Day',
                'operation_hours' => '13:00 - 24:00',
                'phone' => '097-3264188',
                'google_map_url' => 'https://maps.app.goo.gl/MidnWvKi9BT1exWs5',
                'has_buffet_session' => true,
                'buffet_days' => 'Mon Thu',
                'buffet_start_time' => '19:00',
                'buffet_entry_fee' => 30,
                'buffet_shuttle_fee' => 20,
                'booking_system' => 'Smart Court',
            ],
            [
                'name' => 'ATK Badminton',
                'name_en' => 'ATK Badminton',
                'field_total' => 8,
                'play_price' => 120,
                'court_type' => 'rubber',
                'operation_days' => 'Every Day',
                'operation_hours' => '09:00 - 24:00',
                'phone' => '098-2546924',
                'facebook_url' => 'https://www.facebook.com/profile.php?id=61561941751632',
                'google_map_url' => 'https://maps.app.goo.gl/2LKSuKxNfLLQthT6A',
                'has_buffet_session' => true,
                'buffet_days' => 'Tue Thu Fri Sun',
                'buffet_start_time' => '19:00',
                'buffet_entry_fee' => 35,
                'buffet_shuttle_fee' => 20,
                'booking_system' => 'Smart Court',
            ],
            [
                'name' => 'Greenhill Badminton',
                'name_en' => 'Greenhill Badminton',
                'field_total' => 6,
                'play_price' => 120,
                'court_type' => 'rubber',
                'operation_days' => 'Mon-Fri 15:00-22:00, Sat-Sun 09:00-18:00',
                'operation_hours' => '15:00 - 22:00',
                'phone' => '083-4564997',
                'facebook_url' => 'https://www.facebook.com/Greenhill-Badminton-504505579701786/',
                'google_map_url' => 'https://maps.app.goo.gl/5EtWsR69MznPgFXYA',
                'has_buffet_session' => true,
                'buffet_days' => 'Mon Tue Wed Thu',
                'buffet_start_time' => '19:00',
                'buffet_entry_fee' => 30,
                'buffet_shuttle_fee' => 18,
            ],
            [
                'name' => 'ตีรดี แบดมินตัน',
                'name_en' => 'Teeradee Badminton',
                'field_total' => 7,
                'play_price' => 140,
                'court_type' => 'rubber',
                'operation_days' => 'Every Day',
                'operation_hours' => '14:00 - 22:00',
                'phone' => '062-3606595',
                'google_map_url' => 'https://maps.app.goo.gl/RW5n2aiJovwSe2Ht9',
            ],
            [
                'name' => 'ShuttleSmash Badminton',
                'name_en' => 'ShuttleSmash Badminton',
                'field_total' => 10,
                'court_type' => 'rubber',
                'operation_days' => 'Every Day',
                'operation_hours' => '08:00 - 24:00',
                'phone' => '092-560-3994',
                'facebook_url' => 'https://www.facebook.com/profile.php?id=61566810571260',
                'has_buffet_session' => true,
                'buffet_days' => 'Mon Wed Sat',
                'buffet_start_time' => '20:00',
                'buffet_entry_fee' => 55,
                'buffet_shuttle_fee' => 20,
            ],
            [
                'name' => 'ลานนา แบดมินตัน',
                'name_en' => 'Lanna Badminton',
                'field_total' => 4,
                'court_type' => 'rubber',
            ],
            [
                'name' => 'ซิรินเลค แบดมินตัน',
                'name_en' => 'North Arena Sport Club',
                'field_total' => 8,
                'play_price' => 200,
                'court_type' => 'rubber',
                'operation_days' => 'Every Day',
                'operation_hours' => '09:00 - 21:00',
                'phone' => '061-2659009',
            ],
            [
                'name' => 'สนามแบดมินตัน มช',
                'name_en' => 'CMU Badminton',
                'field_total' => 6,
                'court_type' => 'rubber',
                'operation_hours' => '18:00 - 21:00',
            ],
            [
                'name' => 'สนามกีฬาสมโภชเชียงใหม่ 700 ปี',
                'field_total' => 8,
                'court_type' => 'rubber',
                'operation_days' => 'Tue - Sun',
                'operation_hours' => '16:00 - 20:00',
            ],
            [
                'name' => 'ศูนย์ฝึกแบดมินตันภาคเหนือ',
                'court_type' => 'rubber',
                'phone' => '096-8956394',
            ],
            [
                'name' => 'สนามแบดสมาคมพานิชย์สามัคคี',
                'field_total' => 3,
                'play_price' => 100,
                'court_type' => 'wood',
                'operation_hours' => '10:00 - 24:00',
                'phone' => '086-9102246',
            ],
            [
                'name' => 'JC Badminton',
                'name_en' => 'JC Badminton',
                'court_type' => 'rubber',
            ],
            [
                'name' => 'สนามแบดมินตัน เทศบาลตำบลสุเทพ',
                'court_type' => 'rubber',
            ],
            [
                'name' => 'สนามแบดมินตันบ้านสวนกวาง',
                'court_type' => 'rubber',
            ],
            [
                'name' => 'Spirit Badminton Arena',
                'name_en' => 'Spirit Badminton Arena',
                'field_total' => 8,
                'play_price' => 120,
                'court_type' => 'rubber',
                'operation_days' => 'Every Day',
                'has_buffet_session' => true,
                'buffet_days' => 'Fri Sun',
            ],
            [
                'name' => 'สโมสรบ้านรุ่งอรุณ 3',
                'field_total' => 2,
                'court_type' => 'rubber',
            ],
            [
                'name' => 'สนามสวนดอก',
                'field_total' => 3,
                'play_price' => 0,
                'court_type' => 'rubber',
                'operation_hours' => '16:00 - 21:00',
            ],
            [
                'name' => 'สนามกีฬา 700 ปี (Out Door)',
                'field_total' => 10,
                'court_type' => 'synthetic',
                'operation_days' => 'Every Day',
            ],
            [
                'name' => 'อุทยานหลวงราชพฤกษ์',
                'name_en' => 'Royal Park Rajapruek',
                'field_total' => 3,
                'play_price' => 0,
                'court_type' => 'synthetic',
                'operation_days' => 'Every Day',
            ],
        ];

        foreach ($courts as $court) {
            Court::create(array_merge([
                'available_for_booking' => true,
                'has_buffet_session' => false,
            ], $court));
        }

        $this->command->info('Seeded ' . count($courts) . ' courts (Chiang Mai)');
    }
}
