<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HanziHSK2Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // hanzi HSK 2 (173)
        DB::table('hanzi')->insert([
            ['hanzi' => '要', 'radical' => '覀', 'pinyin' => 'yào', 'pinyin_eng' => 'yao', 'meaning_thai' => 'ต้องการ', 'meaning_english' => 'want, need'],
            ['hanzi' => '就', 'radical' => '尢', 'pinyin' => 'jiù', 'pinyin_eng' => 'jiu', 'meaning_thai' => 'ก็จะ', 'meaning_english' => 'just, then'],
            ['hanzi' => '到', 'radical' => '刂', 'pinyin' => 'dào', 'pinyin_eng' => 'dao', 'meaning_thai' => 'ถึง', 'meaning_english' => 'arrive, to'],
            ['hanzi' => '为', 'radical' => '丶', 'pinyin' => 'wèi', 'pinyin_eng' => 'wei', 'meaning_thai' => 'สำหรับ', 'meaning_english' => 'for, because of'],
            ['hanzi' => '道', 'radical' => '辶', 'pinyin' => 'dào', 'pinyin_eng' => 'dao', 'meaning_thai' => 'ทาง', 'meaning_english' => 'way, path'],
            ['hanzi' => '可', 'radical' => '口', 'pinyin' => 'kě', 'pinyin_eng' => 'ke', 'meaning_thai' => 'สามารถ', 'meaning_english' => 'can, may'],
            ['hanzi' => '知', 'radical' => '矢', 'pinyin' => 'zhī', 'pinyin_eng' => 'zhi', 'meaning_thai' => 'รู้', 'meaning_english' => 'know'],
            ['hanzi' => '得', 'radical' => '彳', 'pinyin' => 'dé', 'pinyin_eng' => 'de', 'meaning_thai' => 'ได้', 'meaning_english' => 'obtain, get'],
            ['hanzi' => '过', 'radical' => '辶', 'pinyin' => 'guò', 'pinyin_eng' => 'guo', 'meaning_thai' => 'ผ่าน', 'meaning_english' => 'pass, cross'],
            ['hanzi' => '吧', 'radical' => '口', 'pinyin' => 'ba', 'pinyin_eng' => 'ba', 'meaning_thai' => 'สิ', 'meaning_english' => '(particle)'],
            ['hanzi' => '还', 'radical' => '辶', 'pinyin' => 'hái', 'pinyin_eng' => 'hai', 'meaning_thai' => 'ยัง', 'meaning_english' => 'still, yet'],
            ['hanzi' => '以', 'radical' => '人', 'pinyin' => 'yǐ', 'pinyin_eng' => 'yi', 'meaning_thai' => 'โดย', 'meaning_english' => 'with, by'],
            ['hanzi' => '事', 'radical' => '亅', 'pinyin' => 'shì', 'pinyin_eng' => 'shi', 'meaning_thai' => 'เรื่อง', 'meaning_english' => 'thing, matter'],
            ['hanzi' => '也', 'radical' => '乙', 'pinyin' => 'yě', 'pinyin_eng' => 'ye', 'meaning_thai' => 'ก็', 'meaning_english' => 'also, too'],
            ['hanzi' => '真', 'radical' => '目', 'pinyin' => 'zhēn', 'pinyin_eng' => 'zhen', 'meaning_thai' => 'จริง', 'meaning_english' => 'true, real'],
            ['hanzi' => '让', 'radical' => '讠', 'pinyin' => 'ràng', 'pinyin_eng' => 'rang', 'meaning_thai' => 'ให้', 'meaning_english' => 'let, allow'],
            ['hanzi' => '给', 'radical' => '纟', 'pinyin' => 'gěi', 'pinyin_eng' => 'gei', 'meaning_thai' => 'ให้', 'meaning_english' => 'give'],
            ['hanzi' => '但', 'radical' => '亻', 'pinyin' => 'dàn', 'pinyin_eng' => 'dan', 'meaning_thai' => 'แต่', 'meaning_english' => 'but, however'],
            ['hanzi' => '着', 'radical' => '目', 'pinyin' => 'zhe', 'pinyin_eng' => 'zhe', 'meaning_thai' => 'กำลัง', 'meaning_english' => '(indicates action in progress)'],
            ['hanzi' => '意', 'radical' => '心', 'pinyin' => 'yì', 'pinyin_eng' => 'yi', 'meaning_thai' => 'ความหมาย', 'meaning_english' => 'meaning, intention'],
            ['hanzi' => '别', 'radical' => '刂', 'pinyin' => 'bié', 'pinyin_eng' => 'bie', 'meaning_thai' => 'ไม่', 'meaning_english' => 'do not, other'],
            ['hanzi' => '所', 'radical' => '戶', 'pinyin' => 'suǒ', 'pinyin_eng' => 'suo', 'meaning_thai' => 'ที่', 'meaning_english' => 'place, location'],
            ['hanzi' => '然', 'radical' => '灬', 'pinyin' => 'rán', 'pinyin_eng' => 'ran', 'meaning_thai' => 'ดังนั้น', 'meaning_english' => 'so, thus'],
            ['hanzi' => '走', 'radical' => '走', 'pinyin' => 'zǒu', 'pinyin_eng' => 'zou', 'meaning_thai' => 'เดิน', 'meaning_english' => 'walk, go'],
            ['hanzi' => '经', 'radical' => '纟', 'pinyin' => 'jīng', 'pinyin_eng' => 'jing', 'meaning_thai' => 'ผ่าน', 'meaning_english' => 'pass, through'],
            ['hanzi' => '因', 'radical' => '囗', 'pinyin' => 'yīn', 'pinyin_eng' => 'yin', 'meaning_thai' => 'เพราะ', 'meaning_english' => 'because'],
            ['hanzi' => '告', 'radical' => '口', 'pinyin' => 'gào', 'pinyin_eng' => 'gao', 'meaning_thai' => 'บอก', 'meaning_english' => 'tell, inform'],
            ['hanzi' => '最', 'radical' => '曰', 'pinyin' => 'zuì', 'pinyin_eng' => 'zui', 'meaning_thai' => 'ที่สุด', 'meaning_english' => 'most, -est'],
            ['hanzi' => '手', 'radical' => '手', 'pinyin' => 'shǒu', 'pinyin_eng' => 'shou', 'meaning_thai' => 'มือ', 'meaning_english' => 'hand'],
            ['hanzi' => '找', 'radical' => '扌', 'pinyin' => 'zhǎo', 'pinyin_eng' => 'zhao', 'meaning_thai' => 'หา', 'meaning_english' => 'look for, seek'],
            ['hanzi' => '快', 'radical' => '忄', 'pinyin' => 'kuài', 'pinyin_eng' => 'kuai', 'meaning_thai' => 'เร็ว', 'meaning_english' => 'fast, quick'],
            ['hanzi' => '等', 'radical' => '竹', 'pinyin' => 'děng', 'pinyin_eng' => 'deng', 'meaning_thai' => 'รอ, ระดับ', 'meaning_english' => 'wait, rank'],
            ['hanzi' => '从', 'radical' => '人', 'pinyin' => 'cóng', 'pinyin_eng' => 'cong', 'meaning_thai' => 'จาก', 'meaning_english' => 'from, follow'],
            ['hanzi' => '情', 'radical' => '忄', 'pinyin' => 'qíng', 'pinyin_eng' => 'qing', 'meaning_thai' => 'ความรู้สึก', 'meaning_english' => 'feeling, emotion'],
            ['hanzi' => '诉', 'radical' => '讠', 'pinyin' => 'sù', 'pinyin_eng' => 'su', 'meaning_thai' => 'บอก, ร้องเรียน', 'meaning_english' => 'tell, complain'],
            ['hanzi' => '已', 'radical' => '己', 'pinyin' => 'yǐ', 'pinyin_eng' => 'yi', 'meaning_thai' => 'แล้ว', 'meaning_english' => 'already'],
            ['hanzi' => '问', 'radical' => '门', 'pinyin' => 'wèn', 'pinyin_eng' => 'wen', 'meaning_thai' => 'ถาม', 'meaning_english' => 'ask, inquire'],
            ['hanzi' => '错', 'radical' => '钅', 'pinyin' => 'cuò', 'pinyin_eng' => 'cuo', 'meaning_thai' => 'ผิดพลาด', 'meaning_english' => 'wrong, mistake'],
            ['hanzi' => '孩', 'radical' => '子', 'pinyin' => 'hái', 'pinyin_eng' => 'hai', 'meaning_thai' => 'เด็ก', 'meaning_english' => 'child'],
            ['hanzi' => '它', 'radical' => '宀', 'pinyin' => 'tā', 'pinyin_eng' => 'ta', 'meaning_thai' => 'มัน', 'meaning_english' => 'it'],
            ['hanzi' => '间', 'radical' => '门', 'pinyin' => 'jiān', 'pinyin_eng' => 'jian', 'meaning_thai' => 'ระหว่าง, ห้อง', 'meaning_english' => 'between, room'],
            ['hanzi' => '次', 'radical' => '欠', 'pinyin' => 'cì', 'pinyin_eng' => 'ci', 'meaning_thai' => 'ครั้ง, ถัดไป', 'meaning_english' => 'next, time'],
            ['hanzi' => '正', 'radical' => '止', 'pinyin' => 'zhèng', 'pinyin_eng' => 'zheng', 'meaning_thai' => 'ถูกต้อง', 'meaning_english' => 'correct, right'],
            ['hanzi' => '进', 'radical' => '辶', 'pinyin' => 'jìn', 'pinyin_eng' => 'jin', 'meaning_thai' => 'เข้าสู่', 'meaning_english' => 'enter, advance'],
            ['hanzi' => '比', 'radical' => '比', 'pinyin' => 'bǐ', 'pinyin_eng' => 'bi', 'meaning_thai' => 'เปรียบเทียบ', 'meaning_english' => 'compare'],
            ['hanzi' => '帮', 'radical' => '巾', 'pinyin' => 'bāng', 'pinyin_eng' => 'bang', 'meaning_thai' => 'ช่วยเหลือ', 'meaning_english' => 'help'],
            ['hanzi' => '晚', 'radical' => '日', 'pinyin' => 'wǎn', 'pinyin_eng' => 'wan', 'meaning_thai' => 'เย็น', 'meaning_english' => 'late, evening'],
            ['hanzi' => '动', 'radical' => '力', 'pinyin' => 'dòng', 'pinyin_eng' => 'dong', 'meaning_thai' => 'เคลื่อนไหว', 'meaning_english' => 'move, action'],
            ['hanzi' => '常', 'radical' => '巾', 'pinyin' => 'cháng', 'pinyin_eng' => 'chang', 'meaning_thai' => 'บ่อย, ปกติ', 'meaning_english' => 'often, normal'],
            ['hanzi' => '长', 'radical' => '长', 'pinyin' => 'cháng', 'pinyin_eng' => 'chang', 'meaning_thai' => 'ยาว, เติบโต', 'meaning_english' => 'long, grow'],
            ['hanzi' => '白', 'radical' => '白', 'pinyin' => 'bái', 'pinyin_eng' => 'bai', 'meaning_thai' => 'ขาว', 'meaning_english' => 'white'],
            ['hanzi' => '第', 'radical' => '⺮', 'pinyin' => 'dì', 'pinyin_eng' => 'di', 'meaning_thai' => 'ลำดับ', 'meaning_english' => 'first, number'],
            ['hanzi' => '两', 'radical' => '一', 'pinyin' => 'liǎng', 'pinyin_eng' => 'liang', 'meaning_thai' => 'สอง', 'meaning_english' => 'two, both'],
            ['hanzi' => '非', 'radical' => '非', 'pinyin' => 'fēi', 'pinyin_eng' => 'fei', 'meaning_thai' => 'ไม่, ผิด', 'meaning_english' => 'not, wrong'],
            ['hanzi' => '公', 'radical' => '八', 'pinyin' => 'gōng', 'pinyin_eng' => 'gong', 'meaning_thai' => 'สาธารณะ, เพศชาย', 'meaning_english' => 'public, male'],
            ['hanzi' => '身', 'radical' => '身', 'pinyin' => 'shēn', 'pinyin_eng' => 'shen', 'meaning_thai' => 'ร่างกาย', 'meaning_english' => 'body, oneself'],
            ['hanzi' => '题', 'radical' => '页', 'pinyin' => 'tí', 'pinyin_eng' => 'ti', 'meaning_thai' => 'หัวข้อ, คำถาม', 'meaning_english' => 'topic, question'],
            ['hanzi' => '完', 'radical' => '宀', 'pinyin' => 'wán', 'pinyin_eng' => 'wan', 'meaning_thai' => 'เสร็จสมบูรณ์', 'meaning_english' => 'complete, finish'],
            ['hanzi' => '望', 'radical' => '望', 'pinyin' => 'wàng', 'pinyin_eng' => 'wang', 'meaning_thai' => 'หวัง, มอง', 'meaning_english' => 'hope, look'],
            ['hanzi' => '离', 'radical' => '离', 'pinyin' => 'lí', 'pinyin_eng' => 'li', 'meaning_thai' => 'ออก, จาก', 'meaning_english' => 'leave, from'],
            ['hanzi' => '新', 'radical' => '斤', 'pinyin' => 'xīn', 'pinyin_eng' => 'xin', 'meaning_thai' => 'ใหม่', 'meaning_english' => 'new'],
            ['hanzi' => '思', 'radical' => '心', 'pinyin' => 'sī', 'pinyin_eng' => 'si', 'meaning_thai' => 'คิด', 'meaning_english' => 'think, thought'],
            ['hanzi' => '场', 'radical' => '土', 'pinyin' => 'chǎng', 'pinyin_eng' => 'chang', 'meaning_thai' => 'สนาม, สถานที่', 'meaning_english' => 'field, place'],
            ['hanzi' => '始', 'radical' => '女', 'pinyin' => 'shǐ', 'pinyin_eng' => 'shi', 'meaning_thai' => 'เริ่มต้น', 'meaning_english' => 'begin, start'],
            ['hanzi' => '外', 'radical' => '夕', 'pinyin' => 'wài', 'pinyin_eng' => 'wai', 'meaning_thai' => 'ข้างนอก', 'meaning_english' => 'outside'],
            ['hanzi' => '件', 'radical' => '亻', 'pinyin' => 'jiàn', 'pinyin_eng' => 'jian', 'meaning_thai' => 'สิ่งของ', 'meaning_english' => 'item, thing'],
            ['hanzi' => '表', 'radical' => '衤', 'pinyin' => 'biǎo', 'pinyin_eng' => 'biao', 'meaning_thai' => 'พื้นผิว, แสดง', 'meaning_english' => 'surface, show'],
            ['hanzi' => '希', 'radical' => '巾', 'pinyin' => 'xī', 'pinyin_eng' => 'xi', 'meaning_thai' => 'หวัง, หายาก', 'meaning_english' => 'hope, rare'],
            ['hanzi' => '边', 'radical' => '辶', 'pinyin' => 'biān', 'pinyin_eng' => 'bian', 'meaning_thai' => 'ด้านข้าง, ขอบ', 'meaning_english' => 'side, edge'],
            ['hanzi' => '男', 'radical' => '田', 'pinyin' => 'nán', 'pinyin_eng' => 'nan', 'meaning_thai' => 'เพศชาย', 'meaning_english' => 'male'],
            ['hanzi' => '准', 'radical' => '冫', 'pinyin' => 'zhǔn', 'pinyin_eng' => 'zhun', 'meaning_thai' => 'แม่นยำ, อนุญาต', 'meaning_english' => 'accurate, allow'],
            ['hanzi' => '员', 'radical' => '口', 'pinyin' => 'yuán', 'pinyin_eng' => 'yuan', 'meaning_thai' => 'สมาชิก, พนักงาน', 'meaning_english' => 'member, staff'],
            ['hanzi' => '玩', 'radical' => '王', 'pinyin' => 'wán', 'pinyin_eng' => 'wan', 'meaning_thai' => 'เล่น', 'meaning_english' => 'play, enjoy'],
            ['hanzi' => '每', 'radical' => '母', 'pinyin' => 'měi', 'pinyin_eng' => 'mei', 'meaning_thai' => 'ทุก ๆ', 'meaning_english' => 'every, each'],
            ['hanzi' => '备', 'radical' => '夂', 'pinyin' => 'bèi', 'pinyin_eng' => 'bei', 'meaning_thai' => 'เตรียม', 'meaning_english' => 'prepare'],
            ['hanzi' => '试', 'radical' => '讠', 'pinyin' => 'shì', 'pinyin_eng' => 'shi', 'meaning_thai' => 'ทดลอง, ลอง', 'meaning_english' => 'test, try'],
            ['hanzi' => '体', 'radical' => '亻', 'pinyin' => 'tǐ', 'pinyin_eng' => 'ti', 'meaning_thai' => 'ร่างกาย, รูปแบบ', 'meaning_english' => 'body, form'],
            ['hanzi' => '乐', 'radical' => '丿', 'pinyin' => 'lè', 'pinyin_eng' => 'le', 'meaning_thai' => 'สุข, ดนตรี', 'meaning_english' => 'happy, music'],
            ['hanzi' => '早', 'radical' => '日', 'pinyin' => 'zǎo', 'pinyin_eng' => 'zao', 'meaning_thai' => 'เช้า', 'meaning_english' => 'early, morning'],
            ['hanzi' => '门', 'radical' => '门', 'pinyin' => 'mén', 'pinyin_eng' => 'men', 'meaning_thai' => 'ประตู', 'meaning_english' => 'door, gate'],
            ['hanzi' => '房', 'radical' => '户', 'pinyin' => 'fáng', 'pinyin_eng' => 'fang', 'meaning_thai' => 'บ้าน, ห้อง', 'meaning_english' => 'house, room'],
            ['hanzi' => '球', 'radical' => '王', 'pinyin' => 'qiú', 'pinyin_eng' => 'qiu', 'meaning_thai' => 'ลูกบอล, ทรงกลม', 'meaning_english' => 'ball, sphere'],
            ['hanzi' => '夫', 'radical' => '大', 'pinyin' => 'fū', 'pinyin_eng' => 'fu', 'meaning_thai' => 'สามี, ผู้ชาย', 'meaning_english' => 'husband, man'],
            ['hanzi' => '路', 'radical' => '足', 'pinyin' => 'lù', 'pinyin_eng' => 'lu', 'meaning_thai' => 'ถนน, ทาง', 'meaning_english' => 'road, way'],
            ['hanzi' => '日', 'radical' => '日', 'pinyin' => 'rì', 'pinyin_eng' => 'ri', 'meaning_thai' => 'วัน, พระอาทิตย์', 'meaning_english' => 'day, sun'],
            ['hanzi' => '舞', 'radical' => '舛', 'pinyin' => 'wǔ', 'pinyin_eng' => 'wu', 'meaning_thai' => 'เต้นรำ', 'meaning_english' => 'dance'],
            ['hanzi' => '笑', 'radical' => '竹', 'pinyin' => 'xiào', 'pinyin_eng' => 'xiao', 'meaning_thai' => 'หัวเราะ, ยิ้ม', 'meaning_english' => 'laugh, smile'],
            ['hanzi' => '报', 'radical' => '扌', 'pinyin' => 'bào', 'pinyin_eng' => 'bao', 'meaning_thai' => 'รายงาน, หนังสือพิมพ์', 'meaning_english' => 'report, newspaper'],
            ['hanzi' => '教', 'radical' => '攵', 'pinyin' => 'jiào', 'pinyin_eng' => 'jiao', 'meaning_thai' => 'สอน, ศาสนา', 'meaning_english' => 'teach, religion'],
            ['hanzi' => '色', 'radical' => '色', 'pinyin' => 'sè', 'pinyin_eng' => 'se', 'meaning_thai' => 'สี', 'meaning_english' => 'color'],
            ['hanzi' => '远', 'radical' => '辶', 'pinyin' => 'yuǎn', 'pinyin_eng' => 'yuan', 'meaning_thai' => 'ไกล', 'meaning_english' => 'far, distant'],
            ['hanzi' => '眼', 'radical' => '目', 'pinyin' => 'yǎn', 'pinyin_eng' => 'yan', 'meaning_thai' => 'ตา', 'meaning_english' => 'eye'],
            ['hanzi' => '蛋', 'radical' => '虫', 'pinyin' => 'dàn', 'pinyin_eng' => 'dan', 'meaning_thai' => 'ไข่', 'meaning_english' => 'egg'],
            ['hanzi' => '息', 'radical' => '心', 'pinyin' => 'xī', 'pinyin_eng' => 'xi', 'meaning_thai' => 'พัก, ดอกเบี้ย', 'meaning_english' => 'rest, interest'],
            ['hanzi' => '室', 'radical' => '宀', 'pinyin' => 'shì', 'pinyin_eng' => 'shi', 'meaning_thai' => 'ห้อง', 'meaning_english' => 'room'],
            ['hanzi' => '运', 'radical' => '辶', 'pinyin' => 'yùn', 'pinyin_eng' => 'yun', 'meaning_thai' => 'ขนส่ง, โชค', 'meaning_english' => 'transport, luck'],
            ['hanzi' => '哥', 'radical' => '口', 'pinyin' => 'gē', 'pinyin_eng' => 'ge', 'meaning_thai' => 'พี่ชาย', 'meaning_english' => 'older brother'],
            ['hanzi' => '火', 'radical' => '火', 'pinyin' => 'huǒ', 'pinyin_eng' => 'huo', 'meaning_thai' => 'ไฟ', 'meaning_english' => 'fire'],
            ['hanzi' => '条', 'radical' => '木', 'pinyin' => 'tiáo', 'pinyin_eng' => 'tiao', 'meaning_thai' => 'แถบ, รายการ', 'meaning_english' => 'strip, item'],
            ['hanzi' => '病', 'radical' => '疒', 'pinyin' => 'bìng', 'pinyin_eng' => 'bing', 'meaning_thai' => 'โรค', 'meaning_english' => 'illness, disease'],
            ['hanzi' => '弟', 'radical' => '弓', 'pinyin' => 'dì', 'pinyin_eng' => 'di', 'meaning_thai' => 'น้องชาย', 'meaning_english' => 'younger brother'],
            ['hanzi' => '您', 'radical' => '心', 'pinyin' => 'nín', 'pinyin_eng' => 'nin', 'meaning_thai' => 'คุณ (สุภาพ)', 'meaning_english' => 'you (polite)'],
            ['hanzi' => '送', 'radical' => '辶', 'pinyin' => 'sòng', 'pinyin_eng' => 'song', 'meaning_thai' => 'ส่ง', 'meaning_english' => 'send, deliver'],
            ['hanzi' => '近', 'radical' => '辶', 'pinyin' => 'jìn', 'pinyin_eng' => 'jin', 'meaning_thai' => 'ใกล้', 'meaning_english' => 'near, close'],
            ['hanzi' => '穿', 'radical' => '穴', 'pinyin' => 'chuān', 'pinyin_eng' => 'chuan', 'meaning_thai' => 'ใส่', 'meaning_english' => 'wear, pierce'],
            ['hanzi' => '助', 'radical' => '力', 'pinyin' => 'zhù', 'pinyin_eng' => 'zhu', 'meaning_thai' => 'ช่วยเหลือ', 'meaning_english' => 'help, assist'],
            ['hanzi' => '司', 'radical' => '口', 'pinyin' => 'sī', 'pinyin_eng' => 'si', 'meaning_thai' => 'จัดการ, แผนก', 'meaning_english' => 'manage, department'],
            ['hanzi' => '跑', 'radical' => '足', 'pinyin' => 'pǎo', 'pinyin_eng' => 'pao', 'meaning_thai' => 'วิ่ง', 'meaning_english' => 'run'],
            ['hanzi' => '忙', 'radical' => '忄', 'pinyin' => 'máng', 'pinyin_eng' => 'mang', 'meaning_thai' => 'ยุ่ง', 'meaning_english' => 'busy'],
            ['hanzi' => '站', 'radical' => '立', 'pinyin' => 'zhàn', 'pinyin_eng' => 'zhan', 'meaning_thai' => 'ยืน, สถานี', 'meaning_english' => 'stand, station'],
            ['hanzi' => '跳', 'radical' => '足', 'pinyin' => 'tiào', 'pinyin_eng' => 'tiao', 'meaning_thai' => 'กระโดด', 'meaning_english' => 'jump'],
            ['hanzi' => '便', 'radical' => '亻', 'pinyin' => 'biàn', 'pinyin_eng' => 'bian', 'meaning_thai' => 'สะดวก, จากนั้น', 'meaning_english' => 'convenient, then'],
            ['hanzi' => '歌', 'radical' => '欠', 'pinyin' => 'gē', 'pinyin_eng' => 'ge', 'meaning_thai' => 'เพลง', 'meaning_english' => 'song'],
            ['hanzi' => '务', 'radical' => '力', 'pinyin' => 'wù', 'pinyin_eng' => 'wu', 'meaning_thai' => 'ธุรกิจ, กิจการ', 'meaning_english' => 'affair, business'],
            ['hanzi' => '黑', 'radical' => '黑', 'pinyin' => 'hēi', 'pinyin_eng' => 'hei', 'meaning_thai' => 'สีดำ', 'meaning_english' => 'black'],
            ['hanzi' => '票', 'radical' => '示', 'pinyin' => 'piào', 'pinyin_eng' => 'piao', 'meaning_thai' => 'ตั๋ว', 'meaning_english' => 'ticket'],
            ['hanzi' => '游', 'radical' => '氵', 'pinyin' => 'yóu', 'pinyin_eng' => 'you', 'meaning_thai' => 'ว่ายน้ำ, ท่องเที่ยว', 'meaning_english' => 'swim, travel'],
            ['hanzi' => '唱', 'radical' => '口', 'pinyin' => 'chàng', 'pinyin_eng' => 'chang', 'meaning_thai' => 'ร้องเพลง', 'meaning_english' => 'sing'],
            ['hanzi' => '考', 'radical' => '老', 'pinyin' => 'kǎo', 'pinyin_eng' => 'kao', 'meaning_thai' => 'ทดสอบ', 'meaning_english' => 'test, examine'],
            ['hanzi' => '往', 'radical' => '彳', 'pinyin' => 'wǎng', 'pinyin_eng' => 'wang', 'meaning_thai' => 'ไปทาง, อดีต', 'meaning_english' => 'toward, past'],
            ['hanzi' => '步', 'radical' => '止', 'pinyin' => 'bù', 'pinyin_eng' => 'bu', 'meaning_thai' => 'ก้าว, เดิน', 'meaning_english' => 'step, walk'],
            ['hanzi' => '班', 'radical' => '王', 'pinyin' => 'bān', 'pinyin_eng' => 'ban', 'meaning_thai' => 'ชั้นเรียน, กะ', 'meaning_english' => 'class, shift'],
            ['hanzi' => '药', 'radical' => '艹', 'pinyin' => 'yào', 'pinyin_eng' => 'yao', 'meaning_thai' => 'ยา', 'meaning_english' => 'medicine, drug'],
            ['hanzi' => '卖', 'radical' => '士', 'pinyin' => 'mài', 'pinyin_eng' => 'mai', 'meaning_thai' => 'ขาย', 'meaning_english' => 'sell'],
            ['hanzi' => '百', 'radical' => '白', 'pinyin' => 'bǎi', 'pinyin_eng' => 'bai', 'meaning_thai' => 'ร้อย', 'meaning_english' => 'hundred'],
            ['hanzi' => '妹', 'radical' => '女', 'pinyin' => 'mèi', 'pinyin_eng' => 'mei', 'meaning_thai' => 'น้องสาว', 'meaning_english' => 'younger sister'],
            ['hanzi' => '足', 'radical' => '足', 'pinyin' => 'zú', 'pinyin_eng' => 'zu', 'meaning_thai' => 'เท้า, พอเพียง', 'meaning_english' => 'foot, enough'],
            ['hanzi' => '慢', 'radical' => '忄', 'pinyin' => 'màn', 'pinyin_eng' => 'man', 'meaning_thai' => 'ช้า', 'meaning_english' => 'slow'],
            ['hanzi' => '妻', 'radical' => '女', 'pinyin' => 'qī', 'pinyin_eng' => 'qi', 'meaning_thai' => 'ภรรยา', 'meaning_english' => 'wife'],
            ['hanzi' => '床', 'radical' => '广', 'pinyin' => 'chuáng', 'pinyin_eng' => 'chuang', 'meaning_thai' => 'เตียง', 'meaning_english' => 'bed'],
            ['hanzi' => '休', 'radical' => '亻', 'pinyin' => 'xiū', 'pinyin_eng' => 'xiu', 'meaning_thai' => 'พักผ่อน', 'meaning_english' => 'rest, stop'],
            ['hanzi' => '洗', 'radical' => '氵', 'pinyin' => 'xǐ', 'pinyin_eng' => 'xi', 'meaning_thai' => 'ล้าง', 'meaning_english' => 'wash'],
            ['hanzi' => '奶', 'radical' => '女', 'pinyin' => 'nǎi', 'pinyin_eng' => 'nai', 'meaning_thai' => 'นม', 'meaning_english' => 'milk'],
            ['hanzi' => '千', 'radical' => '十', 'pinyin' => 'qiān', 'pinyin_eng' => 'qian', 'meaning_thai' => 'พัน', 'meaning_english' => 'thousand'],
            ['hanzi' => '共', 'radical' => '八', 'pinyin' => 'gòng', 'pinyin_eng' => 'gong', 'meaning_thai' => 'ร่วมกัน, รวม', 'meaning_english' => 'together, total'],
            ['hanzi' => '懂', 'radical' => '忄', 'pinyin' => 'dǒng', 'pinyin_eng' => 'dong', 'meaning_thai' => 'เข้าใจ', 'meaning_english' => 'understand'],
            ['hanzi' => '介', 'radical' => '人', 'pinyin' => 'jiè', 'pinyin_eng' => 'jie', 'meaning_thai' => 'แนะนำ, ระหว่าง', 'meaning_english' => 'introduce, between'],
            ['hanzi' => '红', 'radical' => '纟', 'pinyin' => 'hóng', 'pinyin_eng' => 'hong', 'meaning_thai' => 'สีแดง', 'meaning_english' => 'red'],
            ['hanzi' => '鱼', 'radical' => '鱼', 'pinyin' => 'yú', 'pinyin_eng' => 'yu', 'meaning_thai' => 'ปลา', 'meaning_english' => 'fish'],
            ['hanzi' => '牛', 'radical' => '牛', 'pinyin' => 'niú', 'pinyin_eng' => 'niu', 'meaning_thai' => 'วัว', 'meaning_english' => 'cow, ox'],
            ['hanzi' => '馆', 'radical' => '食', 'pinyin' => 'guǎn', 'pinyin_eng' => 'guan', 'meaning_thai' => 'สถานที่, สถาบัน', 'meaning_english' => 'hall, establishment'],
            ['hanzi' => '肉', 'radical' => '肉', 'pinyin' => 'ròu', 'pinyin_eng' => 'rou', 'meaning_thai' => 'เนื้อสัตว์', 'meaning_english' => 'meat'],
            ['hanzi' => '旅', 'radical' => '方', 'pinyin' => 'lǚ', 'pinyin_eng' => 'lv', 'meaning_thai' => 'ท่องเที่ยว', 'meaning_english' => 'travel, journey'],
            ['hanzi' => '鸡', 'radical' => '鸟', 'pinyin' => 'jī', 'pinyin_eng' => 'ji', 'meaning_thai' => 'ไก่', 'meaning_english' => 'chicken'],
            ['hanzi' => '丈', 'radical' => '一', 'pinyin' => 'zhàng', 'pinyin_eng' => 'zhang', 'meaning_thai' => 'สิบฟุต, สามี', 'meaning_english' => 'ten feet, husband'],
            ['hanzi' => '睛', 'radical' => '目', 'pinyin' => 'jīng', 'pinyin_eng' => 'jing', 'meaning_thai' => 'ตา', 'meaning_english' => 'eye'],
            ['hanzi' => '笔', 'radical' => '竹', 'pinyin' => 'bǐ', 'pinyin_eng' => 'bi', 'meaning_thai' => 'ปากกา', 'meaning_english' => 'pen'],
            ['hanzi' => '虽', 'radical' => '虍', 'pinyin' => 'suī', 'pinyin_eng' => 'sui', 'meaning_thai' => 'แม้ว่า', 'meaning_english' => 'although'],
            ['hanzi' => '啡', 'radical' => '口', 'pinyin' => 'fēi', 'pinyin_eng' => 'fei', 'meaning_thai' => 'กาแฟ', 'meaning_english' => '(part of 咖啡) coffee'],
            ['hanzi' => '课', 'radical' => '讠', 'pinyin' => 'kè', 'pinyin_eng' => 'ke', 'meaning_thai' => 'บทเรียน, ชั้นเรียน', 'meaning_english' => 'class, lesson'],
            ['hanzi' => '咖', 'radical' => '口', 'pinyin' => 'kā', 'pinyin_eng' => 'ka', 'meaning_thai' => 'กาแฟ', 'meaning_english' => '(part of 咖啡) coffee'],
            ['hanzi' => '纸', 'radical' => '纟', 'pinyin' => 'zhǐ', 'pinyin_eng' => 'zhi', 'meaning_thai' => 'กระดาษ', 'meaning_english' => 'paper'],
            ['hanzi' => '左', 'radical' => '工', 'pinyin' => 'zuǒ', 'pinyin_eng' => 'zuo', 'meaning_thai' => 'ซ้าย', 'meaning_english' => 'left'],
            ['hanzi' => '右', 'radical' => '口', 'pinyin' => 'yòu', 'pinyin_eng' => 'you', 'meaning_thai' => 'ขวา', 'meaning_english' => 'right'],
            ['hanzi' => '旁', 'radical' => '方', 'pinyin' => 'páng', 'pinyin_eng' => 'pang', 'meaning_thai' => 'ข้างๆ', 'meaning_english' => 'beside, side'],
            ['hanzi' => '雪', 'radical' => '雨', 'pinyin' => 'xuě', 'pinyin_eng' => 'xue', 'meaning_thai' => 'หิมะ', 'meaning_english' => 'snow'],
            ['hanzi' => '贵', 'radical' => '贝', 'pinyin' => 'guì', 'pinyin_eng' => 'gui', 'meaning_thai' => 'แพง', 'meaning_english' => 'expensive'],
            ['hanzi' => '汽', 'radical' => '氵', 'pinyin' => 'qì', 'pinyin_eng' => 'qi', 'meaning_thai' => 'ไอน้ำ, แก๊ส', 'meaning_english' => 'steam, gas'],
            ['hanzi' => '瓜', 'radical' => '瓜', 'pinyin' => 'guā', 'pinyin_eng' => 'gua', 'meaning_thai' => 'แตง', 'meaning_english' => 'melon'],
            ['hanzi' => '阴', 'radical' => '阝', 'pinyin' => 'yīn', 'pinyin_eng' => 'yin', 'meaning_thai' => 'มืดครึ้ม, ลบ', 'meaning_english' => 'cloudy, negative'],
            ['hanzi' => '累', 'radical' => '糸', 'pinyin' => 'lèi', 'pinyin_eng' => 'lei', 'meaning_thai' => 'เหนื่อย', 'meaning_english' => 'tired'],
            ['hanzi' => '绍', 'radical' => '纟', 'pinyin' => 'shào', 'pinyin_eng' => 'shao', 'meaning_thai' => 'แนะนำ, ต่อเนื่อง', 'meaning_english' => 'introduce, continue'],
            ['hanzi' => '踢', 'radical' => '足', 'pinyin' => 'tī', 'pinyin_eng' => 'ti', 'meaning_thai' => 'เตะ', 'meaning_english' => 'kick'],
            ['hanzi' => '宾', 'radical' => '宀', 'pinyin' => 'bīn', 'pinyin_eng' => 'bin', 'meaning_thai' => 'แขก', 'meaning_english' => 'guest'],
            ['hanzi' => '泳', 'radical' => '氵', 'pinyin' => 'yǒng', 'pinyin_eng' => 'yong', 'meaning_thai' => 'ว่ายน้ำ', 'meaning_english' => 'swim'],
            ['hanzi' => '零', 'radical' => '雨', 'pinyin' => 'líng', 'pinyin_eng' => 'ling', 'meaning_thai' => 'ศูนย์', 'meaning_english' => 'zero'],
            ['hanzi' => '羊', 'radical' => '羊', 'pinyin' => 'yáng', 'pinyin_eng' => 'yang', 'meaning_thai' => 'แกะ, แพะ', 'meaning_english' => 'sheep, goat'],
            ['hanzi' => '颜', 'radical' => '页', 'pinyin' => 'yán', 'pinyin_eng' => 'yan', 'meaning_thai' => 'ใบหน้า, สี', 'meaning_english' => 'face, color'],
            ['hanzi' => '姓', 'radical' => '女', 'pinyin' => 'xìng', 'pinyin_eng' => 'xing', 'meaning_thai' => 'นามสกุล', 'meaning_english' => 'surname'],
            ['hanzi' => '篮', 'radical' => '竹', 'pinyin' => 'lán', 'pinyin_eng' => 'lan', 'meaning_thai' => 'ตะกร้า', 'meaning_english' => 'basket'],
            ['hanzi' => '宜', 'radical' => '宀', 'pinyin' => 'yí', 'pinyin_eng' => 'yi', 'meaning_thai' => 'เหมาะสม', 'meaning_english' => 'suitable'],
            ['hanzi' => '铅', 'radical' => '钅', 'pinyin' => 'qiān', 'pinyin_eng' => 'qian', 'meaning_thai' => 'ตะกั่ว', 'meaning_english' => 'lead (metal)'],
            ['hanzi' => '晴', 'radical' => '日', 'pinyin' => 'qíng', 'pinyin_eng' => 'qing', 'meaning_thai' => 'ชัดเจน, สว่าง', 'meaning_english' => 'clear, fine'],
        ]);

        // hanzi_categories HSK 2 (173)
        DB::table('hanzi_categories')->insert([
            ['hanzi_id' => 175, 'category_id' => 2],
            ['hanzi_id' => 176, 'category_id' => 2],
            ['hanzi_id' => 177, 'category_id' => 2],
            ['hanzi_id' => 178, 'category_id' => 2],
            ['hanzi_id' => 179, 'category_id' => 2],
            ['hanzi_id' => 180, 'category_id' => 2],
            ['hanzi_id' => 181, 'category_id' => 2],
            ['hanzi_id' => 182, 'category_id' => 2],
            ['hanzi_id' => 183, 'category_id' => 2],
            ['hanzi_id' => 184, 'category_id' => 2],
            ['hanzi_id' => 185, 'category_id' => 2],
            ['hanzi_id' => 186, 'category_id' => 2],
            ['hanzi_id' => 187, 'category_id' => 2],
            ['hanzi_id' => 188, 'category_id' => 2],
            ['hanzi_id' => 189, 'category_id' => 2],
            ['hanzi_id' => 190, 'category_id' => 2],
            ['hanzi_id' => 191, 'category_id' => 2],
            ['hanzi_id' => 192, 'category_id' => 2],
            ['hanzi_id' => 193, 'category_id' => 2],
            ['hanzi_id' => 194, 'category_id' => 2],
            ['hanzi_id' => 195, 'category_id' => 2],
            ['hanzi_id' => 196, 'category_id' => 2],
            ['hanzi_id' => 197, 'category_id' => 2],
            ['hanzi_id' => 198, 'category_id' => 2],
            ['hanzi_id' => 199, 'category_id' => 2],
            ['hanzi_id' => 200, 'category_id' => 2],
            ['hanzi_id' => 201, 'category_id' => 2],
            ['hanzi_id' => 202, 'category_id' => 2],
            ['hanzi_id' => 203, 'category_id' => 2],
            ['hanzi_id' => 204, 'category_id' => 2],
            ['hanzi_id' => 205, 'category_id' => 2],
            ['hanzi_id' => 206, 'category_id' => 2],
            ['hanzi_id' => 207, 'category_id' => 2],
            ['hanzi_id' => 208, 'category_id' => 2],
            ['hanzi_id' => 209, 'category_id' => 2],
            ['hanzi_id' => 210, 'category_id' => 2],
            ['hanzi_id' => 211, 'category_id' => 2],
            ['hanzi_id' => 212, 'category_id' => 2],
            ['hanzi_id' => 213, 'category_id' => 2],
            ['hanzi_id' => 214, 'category_id' => 2],
            ['hanzi_id' => 215, 'category_id' => 2],
            ['hanzi_id' => 216, 'category_id' => 2],
            ['hanzi_id' => 217, 'category_id' => 2],
            ['hanzi_id' => 218, 'category_id' => 2],
            ['hanzi_id' => 219, 'category_id' => 2],
            ['hanzi_id' => 220, 'category_id' => 2],
            ['hanzi_id' => 221, 'category_id' => 2],
            ['hanzi_id' => 222, 'category_id' => 2],
            ['hanzi_id' => 223, 'category_id' => 2],
            ['hanzi_id' => 224, 'category_id' => 2],
            ['hanzi_id' => 225, 'category_id' => 2],
            ['hanzi_id' => 226, 'category_id' => 2],
            ['hanzi_id' => 227, 'category_id' => 2],
            ['hanzi_id' => 228, 'category_id' => 2],
            ['hanzi_id' => 229, 'category_id' => 2],
            ['hanzi_id' => 230, 'category_id' => 2],
            ['hanzi_id' => 231, 'category_id' => 2],
            ['hanzi_id' => 232, 'category_id' => 2],
            ['hanzi_id' => 233, 'category_id' => 2],
            ['hanzi_id' => 234, 'category_id' => 2],
            ['hanzi_id' => 235, 'category_id' => 2],
            ['hanzi_id' => 236, 'category_id' => 2],
            ['hanzi_id' => 237, 'category_id' => 2],
            ['hanzi_id' => 238, 'category_id' => 2],
            ['hanzi_id' => 239, 'category_id' => 2],
            ['hanzi_id' => 240, 'category_id' => 2],
            ['hanzi_id' => 241, 'category_id' => 2],
            ['hanzi_id' => 242, 'category_id' => 2],
            ['hanzi_id' => 243, 'category_id' => 2],
            ['hanzi_id' => 244, 'category_id' => 2],
            ['hanzi_id' => 245, 'category_id' => 2],
            ['hanzi_id' => 246, 'category_id' => 2],
            ['hanzi_id' => 247, 'category_id' => 2],
            ['hanzi_id' => 248, 'category_id' => 2],
            ['hanzi_id' => 249, 'category_id' => 2],
            ['hanzi_id' => 250, 'category_id' => 2],
            ['hanzi_id' => 251, 'category_id' => 2],
            ['hanzi_id' => 252, 'category_id' => 2],
            ['hanzi_id' => 253, 'category_id' => 2],
            ['hanzi_id' => 254, 'category_id' => 2],
            ['hanzi_id' => 255, 'category_id' => 2],
            ['hanzi_id' => 256, 'category_id' => 2],
            ['hanzi_id' => 257, 'category_id' => 2],
            ['hanzi_id' => 258, 'category_id' => 2],
            ['hanzi_id' => 259, 'category_id' => 2],
            ['hanzi_id' => 260, 'category_id' => 2],
            ['hanzi_id' => 261, 'category_id' => 2],
            ['hanzi_id' => 262, 'category_id' => 2],
            ['hanzi_id' => 263, 'category_id' => 2],
            ['hanzi_id' => 264, 'category_id' => 2],
            ['hanzi_id' => 265, 'category_id' => 2],
            ['hanzi_id' => 266, 'category_id' => 2],
            ['hanzi_id' => 267, 'category_id' => 2],
            ['hanzi_id' => 268, 'category_id' => 2],
            ['hanzi_id' => 269, 'category_id' => 2],
            ['hanzi_id' => 270, 'category_id' => 2],
            ['hanzi_id' => 271, 'category_id' => 2],
            ['hanzi_id' => 272, 'category_id' => 2],
            ['hanzi_id' => 273, 'category_id' => 2],
            ['hanzi_id' => 274, 'category_id' => 2],
            ['hanzi_id' => 275, 'category_id' => 2],
            ['hanzi_id' => 276, 'category_id' => 2],
            ['hanzi_id' => 277, 'category_id' => 2],
            ['hanzi_id' => 278, 'category_id' => 2],
            ['hanzi_id' => 279, 'category_id' => 2],
            ['hanzi_id' => 280, 'category_id' => 2],
            ['hanzi_id' => 281, 'category_id' => 2],
            ['hanzi_id' => 282, 'category_id' => 2],
            ['hanzi_id' => 283, 'category_id' => 2],
            ['hanzi_id' => 284, 'category_id' => 2],
            ['hanzi_id' => 285, 'category_id' => 2],
            ['hanzi_id' => 286, 'category_id' => 2],
            ['hanzi_id' => 287, 'category_id' => 2],
            ['hanzi_id' => 288, 'category_id' => 2],
            ['hanzi_id' => 289, 'category_id' => 2],
            ['hanzi_id' => 290, 'category_id' => 2],
            ['hanzi_id' => 291, 'category_id' => 2],
            ['hanzi_id' => 292, 'category_id' => 2],
            ['hanzi_id' => 293, 'category_id' => 2],
            ['hanzi_id' => 294, 'category_id' => 2],
            ['hanzi_id' => 295, 'category_id' => 2],
            ['hanzi_id' => 296, 'category_id' => 2],
            ['hanzi_id' => 297, 'category_id' => 2],
            ['hanzi_id' => 298, 'category_id' => 2],
            ['hanzi_id' => 299, 'category_id' => 2],
            ['hanzi_id' => 300, 'category_id' => 2],
            ['hanzi_id' => 301, 'category_id' => 2],
            ['hanzi_id' => 302, 'category_id' => 2],
            ['hanzi_id' => 303, 'category_id' => 2],
            ['hanzi_id' => 304, 'category_id' => 2],
            ['hanzi_id' => 305, 'category_id' => 2],
            ['hanzi_id' => 306, 'category_id' => 2],
            ['hanzi_id' => 307, 'category_id' => 2],
            ['hanzi_id' => 308, 'category_id' => 2],
            ['hanzi_id' => 309, 'category_id' => 2],
            ['hanzi_id' => 310, 'category_id' => 2],
            ['hanzi_id' => 311, 'category_id' => 2],
            ['hanzi_id' => 312, 'category_id' => 2],
            ['hanzi_id' => 313, 'category_id' => 2],
            ['hanzi_id' => 314, 'category_id' => 2],
            ['hanzi_id' => 315, 'category_id' => 2],
            ['hanzi_id' => 316, 'category_id' => 2],
            ['hanzi_id' => 317, 'category_id' => 2],
            ['hanzi_id' => 318, 'category_id' => 2],
            ['hanzi_id' => 319, 'category_id' => 2],
            ['hanzi_id' => 320, 'category_id' => 2],
            ['hanzi_id' => 321, 'category_id' => 2],
            ['hanzi_id' => 322, 'category_id' => 2],
            ['hanzi_id' => 323, 'category_id' => 2],
            ['hanzi_id' => 324, 'category_id' => 2],
            ['hanzi_id' => 325, 'category_id' => 2],
            ['hanzi_id' => 326, 'category_id' => 2],
            ['hanzi_id' => 327, 'category_id' => 2],
            ['hanzi_id' => 328, 'category_id' => 2],
            ['hanzi_id' => 329, 'category_id' => 2],
            ['hanzi_id' => 330, 'category_id' => 2],
            ['hanzi_id' => 331, 'category_id' => 2],
            ['hanzi_id' => 332, 'category_id' => 2],
            ['hanzi_id' => 333, 'category_id' => 2],
            ['hanzi_id' => 334, 'category_id' => 2],
            ['hanzi_id' => 335, 'category_id' => 2],
            ['hanzi_id' => 336, 'category_id' => 2],
            ['hanzi_id' => 337, 'category_id' => 2],
            ['hanzi_id' => 338, 'category_id' => 2],
            ['hanzi_id' => 339, 'category_id' => 2],
            ['hanzi_id' => 340, 'category_id' => 2],
            ['hanzi_id' => 341, 'category_id' => 2],
            ['hanzi_id' => 342, 'category_id' => 2],
            ['hanzi_id' => 343, 'category_id' => 2],
            ['hanzi_id' => 344, 'category_id' => 2],
            ['hanzi_id' => 345, 'category_id' => 2],
            ['hanzi_id' => 346, 'category_id' => 2],
            ['hanzi_id' => 347, 'category_id' => 2],
        ]);
    }
}
