<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HanziUnCommonSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // hanzi Common Hanzi (3462)
        DB::table('hanzi')->insert([
            ['hanzi' => '丨', 'radical' => '丨', 'pinyin' => 'gǔn', 'pinyin_eng' => 'gun', 'meaning_thai' => 'เส้น', 'meaning_english' => 'line'],
            ['hanzi' => '丶', 'radical' => '丶', 'pinyin' => 'zhǔ', 'pinyin_eng' => 'zhu', 'meaning_thai' => 'จุด', 'meaning_english' => 'dot'],
            ['hanzi' => '丿', 'radical' => '丿', 'pinyin' => 'piě', 'pinyin_eng' => 'pie', 'meaning_thai' => 'เส้นเฉียง', 'meaning_english' => 'slash'],
            ['hanzi' => '亅', 'radical' => '亅', 'pinyin' => 'jué', 'pinyin_eng' => 'jue', 'meaning_thai' => 'ตะขอ', 'meaning_english' => 'hook'],
            ['hanzi' => '亠', 'radical' => '亠', 'pinyin' => 'tóu', 'pinyin_eng' => 'tou', 'meaning_thai' => 'ฝา', 'meaning_english' => 'lid'],
            ['hanzi' => '冂', 'radical' => '冂', 'pinyin' => 'jiōng', 'pinyin_eng' => 'jiong', 'meaning_thai' => 'กล่องล่าง', 'meaning_english' => 'down box'],
            ['hanzi' => '冖', 'radical' => '冖', 'pinyin' => 'mì', 'pinyin_eng' => 'mi', 'meaning_thai' => 'ปก', 'meaning_english' => 'cover'],
            ['hanzi' => '冫', 'radical' => '冫', 'pinyin' => 'bīng', 'pinyin_eng' => 'bing', 'meaning_thai' => 'น้ำแข็ง', 'meaning_english' => 'ice'],
            ['hanzi' => '凵', 'radical' => '凵', 'pinyin' => 'qiǎn', 'pinyin_eng' => 'qian', 'meaning_thai' => 'กล่องเปิด', 'meaning_english' => 'open box'],
            ['hanzi' => '勹', 'radical' => '勹', 'pinyin' => 'bāo', 'pinyin_eng' => 'bao', 'meaning_thai' => 'ห่อ', 'meaning_english' => 'wrap'],
            ['hanzi' => '匚', 'radical' => '匚', 'pinyin' => 'fāng', 'pinyin_eng' => 'fang', 'meaning_thai' => 'กล่อง', 'meaning_english' => 'box'],
            ['hanzi' => '匸', 'radical' => '匸', 'pinyin' => 'xǐ', 'pinyin_eng' => 'xi', 'meaning_thai' => 'การซ่อน', 'meaning_english' => 'hiding enclosure'],
            ['hanzi' => '卩', 'radical' => '卩', 'pinyin' => 'jié', 'pinyin_eng' => 'jie', 'meaning_thai' => 'ประทับตรา', 'meaning_english' => 'seal'],
            ['hanzi' => '厶', 'radical' => '厶', 'pinyin' => 'sī', 'pinyin_eng' => 'si', 'meaning_thai' => 'ส่วนตัว', 'meaning_english' => 'private'],
            ['hanzi' => '囗', 'radical' => '囗', 'pinyin' => 'wéi', 'pinyin_eng' => 'wei', 'meaning_thai' => 'การล้อมรั้ว', 'meaning_english' => 'enclosure'],
            ['hanzi' => '夂', 'radical' => '夂', 'pinyin' => 'zhǐ', 'pinyin_eng' => 'zhi', 'meaning_thai' => 'ไป', 'meaning_english' => 'go'],
            ['hanzi' => '夊', 'radical' => '夊', 'pinyin' => 'suī', 'pinyin_eng' => 'sui', 'meaning_thai' => 'เดินช้า', 'meaning_english' => 'go slowly'],
            ['hanzi' => '宀', 'radical' => '宀', 'pinyin' => 'mián', 'pinyin_eng' => 'mian', 'meaning_thai' => 'หลังคา', 'meaning_english' => 'roof'],
            ['hanzi' => '尢', 'radical' => '尢', 'pinyin' => 'wāng', 'pinyin_eng' => 'wang', 'meaning_thai' => 'ขากะเผลก', 'meaning_english' => 'lame'],
            ['hanzi' => '屮', 'radical' => '屮', 'pinyin' => 'chè', 'pinyin_eng' => 'che', 'meaning_thai' => 'ต้นอ่อน', 'meaning_english' => 'sprout'],
            ['hanzi' => '巛', 'radical' => '巛', 'pinyin' => 'chuān', 'pinyin_eng' => 'chuan', 'meaning_thai' => 'แม่น้ำ', 'meaning_english' => 'river'],
            ['hanzi' => '廴', 'radical' => '廴', 'pinyin' => 'yǐn', 'pinyin_eng' => 'yin', 'meaning_thai' => 'ก้าวยาว', 'meaning_english' => 'long stride'],
            ['hanzi' => '廾', 'radical' => '廾', 'pinyin' => 'gǒng', 'pinyin_eng' => 'gong', 'meaning_thai' => 'สองมือ', 'meaning_english' => 'two hands'],
            ['hanzi' => '彐', 'radical' => '彐', 'pinyin' => 'jì', 'pinyin_eng' => 'ji', 'meaning_thai' => 'ปาก', 'meaning_english' => 'snout'],
            ['hanzi' => '彡', 'radical' => '彡', 'pinyin' => 'shān', 'pinyin_eng' => 'shan', 'meaning_thai' => 'ขนแข็ง', 'meaning_english' => 'bristle'],
            ['hanzi' => '攴', 'radical' => '攴', 'pinyin' => 'pū', 'pinyin_eng' => 'pu', 'meaning_thai' => 'ตี', 'meaning_english' => 'tap'],
            ['hanzi' => '疋', 'radical' => '疋', 'pinyin' => 'pǐ', 'pinyin_eng' => 'pi', 'meaning_thai' => 'เท้า', 'meaning_english' => 'foot'],
            ['hanzi' => '疒', 'radical' => '疒', 'pinyin' => 'nè', 'pinyin_eng' => 'ne', 'meaning_thai' => 'ความเจ็บป่วย', 'meaning_english' => 'sickness'],
            ['hanzi' => '癶', 'radical' => '癶', 'pinyin' => 'bō', 'pinyin_eng' => 'bo', 'meaning_thai' => 'รอยเท้า', 'meaning_english' => 'footsteps'],
            ['hanzi' => '禸', 'radical' => '禸', 'pinyin' => 'róu', 'pinyin_eng' => 'rou', 'meaning_thai' => 'ทางเดิน', 'meaning_english' => 'track'],
            ['hanzi' => '糸', 'radical' => '糸', 'pinyin' => 'mì', 'pinyin_eng' => 'mi', 'meaning_thai' => 'ไหม', 'meaning_english' => 'silk'],
            ['hanzi' => '虍', 'radical' => '虍', 'pinyin' => 'hū', 'pinyin_eng' => 'hu', 'meaning_thai' => 'เสือ', 'meaning_english' => 'tiger'],
            ['hanzi' => '襾', 'radical' => '襾', 'pinyin' => 'yà', 'pinyin_eng' => 'ya', 'meaning_thai' => 'ตะวันตก', 'meaning_english' => 'west'],
            ['hanzi' => '辵', 'radical' => '辵', 'pinyin' => 'chuò', 'pinyin_eng' => 'chuo', 'meaning_thai' => 'เดิน', 'meaning_english' => 'walk'],
            ['hanzi' => '釆', 'radical' => '釆', 'pinyin' => 'biàn', 'pinyin_eng' => 'bian', 'meaning_thai' => 'แยกแยะ', 'meaning_english' => 'distinguish'],
            ['hanzi' => '隹', 'radical' => '隹', 'pinyin' => 'zhuī', 'pinyin_eng' => 'zhui', 'meaning_thai' => 'นกหางสั้น', 'meaning_english' => 'short-tailed bird'],
            ['hanzi' => '髟', 'radical' => '髟', 'pinyin' => 'biāo', 'pinyin_eng' => 'biao', 'meaning_thai' => 'ผมยาว', 'meaning_english' => 'long hair'],
            ['hanzi' => '䒑', 'radical' => '䒑', 'pinyin' => 'huáng', 'pinyin_eng' => 'huang', 'meaning_thai' => 'หญ้า', 'meaning_english' => 'grass'],
            ['hanzi' => '丄', 'radical' => '丄', 'pinyin' => 'shàng', 'pinyin_eng' => 'shang', 'meaning_thai' => 'ขึ้น', 'meaning_english' => 'up'],
            ['hanzi' => '丆', 'radical' => '丆', 'pinyin' => 'há', 'pinyin_eng' => 'ha', 'meaning_thai' => 'ลง', 'meaning_english' => 'down'],
            ['hanzi' => '乁', 'radical' => '乁', 'pinyin' => 'yí', 'pinyin_eng' => 'yi', 'meaning_thai' => 'สอง', 'meaning_english' => 'second'],
            ['hanzi' => '乚', 'radical' => '乚', 'pinyin' => 'yǐn', 'pinyin_eng' => 'yin', 'meaning_thai' => 'ซ่อน', 'meaning_english' => 'hidden'],
            ['hanzi' => '乛', 'radical' => '乛', 'pinyin' => 'yǎ', 'pinyin_eng' => 'ya', 'meaning_thai' => 'เส้นโค้ง', 'meaning_english' => 'curved stroke'],
            ['hanzi' => '亇', 'radical' => '亇', 'pinyin' => 'má', 'pinyin_eng' => 'ma', 'meaning_thai' => 'คน', 'meaning_english' => 'man'],
            ['hanzi' => '亼', 'radical' => '亼', 'pinyin' => 'jí', 'pinyin_eng' => 'ji', 'meaning_thai' => 'รวมกัน', 'meaning_english' => 'assemble'],
            ['hanzi' => '𠂇', 'radical' => '𠂇', 'pinyin' => 'yáo', 'pinyin_eng' => 'yao', 'meaning_thai' => 'น้อย', 'meaning_english' => 'little'],
            ['hanzi' => '氶', 'radical' => '氶', 'pinyin' => 'zhěng', 'pinyin_eng' => 'zheng', 'meaning_thai' => 'ไอน้ำ', 'meaning_english' => 'steam'],
            ['hanzi' => '辶', 'radical' => '辶', 'pinyin' => 'chuò', 'pinyin_eng' => 'chuo', 'meaning_thai' => 'เดิน', 'meaning_english' => 'walk'],
            ['hanzi' => '妟', 'radical' => '妟', 'pinyin' => 'yàn', 'pinyin_eng' => 'yan', 'meaning_thai' => 'สวยงาม', 'meaning_english' => 'beautiful'],
            ['hanzi' => '卄', 'radical' => '卄', 'pinyin' => 'niàn', 'pinyin_eng' => 'nian', 'meaning_thai' => 'ยี่สิบ', 'meaning_english' => 'twenty'],
            ['hanzi' => '刂', 'radical' => '刂', 'pinyin' => 'dāo', 'pinyin_eng' => 'dao', 'meaning_thai' => 'มีด', 'meaning_english' => 'knife'],
            ['hanzi' => '尣', 'radical' => '尣', 'pinyin' => 'wāng', 'pinyin_eng' => 'wang', 'meaning_thai' => 'ขากะเผลก', 'meaning_english' => 'lame'],
            ['hanzi' => '巜', 'radical' => '巜', 'pinyin' => 'guì', 'pinyin_eng' => 'gui', 'meaning_thai' => 'แม่น้ำ', 'meaning_english' => 'river'],
            ['hanzi' => '肀', 'radical' => '肀', 'pinyin' => 'yù', 'pinyin_eng' => 'yu', 'meaning_thai' => 'แปรง', 'meaning_english' => 'brush'],
            ['hanzi' => '罒', 'radical' => '罒', 'pinyin' => 'wǎng', 'pinyin_eng' => 'wang', 'meaning_thai' => 'ตาข่าย', 'meaning_english' => 'net'],
            ['hanzi' => '彑', 'radical' => '彑', 'pinyin' => 'jì', 'pinyin_eng' => 'ji', 'meaning_thai' => 'ปาก', 'meaning_english' => 'snout'],
            ['hanzi' => '丩', 'radical' => '丩', 'pinyin' => 'jiū', 'pinyin_eng' => 'jiu', 'meaning_thai' => 'พันกัน', 'meaning_english' => 'entwine'],
            ['hanzi' => '艹', 'radical' => '艹', 'pinyin' => 'cǎo', 'pinyin_eng' => 'cao', 'meaning_thai' => 'หญ้า', 'meaning_english' => 'grass'],
            ['hanzi' => '帀', 'radical' => '帀', 'pinyin' => 'zā', 'pinyin_eng' => 'za', 'meaning_thai' => 'ปก', 'meaning_english' => 'cover'],
            ['hanzi' => '丬', 'radical' => '丬', 'pinyin' => 'qiáng', 'pinyin_eng' => 'qiang', 'meaning_thai' => 'ครึ่งลำต้น', 'meaning_english' => 'half tree trunk'],
            ['hanzi' => '昜', 'radical' => '昜', 'pinyin' => 'yáng', 'pinyin_eng' => 'yang', 'meaning_thai' => 'พระอาทิตย์', 'meaning_english' => 'sun'],
            ['hanzi' => '雚', 'radical' => '雚', 'pinyin' => 'guàn', 'pinyin_eng' => 'guan', 'meaning_thai' => 'นกกระสา', 'meaning_english' => 'stork'],
            ['hanzi' => '亽', 'radical' => '亽', 'pinyin' => 'rén', 'pinyin_eng' => 'ren', 'meaning_thai' => 'คน', 'meaning_english' => 'man'],
            ['hanzi' => '卬', 'radical' => '卬', 'pinyin' => 'áng', 'pinyin_eng' => 'ang', 'meaning_thai' => 'ยก', 'meaning_english' => 'raise'],
            ['hanzi' => '朩', 'radical' => '朩', 'pinyin' => 'mù', 'pinyin_eng' => 'mu', 'meaning_thai' => 'ต้นไม้', 'meaning_english' => 'tree'],
            ['hanzi' => '夋', 'radical' => '夋', 'pinyin' => 'jùn', 'pinyin_eng' => 'jun', 'meaning_thai' => 'มีความสามารถ', 'meaning_english' => 'capable'],
            ['hanzi' => '㣊', 'radical' => '㣊', 'pinyin' => 'xián', 'pinyin_eng' => 'xian', 'meaning_thai' => 'อย่างไม่รีบ', 'meaning_english' => 'leisurely'],
            ['hanzi' => '咅', 'radical' => '咅', 'pinyin' => 'pǒu', 'pinyin_eng' => 'pou', 'meaning_thai' => 'แบ่ง', 'meaning_english' => 'to divide'],
            ['hanzi' => '侖', 'radical' => '侖', 'pinyin' => 'lún', 'pinyin_eng' => 'lun', 'meaning_thai' => 'เป็นระเบียบ', 'meaning_english' => 'orderly'],
            ['hanzi' => '豖', 'radical' => '豖', 'pinyin' => 'chù', 'pinyin_eng' => 'chu', 'meaning_thai' => 'หมู', 'meaning_english' => 'pig'],
            ['hanzi' => '丂', 'radical' => '丂', 'pinyin' => 'kǎo', 'pinyin_eng' => 'kao', 'meaning_thai' => 'เคียว', 'meaning_english' => 'sickle'],
            ['hanzi' => '戉', 'radical' => '戉', 'pinyin' => 'yuè', 'pinyin_eng' => 'yue', 'meaning_thai' => 'ขวานรบ', 'meaning_english' => 'battle-axe'],
            ['hanzi' => '乇', 'radical' => '乇', 'pinyin' => 'tuō', 'pinyin_eng' => 'tuo', 'meaning_thai' => 'ถือขึ้น', 'meaning_english' => 'hold up'],
            ['hanzi' => '仌', 'radical' => '仌', 'pinyin' => 'bīng', 'pinyin_eng' => 'bing', 'meaning_thai' => 'น้ำแข็ง', 'meaning_english' => 'ice'],
            ['hanzi' => '彥', 'radical' => '彥', 'pinyin' => 'yàn', 'pinyin_eng' => 'yan', 'meaning_thai' => 'สง่างาม', 'meaning_english' => 'elegant'],
            ['hanzi' => '壴', 'radical' => '壴', 'pinyin' => 'zhù', 'pinyin_eng' => 'zhu', 'meaning_thai' => 'กลอง', 'meaning_english' => 'drum'],
            ['hanzi' => '々', 'radical' => '々', 'pinyin' => '々', 'pinyin_eng' => '々', 'meaning_thai' => 'เครื่องหมายซ้ำ', 'meaning_english' => 'repetition sign'],
            // ['hanzi' => '𠃌', 'radical' => '𠃌', 'pinyin' => 'yì', 'pinyin_eng' => 'yi', 'meaning_thai' => 'บิดเบี้ยว', 'meaning_english' => 'twisted'],
            // ['hanzi' => '𡿨', 'radical' => '𡿨', 'pinyin' => 'xiàn', 'pinyin_eng' => 'xian', 'meaning_thai' => 'เส้นแนวตั้ง', 'meaning_english' => 'vertical line'],
            // ['hanzi' => '㔾', 'radical' => '㔾', 'pinyin' => 'jié', 'pinyin_eng' => 'jie', 'meaning_thai' => 'ประทับตรา', 'meaning_english' => 'seal'],
            // ['hanzi' => '𠂆', 'radical' => '𠂆', 'pinyin' => 'qū', 'pinyin_eng' => 'qu', 'meaning_thai' => 'โค้ง', 'meaning_english' => 'bent'],
            // ['hanzi' => '𠄌', 'radical' => '𠄌', 'pinyin' => 'gǒng', 'pinyin_eng' => 'gong', 'meaning_thai' => 'โค้ง', 'meaning_english' => 'bow'],
            // ['hanzi' => '𫩏', 'radical' => '𫩏', 'pinyin' => 'fū', 'pinyin_eng' => 'fu', 'meaning_thai' => 'มัด', 'meaning_english' => 'bundle'],
            // ['hanzi' => '𢆉', 'radical' => '𢆉', 'pinyin' => 'kě', 'pinyin_eng' => 'ke', 'meaning_thai' => 'โพรง', 'meaning_english' => 'cavity'],
            // ['hanzi' => '𫶧', 'radical' => '𫶧', 'pinyin' => 'sǒu', 'pinyin_eng' => 'sou', 'meaning_thai' => 'วิญญาณ', 'meaning_english' => 'soul'],
            // ['hanzi' => '𠬶', 'radical' => '𠬶', 'pinyin' => 'chōu', 'pinyin_eng' => 'chou', 'meaning_thai' => 'ชิ้นเล็กๆ', 'meaning_english' => 'chip'],
            // ['hanzi' => '𠕁', 'radical' => '𠕁', 'pinyin' => 'hé', 'pinyin_eng' => 'he', 'meaning_thai' => 'และ', 'meaning_english' => 'and'],
            // ['hanzi' => '𠀃', 'radical' => '𠀃', 'pinyin' => 'lù', 'pinyin_eng' => 'lu', 'meaning_thai' => 'ทางเดิน', 'meaning_english' => 'path'],
            // ['hanzi' => '𫠠', 'radical' => '𫠠', 'pinyin' => 'yáo', 'pinyin_eng' => 'yao', 'meaning_thai' => 'สูง', 'meaning_english' => 'tall'],
        ]);

        // hanzi_categories Common Hanzi (3462)
        DB::table('hanzi_categories')->insert([
            ['hanzi_id' => 7238, 'category_id' => 10],
            ['hanzi_id' => 7239, 'category_id' => 10],
            ['hanzi_id' => 7240, 'category_id' => 10],
            ['hanzi_id' => 7241, 'category_id' => 10],
            ['hanzi_id' => 7242, 'category_id' => 10],
            ['hanzi_id' => 7243, 'category_id' => 10],
            ['hanzi_id' => 7244, 'category_id' => 10],
            ['hanzi_id' => 7245, 'category_id' => 10],
            ['hanzi_id' => 7246, 'category_id' => 10],
            ['hanzi_id' => 7247, 'category_id' => 10],
            ['hanzi_id' => 7248, 'category_id' => 10],
            ['hanzi_id' => 7249, 'category_id' => 10],
            ['hanzi_id' => 7250, 'category_id' => 10],
            ['hanzi_id' => 7251, 'category_id' => 10],
            ['hanzi_id' => 7252, 'category_id' => 10],
            ['hanzi_id' => 7253, 'category_id' => 10],
            ['hanzi_id' => 7254, 'category_id' => 10],
            ['hanzi_id' => 7255, 'category_id' => 10],
            ['hanzi_id' => 7256, 'category_id' => 10],
            ['hanzi_id' => 7257, 'category_id' => 10],
            ['hanzi_id' => 7258, 'category_id' => 10],
            ['hanzi_id' => 7259, 'category_id' => 10],
            ['hanzi_id' => 7260, 'category_id' => 10],
            ['hanzi_id' => 7261, 'category_id' => 10],
            ['hanzi_id' => 7262, 'category_id' => 10],
            ['hanzi_id' => 7263, 'category_id' => 10],
            ['hanzi_id' => 7264, 'category_id' => 10],
            ['hanzi_id' => 7265, 'category_id' => 10],
            ['hanzi_id' => 7266, 'category_id' => 10],
            ['hanzi_id' => 7267, 'category_id' => 10],
            ['hanzi_id' => 7268, 'category_id' => 10],
            ['hanzi_id' => 7269, 'category_id' => 10],
            ['hanzi_id' => 7270, 'category_id' => 10],
            ['hanzi_id' => 7271, 'category_id' => 10],
            ['hanzi_id' => 7272, 'category_id' => 10],
            ['hanzi_id' => 7273, 'category_id' => 10],
            ['hanzi_id' => 7274, 'category_id' => 10],
            ['hanzi_id' => 7275, 'category_id' => 10],
            ['hanzi_id' => 7276, 'category_id' => 10],
            ['hanzi_id' => 7277, 'category_id' => 10],
            ['hanzi_id' => 7278, 'category_id' => 10],
            ['hanzi_id' => 7279, 'category_id' => 10],
            ['hanzi_id' => 7280, 'category_id' => 10],
            ['hanzi_id' => 7281, 'category_id' => 10],
            ['hanzi_id' => 7282, 'category_id' => 10],
            ['hanzi_id' => 7283, 'category_id' => 10],
            ['hanzi_id' => 7284, 'category_id' => 10],
            ['hanzi_id' => 7285, 'category_id' => 10],
            ['hanzi_id' => 7286, 'category_id' => 10],
            ['hanzi_id' => 7287, 'category_id' => 10],
            ['hanzi_id' => 7288, 'category_id' => 10],
            ['hanzi_id' => 7289, 'category_id' => 10],
            ['hanzi_id' => 7290, 'category_id' => 10],
            ['hanzi_id' => 7291, 'category_id' => 10],
            ['hanzi_id' => 7292, 'category_id' => 10],
            ['hanzi_id' => 7293, 'category_id' => 10],
            ['hanzi_id' => 7294, 'category_id' => 10],
            ['hanzi_id' => 7295, 'category_id' => 10],
            ['hanzi_id' => 7296, 'category_id' => 10],
            ['hanzi_id' => 7297, 'category_id' => 10],
            ['hanzi_id' => 7298, 'category_id' => 10],
            ['hanzi_id' => 7299, 'category_id' => 10],
            ['hanzi_id' => 7300, 'category_id' => 10],
            ['hanzi_id' => 7301, 'category_id' => 10],
            ['hanzi_id' => 7302, 'category_id' => 10],
            ['hanzi_id' => 7303, 'category_id' => 10],
            ['hanzi_id' => 7304, 'category_id' => 10],
            ['hanzi_id' => 7305, 'category_id' => 10],
            ['hanzi_id' => 7306, 'category_id' => 10],
            ['hanzi_id' => 7307, 'category_id' => 10],
            ['hanzi_id' => 7308, 'category_id' => 10],
            ['hanzi_id' => 7309, 'category_id' => 10],
            ['hanzi_id' => 7310, 'category_id' => 10],
            ['hanzi_id' => 7311, 'category_id' => 10],
            ['hanzi_id' => 7312, 'category_id' => 10],
            ['hanzi_id' => 7313, 'category_id' => 10],
            ['hanzi_id' => 7314, 'category_id' => 10],
            // ['hanzi_id' => 7315, 'category_id' => 10],
            // ['hanzi_id' => 7316, 'category_id' => 10],
            // ['hanzi_id' => 7317, 'category_id' => 10],
            // ['hanzi_id' => 7318, 'category_id' => 10],
            // ['hanzi_id' => 7319, 'category_id' => 10],
            // ['hanzi_id' => 7320, 'category_id' => 10],
            // ['hanzi_id' => 7321, 'category_id' => 10],
            // ['hanzi_id' => 7322, 'category_id' => 10],
            // ['hanzi_id' => 7323, 'category_id' => 10],
            // ['hanzi_id' => 7324, 'category_id' => 10],
            // ['hanzi_id' => 7325, 'category_id' => 10],
            // ['hanzi_id' => 7326, 'category_id' => 10],
        ]);
    }
}
