<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HanziHSK4Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // hanzi HSK 4 (447)
        DB::table('hanzi')->insert([
            ['hanzi' => '死', 'radical' => '歹', 'pinyin' => 'sǐ', 'pinyin_eng' => 'si', 'meaning_thai' => 'ตาย', 'meaning_english' => 'to die'],
            ['hanzi' => '之', 'radical' => '丶', 'pinyin' => 'zhī', 'pinyin_eng' => 'zhi', 'meaning_thai' => 'ของ', 'meaning_english' => 'of'],
            ['hanzi' => '克', 'radical' => '十', 'pinyin' => 'kè', 'pinyin_eng' => 'ke', 'meaning_thai' => 'เอาชนะ', 'meaning_english' => 'to overcome'],
            ['hanzi' => '无', 'radical' => '无', 'pinyin' => 'wú', 'pinyin_eng' => 'wu', 'meaning_thai' => 'ไม่มี', 'meaning_english' => 'without'],
            ['hanzi' => '全', 'radical' => '入', 'pinyin' => 'quán', 'pinyin_eng' => 'quan', 'meaning_thai' => 'ทั้งหมด', 'meaning_english' => 'whole'],
            ['hanzi' => '美', 'radical' => '羊', 'pinyin' => 'měi', 'pinyin_eng' => 'mei', 'meaning_thai' => 'สวยงาม', 'meaning_english' => 'beautiful'],
            ['hanzi' => '许', 'radical' => '讠', 'pinyin' => 'xǔ', 'pinyin_eng' => 'xu', 'meaning_thai' => 'อนุญาต', 'meaning_english' => 'to allow'],
            ['hanzi' => '亲', 'radical' => '見', 'pinyin' => 'qīn', 'pinyin_eng' => 'qin', 'meaning_thai' => 'ญาติ', 'meaning_english' => 'relative'],
            ['hanzi' => '尔', 'radical' => '小', 'pinyin' => 'ěr', 'pinyin_eng' => 'er', 'meaning_thai' => 'คุณ', 'meaning_english' => 'you'],
            ['hanzi' => '保', 'radical' => '亻', 'pinyin' => 'bǎo', 'pinyin_eng' => 'bao', 'meaning_thai' => 'ปกป้อง', 'meaning_english' => 'to protect'],
            ['hanzi' => '受', 'radical' => '又', 'pinyin' => 'shòu', 'pinyin_eng' => 'shou', 'meaning_thai' => 'รับ', 'meaning_english' => 'to receive'],
            ['hanzi' => '活', 'radical' => '氵', 'pinyin' => 'huó', 'pinyin_eng' => 'huo', 'meaning_thai' => 'มีชีวิต', 'meaning_english' => 'to live'],
            ['hanzi' => '何', 'radical' => '亻', 'pinyin' => 'hé', 'pinyin_eng' => 'he', 'meaning_thai' => 'อะไร', 'meaning_english' => 'what'],
            ['hanzi' => '伙', 'radical' => '亻', 'pinyin' => 'huǒ', 'pinyin_eng' => 'huo', 'meaning_thai' => 'พันธมิตร', 'meaning_english' => 'partner'],
            ['hanzi' => '谈', 'radical' => '讠', 'pinyin' => 'tán', 'pinyin_eng' => 'tan', 'meaning_thai' => 'พูดคุย', 'meaning_english' => 'to talk'],
            ['hanzi' => '部', 'radical' => '邑', 'pinyin' => 'bù', 'pinyin_eng' => 'bu', 'meaning_thai' => 'ส่วน', 'meaning_english' => 'part'],
            ['hanzi' => '计', 'radical' => '讠', 'pinyin' => 'jì', 'pinyin_eng' => 'ji', 'meaning_thai' => 'วางแผน', 'meaning_english' => 'to plan'],
            ['hanzi' => '任', 'radical' => '亻', 'pinyin' => 'rèn', 'pinyin_eng' => 'ren', 'meaning_thai' => 'แต่งตั้ง', 'meaning_english' => 'to appoint'],
            ['hanzi' => '确', 'radical' => '石', 'pinyin' => 'què', 'pinyin_eng' => 'que', 'meaning_thai' => 'แน่นอน', 'meaning_english' => 'certain'],
            ['hanzi' => '利', 'radical' => '禾', 'pinyin' => 'lì', 'pinyin_eng' => 'li', 'meaning_thai' => 'กำไร', 'meaning_english' => 'profit'],
            ['hanzi' => '警', 'radical' => '言', 'pinyin' => 'jǐng', 'pinyin_eng' => 'jing', 'meaning_thai' => 'แจ้งเตือน', 'meaning_english' => 'to alert'],
            ['hanzi' => '士', 'radical' => '士', 'pinyin' => 'shì', 'pinyin_eng' => 'shi', 'meaning_thai' => 'ทหาร', 'meaning_english' => 'soldier'],
            ['hanzi' => '拉', 'radical' => '扌', 'pinyin' => 'lā', 'pinyin_eng' => 'la', 'meaning_thai' => 'ดึง', 'meaning_english' => 'to pull'],
            ['hanzi' => '将', 'radical' => '寸', 'pinyin' => 'jiāng', 'pinyin_eng' => 'jiang', 'meaning_thai' => 'จะ', 'meaning_english' => 'will'],
            ['hanzi' => '证', 'radical' => '讠', 'pinyin' => 'zhèng', 'pinyin_eng' => 'zheng', 'meaning_thai' => 'พิสูจน์', 'meaning_english' => 'to prove'],
            ['hanzi' => '管', 'radical' => '竹', 'pinyin' => 'guǎn', 'pinyin_eng' => 'guan', 'meaning_thai' => 'จัดการ', 'meaning_english' => 'to manage'],
            ['hanzi' => '处', 'radical' => '夂', 'pinyin' => 'chù', 'pinyin_eng' => 'chu', 'meaning_thai' => 'สถานที่', 'meaning_english' => 'place'],
            ['hanzi' => '切', 'radical' => '刀', 'pinyin' => 'qiē', 'pinyin_eng' => 'qie', 'meaning_thai' => 'ตัด', 'meaning_english' => 'to cut'],
            ['hanzi' => '失', 'radical' => '失', 'pinyin' => 'shī', 'pinyin_eng' => 'shi', 'meaning_thai' => 'สูญเสีย', 'meaning_english' => 'to lose'],
            ['hanzi' => '性', 'radical' => '忄', 'pinyin' => 'xìng', 'pinyin_eng' => 'xing', 'meaning_thai' => 'ธรรมชาติ', 'meaning_english' => 'nature'],
            ['hanzi' => '此', 'radical' => '止', 'pinyin' => 'cǐ', 'pinyin_eng' => 'ci', 'meaning_thai' => 'นี้', 'meaning_english' => 'this'],
            ['hanzi' => '合', 'radical' => '口', 'pinyin' => 'hé', 'pinyin_eng' => 'he', 'meaning_thai' => 'รวมกัน', 'meaning_english' => 'to combine'],
            ['hanzi' => '队', 'radical' => '阝', 'pinyin' => 'duì', 'pinyin_eng' => 'dui', 'meaning_thai' => 'ทีม', 'meaning_english' => 'team'],
            ['hanzi' => '抱', 'radical' => '扌', 'pinyin' => 'bào', 'pinyin_eng' => 'bao', 'meaning_thai' => 'กอด', 'meaning_english' => 'to hold'],
            ['hanzi' => '通', 'radical' => '辶', 'pinyin' => 'tōng', 'pinyin_eng' => 'tong', 'meaning_thai' => 'สื่อสาร', 'meaning_english' => 'to communicate'],
            ['hanzi' => '并', 'radical' => '并', 'pinyin' => 'bìng', 'pinyin_eng' => 'bing', 'meaning_thai' => 'และ', 'meaning_english' => 'and'],
            ['hanzi' => '歉', 'radical' => '欠', 'pinyin' => 'qiàn', 'pinyin_eng' => 'qian', 'meaning_thai' => 'ขอโทษ', 'meaning_english' => 'apology'],
            ['hanzi' => '命', 'radical' => '口', 'pinyin' => 'mìng', 'pinyin_eng' => 'ming', 'meaning_thai' => 'ชีวิต', 'meaning_english' => 'life'],
            ['hanzi' => '入', 'radical' => '入', 'pinyin' => 'rù', 'pinyin_eng' => 'ru', 'meaning_thai' => 'เข้าไป', 'meaning_english' => 'to enter'],
            ['hanzi' => '掉', 'radical' => '扌', 'pinyin' => 'diào', 'pinyin_eng' => 'diao', 'meaning_thai' => 'หล่น', 'meaning_english' => 'to drop'],
            ['hanzi' => '演', 'radical' => '氵', 'pinyin' => 'yǎn', 'pinyin_eng' => 'yan', 'meaning_thai' => 'แสดง', 'meaning_english' => 'to perform'],
            ['hanzi' => '够', 'radical' => '多', 'pinyin' => 'gòu', 'pinyin_eng' => 'gou', 'meaning_thai' => 'เพียงพอ', 'meaning_english' => 'enough'],
            ['hanzi' => '案', 'radical' => '木', 'pinyin' => 'àn', 'pinyin_eng' => 'an', 'meaning_thai' => 'กรณี', 'meaning_english' => 'case'],
            ['hanzi' => '约', 'radical' => '纟', 'pinyin' => 'yuē', 'pinyin_eng' => 'yue', 'meaning_thai' => 'นัดหมาย', 'meaning_english' => 'to make an appointment'],
            ['hanzi' => '肯', 'radical' => '月', 'pinyin' => 'kěn', 'pinyin_eng' => 'ken', 'meaning_thai' => 'ยินดี', 'meaning_english' => 'willing'],
            ['hanzi' => '伤', 'radical' => '亻', 'pinyin' => 'shāng', 'pinyin_eng' => 'shang', 'meaning_thai' => 'เจ็บ', 'meaning_english' => 'to hurt'],
            ['hanzi' => '父', 'radical' => '父', 'pinyin' => 'fù', 'pinyin_eng' => 'fu', 'meaning_thai' => 'พ่อ', 'meaning_english' => 'father'],
            ['hanzi' => '指', 'radical' => '扌', 'pinyin' => 'zhǐ', 'pinyin_eng' => 'zhi', 'meaning_thai' => 'ชี้', 'meaning_english' => 'to point'],
            ['hanzi' => '原', 'radical' => '厂', 'pinyin' => 'yuán', 'pinyin_eng' => 'yuan', 'meaning_thai' => 'ดั้งเดิม', 'meaning_english' => 'original'],
            ['hanzi' => '底', 'radical' => '广', 'pinyin' => 'dǐ', 'pinyin_eng' => 'di', 'meaning_thai' => 'ก้น', 'meaning_english' => 'bottom'],
            ['hanzi' => '棒', 'radical' => '木', 'pinyin' => 'bàng', 'pinyin_eng' => 'bang', 'meaning_thai' => 'ไม้', 'meaning_english' => 'stick'],
            ['hanzi' => '收', 'radical' => '攵', 'pinyin' => 'shōu', 'pinyin_eng' => 'shou', 'meaning_thai' => 'รับ', 'meaning_english' => 'to receive'],
            ['hanzi' => '交', 'radical' => '亠', 'pinyin' => 'jiāo', 'pinyin_eng' => 'jiao', 'meaning_thai' => 'ส่งมอบ', 'meaning_english' => 'to hand over'],
            ['hanzi' => '停', 'radical' => '亻', 'pinyin' => 'tíng', 'pinyin_eng' => 'ting', 'meaning_thai' => 'หยุด', 'meaning_english' => 'to stop'],
            ['hanzi' => '格', 'radical' => '木', 'pinyin' => 'gé', 'pinyin_eng' => 'ge', 'meaning_thai' => 'มาตรฐาน', 'meaning_english' => 'standard'],
            ['hanzi' => '金', 'radical' => '金', 'pinyin' => 'jīn', 'pinyin_eng' => 'jin', 'meaning_thai' => 'ทองคำ', 'meaning_english' => 'gold'],
            ['hanzi' => '内', 'radical' => '冂', 'pinyin' => 'nèi', 'pinyin_eng' => 'nei', 'meaning_thai' => 'ภายใน', 'meaning_english' => 'inside'],
            ['hanzi' => '至', 'radical' => '至', 'pinyin' => 'zhì', 'pinyin_eng' => 'zhi', 'meaning_thai' => 'ถึง', 'meaning_english' => 'to'],
            ['hanzi' => '消', 'radical' => '氵', 'pinyin' => 'xiāo', 'pinyin_eng' => 'xiao', 'meaning_thai' => 'หายไป', 'meaning_english' => 'to disappear'],
            ['hanzi' => '整', 'radical' => '攵', 'pinyin' => 'zhěng', 'pinyin_eng' => 'zheng', 'meaning_thai' => 'จัดการ', 'meaning_english' => 'to arrange'],
            ['hanzi' => '度', 'radical' => '广', 'pinyin' => 'dù', 'pinyin_eng' => 'du', 'meaning_thai' => 'ระดับ', 'meaning_english' => 'degree'],
            ['hanzi' => '持', 'radical' => '扌', 'pinyin' => 'chí', 'pinyin_eng' => 'chi', 'meaning_thai' => 'ถือ', 'meaning_english' => 'to hold'],
            ['hanzi' => '光', 'radical' => '儿', 'pinyin' => 'guāng', 'pinyin_eng' => 'guang', 'meaning_thai' => 'แสงสว่าง', 'meaning_english' => 'light'],
            ['hanzi' => '与', 'radical' => '一', 'pinyin' => 'yǔ', 'pinyin_eng' => 'yu', 'meaning_thai' => 'และ', 'meaning_english' => 'and'],
            ['hanzi' => '象', 'radical' => '豕', 'pinyin' => 'xiàng', 'pinyin_eng' => 'xiang', 'meaning_thai' => 'ช้าง', 'meaning_english' => 'elephant'],
            ['hanzi' => '使', 'radical' => '亻', 'pinyin' => 'shǐ', 'pinyin_eng' => 'shi', 'meaning_thai' => 'ทำให้', 'meaning_english' => 'to make'],
            ['hanzi' => '察', 'radical' => '宀', 'pinyin' => 'chá', 'pinyin_eng' => 'cha', 'meaning_thai' => 'ตรวจสอบ', 'meaning_english' => 'to inspect'],
            ['hanzi' => '海', 'radical' => '氵', 'pinyin' => 'hǎi', 'pinyin_eng' => 'hai', 'meaning_thai' => 'ทะเล', 'meaning_english' => 'sea'],
            ['hanzi' => '绝', 'radical' => '纟', 'pinyin' => 'jué', 'pinyin_eng' => 'jue', 'meaning_thai' => 'หยุด', 'meaning_english' => 'to break off'],
            ['hanzi' => '反', 'radical' => '又', 'pinyin' => 'fǎn', 'pinyin_eng' => 'fan', 'meaning_thai' => 'ตรงข้าม', 'meaning_english' => 'opposite'],
            ['hanzi' => '由', 'radical' => '田', 'pinyin' => 'yóu', 'pinyin_eng' => 'you', 'meaning_thai' => 'จาก', 'meaning_english' => 'from'],
            ['hanzi' => '论', 'radical' => '讠', 'pinyin' => 'lùn', 'pinyin_eng' => 'lun', 'meaning_thai' => 'สนทนา', 'meaning_english' => 'to discuss'],
            ['hanzi' => '亚', 'radical' => '一', 'pinyin' => 'yà', 'pinyin_eng' => 'ya', 'meaning_thai' => 'เอเชีย', 'meaning_english' => 'Asia'],
            ['hanzi' => '续', 'radical' => '纟', 'pinyin' => 'xù', 'pinyin_eng' => 'xu', 'meaning_thai' => 'ต่อเนื่อง', 'meaning_english' => 'to continue'],
            ['hanzi' => '母', 'radical' => '母', 'pinyin' => 'mǔ', 'pinyin_eng' => 'mu', 'meaning_thai' => 'แม่', 'meaning_english' => 'mother'],
            ['hanzi' => '尽', 'radical' => '尸', 'pinyin' => 'jǐn', 'pinyin_eng' => 'jin', 'meaning_thai' => 'หมดแรง', 'meaning_english' => 'to exhaust'],
            ['hanzi' => '弄', 'radical' => '廾', 'pinyin' => 'nòng', 'pinyin_eng' => 'nong', 'meaning_thai' => 'ทำ', 'meaning_english' => 'to do'],
            ['hanzi' => '密', 'radical' => '宀', 'pinyin' => 'mì', 'pinyin_eng' => 'mi', 'meaning_thai' => 'ความลับ', 'meaning_english' => 'secret'],
            ['hanzi' => '线', 'radical' => '纟', 'pinyin' => 'xiàn', 'pinyin_eng' => 'xian', 'meaning_thai' => 'เส้น', 'meaning_english' => 'line'],
            ['hanzi' => '继', 'radical' => '纟', 'pinyin' => 'jì', 'pinyin_eng' => 'ji', 'meaning_thai' => 'รับมรดก', 'meaning_english' => 'to inherit'],
            ['hanzi' => '份', 'radical' => '亻', 'pinyin' => 'fèn', 'pinyin_eng' => 'fen', 'meaning_thai' => 'ส่วน', 'meaning_english' => 'portion'],
            ['hanzi' => '止', 'radical' => '止', 'pinyin' => 'zhǐ', 'pinyin_eng' => 'zhi', 'meaning_thai' => 'หยุด', 'meaning_english' => 'to stop'],
            ['hanzi' => '拜', 'radical' => '扌', 'pinyin' => 'bài', 'pinyin_eng' => 'bai', 'meaning_thai' => 'บูชา', 'meaning_english' => 'to worship'],
            ['hanzi' => '紧', 'radical' => '纟', 'pinyin' => 'jǐn', 'pinyin_eng' => 'jin', 'meaning_thai' => 'แน่น', 'meaning_english' => 'tight'],
            ['hanzi' => '联', 'radical' => '耳', 'pinyin' => 'lián', 'pinyin_eng' => 'lian', 'meaning_thai' => 'รวมกัน', 'meaning_english' => 'to unite'],
            ['hanzi' => '精', 'radical' => '米', 'pinyin' => 'jīng', 'pinyin_eng' => 'jing', 'meaning_thai' => 'แก่นสาร', 'meaning_english' => 'essence'],
            ['hanzi' => '转', 'radical' => '车', 'pinyin' => 'zhuǎn', 'pinyin_eng' => 'zhuan', 'meaning_thai' => 'หมุน', 'meaning_english' => 'to turn'],
            ['hanzi' => '却', 'radical' => '去', 'pinyin' => 'què', 'pinyin_eng' => 'que', 'meaning_thai' => 'แต่', 'meaning_english' => 'but'],
            ['hanzi' => '基', 'radical' => '土', 'pinyin' => 'jī', 'pinyin_eng' => 'ji', 'meaning_thai' => 'ฐาน', 'meaning_english' => 'base'],
            ['hanzi' => '台', 'radical' => '口', 'pinyin' => 'tái', 'pinyin_eng' => 'tai', 'meaning_thai' => 'แพลตฟอร์ม', 'meaning_english' => 'platform'],
            ['hanzi' => '另', 'radical' => '口', 'pinyin' => 'lìng', 'pinyin_eng' => 'ling', 'meaning_thai' => 'อื่น ๆ', 'meaning_english' => 'other'],
            ['hanzi' => '况', 'radical' => '冫', 'pinyin' => 'kuàng', 'pinyin_eng' => 'kuang', 'meaning_thai' => 'สถานการณ์', 'meaning_english' => 'situation'],
            ['hanzi' => '否', 'radical' => '口', 'pinyin' => 'fǒu', 'pinyin_eng' => 'fou', 'meaning_thai' => 'ไม่', 'meaning_english' => 'not'],
            ['hanzi' => '险', 'radical' => '阝', 'pinyin' => 'xiǎn', 'pinyin_eng' => 'xian', 'meaning_thai' => 'อันตราย', 'meaning_english' => 'danger'],
            ['hanzi' => '言', 'radical' => '言', 'pinyin' => 'yán', 'pinyin_eng' => 'yan', 'meaning_thai' => 'คำ', 'meaning_english' => 'word'],
            ['hanzi' => '幸', 'radical' => '幸', 'pinyin' => 'xìng', 'pinyin_eng' => 'xing', 'meaning_thai' => 'โชคดี', 'meaning_english' => 'lucky'],
            ['hanzi' => '传', 'radical' => '亻', 'pinyin' => 'chuán', 'pinyin_eng' => 'chuan', 'meaning_thai' => 'ถ่ายทอด', 'meaning_english' => 'to transmit'],
            ['hanzi' => '量', 'radical' => '里', 'pinyin' => 'liàng', 'pinyin_eng' => 'liang', 'meaning_thai' => 'ปริมาณ', 'meaning_english' => 'amount'],
            ['hanzi' => '首', 'radical' => '首', 'pinyin' => 'shǒu', 'pinyin_eng' => 'shou', 'meaning_thai' => 'หัว', 'meaning_english' => 'head'],
            ['hanzi' => '改', 'radical' => '攵', 'pinyin' => 'gǎi', 'pinyin_eng' => 'gai', 'meaning_thai' => 'เปลี่ยน', 'meaning_english' => 'to change'],
            ['hanzi' => '术', 'radical' => '木', 'pinyin' => 'shù', 'pinyin_eng' => 'shu', 'meaning_thai' => 'เทคนิค', 'meaning_english' => 'technique'],
            ['hanzi' => '局', 'radical' => '尸', 'pinyin' => 'jú', 'pinyin_eng' => 'ju', 'meaning_thai' => 'สำนักงาน', 'meaning_english' => 'bureau'],
            ['hanzi' => '永', 'radical' => '水', 'pinyin' => 'yǒng', 'pinyin_eng' => 'yong', 'meaning_thai' => 'ตลอดกาล', 'meaning_english' => 'forever'],
            ['hanzi' => '烦', 'radical' => '火', 'pinyin' => 'fán', 'pinyin_eng' => 'fan', 'meaning_thai' => 'รำคาญ', 'meaning_english' => 'annoyed'],
            ['hanzi' => '取', 'radical' => '又', 'pinyin' => 'qǔ', 'pinyin_eng' => 'qu', 'meaning_thai' => 'เอา', 'meaning_english' => 'to take'],
            ['hanzi' => '随', 'radical' => '阝', 'pinyin' => 'suí', 'pinyin_eng' => 'sui', 'meaning_thai' => 'ตาม', 'meaning_english' => 'to follow'],
            ['hanzi' => '式', 'radical' => '弋', 'pinyin' => 'shì', 'pinyin_eng' => 'shi', 'meaning_thai' => 'รูปแบบ', 'meaning_english' => 'style'],
            ['hanzi' => '律', 'radical' => '彳', 'pinyin' => 'lǜ', 'pinyin_eng' => 'lu', 'meaning_thai' => 'กฎหมาย', 'meaning_english' => 'law'],
            ['hanzi' => '费', 'radical' => '贝', 'pinyin' => 'fèi', 'pinyin_eng' => 'fei', 'meaning_thai' => 'ค่าธรรมเนียม', 'meaning_english' => 'fee'],
            ['hanzi' => '科', 'radical' => '禾', 'pinyin' => 'kē', 'pinyin_eng' => 'ke', 'meaning_thai' => 'วิชา', 'meaning_english' => 'subject'],
            ['hanzi' => '麻', 'radical' => '麻', 'pinyin' => 'má', 'pinyin_eng' => 'ma', 'meaning_thai' => 'ชา', 'meaning_english' => 'numb'],
            ['hanzi' => '流', 'radical' => '氵', 'pinyin' => 'liú', 'pinyin_eng' => 'liu', 'meaning_thai' => 'ไหล', 'meaning_english' => 'to flow'],
            ['hanzi' => '倒', 'radical' => '亻', 'pinyin' => 'dǎo', 'pinyin_eng' => 'dao', 'meaning_thai' => 'ล้ม', 'meaning_english' => 'to fall'],
            ['hanzi' => '划', 'radical' => '刂', 'pinyin' => 'huà', 'pinyin_eng' => 'hua', 'meaning_thai' => 'พายเรือ', 'meaning_english' => 'to row'],
            ['hanzi' => '味', 'radical' => '口', 'pinyin' => 'wèi', 'pinyin_eng' => 'wei', 'meaning_thai' => 'รสชาติ', 'meaning_english' => 'taste'],
            ['hanzi' => '区', 'radical' => '匚', 'pinyin' => 'qū', 'pinyin_eng' => 'qu', 'meaning_thai' => 'พื้นที่', 'meaning_english' => 'area'],
            ['hanzi' => '支', 'radical' => '支', 'pinyin' => 'zhī', 'pinyin_eng' => 'zhi', 'meaning_thai' => 'สนับสนุน', 'meaning_english' => 'to support'],
            ['hanzi' => '连', 'radical' => '辶', 'pinyin' => 'lián', 'pinyin_eng' => 'lian', 'meaning_thai' => 'เชื่อมต่อ', 'meaning_english' => 'to connect'],
            ['hanzi' => '弹', 'radical' => '弓', 'pinyin' => 'tán', 'pinyin_eng' => 'tan', 'meaning_thai' => 'เล่น (เครื่องดนตรี)', 'meaning_english' => 'to play (an instrument)'],
            ['hanzi' => '吸', 'radical' => '口', 'pinyin' => 'xī', 'pinyin_eng' => 'xi', 'meaning_thai' => 'สูดเข้าไป', 'meaning_english' => 'to inhale'],
            ['hanzi' => '呀', 'radical' => '口', 'pinyin' => 'yā', 'pinyin_eng' => 'ya', 'meaning_thai' => 'อ่า', 'meaning_english' => 'ah'],
            ['hanzi' => '醒', 'radical' => '酉', 'pinyin' => 'xǐng', 'pinyin_eng' => 'xing', 'meaning_thai' => 'ตื่น', 'meaning_english' => 'to wake up'],
            ['hanzi' => '梦', 'radical' => '木', 'pinyin' => 'mèng', 'pinyin_eng' => 'meng', 'meaning_thai' => 'ฝัน', 'meaning_english' => 'dream'],
            ['hanzi' => '赢', 'radical' => '贝', 'pinyin' => 'yíng', 'pinyin_eng' => 'ying', 'meaning_thai' => 'ชนะ', 'meaning_english' => 'to win'],
            ['hanzi' => '丽', 'radical' => '一', 'pinyin' => 'lì', 'pinyin_eng' => 'li', 'meaning_thai' => 'สวยงาม', 'meaning_english' => 'beautiful'],
            ['hanzi' => '付', 'radical' => '亻', 'pinyin' => 'fù', 'pinyin_eng' => 'fu', 'meaning_thai' => 'จ่าย', 'meaning_english' => 'to pay'],
            ['hanzi' => '排', 'radical' => '扌', 'pinyin' => 'pái', 'pinyin_eng' => 'pai', 'meaning_thai' => 'จัดการ', 'meaning_english' => 'to arrange'],
            ['hanzi' => '敢', 'radical' => '攵', 'pinyin' => 'gǎn', 'pinyin_eng' => 'gan', 'meaning_thai' => 'กล้า', 'meaning_english' => 'to dare'],
            ['hanzi' => '油', 'radical' => '氵', 'pinyin' => 'yóu', 'pinyin_eng' => 'you', 'meaning_thai' => 'น้ำมัน', 'meaning_english' => 'oil'],
            ['hanzi' => '餐', 'radical' => '食', 'pinyin' => 'cān', 'pinyin_eng' => 'can', 'meaning_thai' => 'มื้ออาหาร', 'meaning_english' => 'meal'],
            ['hanzi' => '破', 'radical' => '石', 'pinyin' => 'pò', 'pinyin_eng' => 'po', 'meaning_thai' => 'ทำลาย', 'meaning_english' => 'to break'],
            ['hanzi' => '激', 'radical' => '氵', 'pinyin' => 'jī', 'pinyin_eng' => 'ji', 'meaning_thai' => 'ทำให้ตื่นเต้น', 'meaning_english' => 'to excite'],
            ['hanzi' => '程', 'radical' => '禾', 'pinyin' => 'chéng', 'pinyin_eng' => 'cheng', 'meaning_thai' => 'กระบวนการ', 'meaning_english' => 'process'],
            ['hanzi' => '讨', 'radical' => '讠', 'pinyin' => 'tǎo', 'pinyin_eng' => 'tao', 'meaning_thai' => 'สนทนา', 'meaning_english' => 'to discuss'],
            ['hanzi' => '责', 'radical' => '贝', 'pinyin' => 'zé', 'pinyin_eng' => 'ze', 'meaning_thai' => 'หน้าที่', 'meaning_english' => 'duty'],
            ['hanzi' => '落', 'radical' => '艹', 'pinyin' => 'luò', 'pinyin_eng' => 'luo', 'meaning_thai' => 'ตก', 'meaning_english' => 'to fall'],
            ['hanzi' => '林', 'radical' => '木', 'pinyin' => 'lín', 'pinyin_eng' => 'lin', 'meaning_thai' => 'ป่า', 'meaning_english' => 'forest'],
            ['hanzi' => '及', 'radical' => '又', 'pinyin' => 'jí', 'pinyin_eng' => 'ji', 'meaning_thai' => 'และ', 'meaning_english' => 'and'],
            ['hanzi' => '争', 'radical' => '亠', 'pinyin' => 'zhēng', 'pinyin_eng' => 'zheng', 'meaning_thai' => 'ต่อสู้', 'meaning_english' => 'to fight'],
            ['hanzi' => '猜', 'radical' => '犭', 'pinyin' => 'cāi', 'pinyin_eng' => 'cai', 'meaning_thai' => 'เดา', 'meaning_english' => 'to guess'],
            ['hanzi' => '建', 'radical' => '廴', 'pinyin' => 'jiàn', 'pinyin_eng' => 'jian', 'meaning_thai' => 'สร้าง', 'meaning_english' => 'to build'],
            ['hanzi' => '惊', 'radical' => '忄', 'pinyin' => 'jīng', 'pinyin_eng' => 'jing', 'meaning_thai' => 'ทำให้ประหลาดใจ', 'meaning_english' => 'to surprise'],
            ['hanzi' => '标', 'radical' => '木', 'pinyin' => 'biāo', 'pinyin_eng' => 'biao', 'meaning_thai' => 'เครื่องหมาย', 'meaning_english' => 'mark'],
            ['hanzi' => '各', 'radical' => '口', 'pinyin' => 'gè', 'pinyin_eng' => 'ge', 'meaning_thai' => 'แต่ละ', 'meaning_english' => 'each'],
            ['hanzi' => '民', 'radical' => '氏', 'pinyin' => 'mín', 'pinyin_eng' => 'min', 'meaning_thai' => 'ประชาชน', 'meaning_english' => 'people'],
            ['hanzi' => '功', 'radical' => '力', 'pinyin' => 'gōng', 'pinyin_eng' => 'gong', 'meaning_thai' => 'ความสำเร็จ', 'meaning_english' => 'achievement'],
            ['hanzi' => '示', 'radical' => '示', 'pinyin' => 'shì', 'pinyin_eng' => 'shi', 'meaning_thai' => 'แสดง', 'meaning_english' => 'to show'],
            ['hanzi' => '释', 'radical' => '釆', 'pinyin' => 'shì', 'pinyin_eng' => 'shi', 'meaning_thai' => 'ปล่อย', 'meaning_english' => 'to release'],
            ['hanzi' => '引', 'radical' => '弓', 'pinyin' => 'yǐn', 'pinyin_eng' => 'yin', 'meaning_thai' => 'นำ', 'meaning_english' => 'to lead'],
            ['hanzi' => '疑', 'radical' => '疋', 'pinyin' => 'yí', 'pinyin_eng' => 'yi', 'meaning_thai' => 'สงสัย', 'meaning_english' => 'to doubt'],
            ['hanzi' => '赶', 'radical' => '走', 'pinyin' => 'gǎn', 'pinyin_eng' => 'gan', 'meaning_thai' => 'เร่ง', 'meaning_english' => 'to hurry'],
            ['hanzi' => '俩', 'radical' => '亻', 'pinyin' => 'liǎ', 'pinyin_eng' => 'lia', 'meaning_thai' => 'สอง (ภาษาพูด)', 'meaning_english' => 'two (colloquial)'],
            ['hanzi' => '存', 'radical' => '子', 'pinyin' => 'cún', 'pinyin_eng' => 'cun', 'meaning_thai' => 'มีอยู่', 'meaning_english' => 'to exist'],
            ['hanzi' => '断', 'radical' => '斤', 'pinyin' => 'duàn', 'pinyin_eng' => 'duan', 'meaning_thai' => 'ทำลาย', 'meaning_english' => 'to break'],
            ['hanzi' => '松', 'radical' => '木', 'pinyin' => 'sōng', 'pinyin_eng' => 'song', 'meaning_thai' => 'หลวม', 'meaning_english' => 'loose'],
            ['hanzi' => '博', 'radical' => '十', 'pinyin' => 'bó', 'pinyin_eng' => 'bo', 'meaning_thai' => 'มากมาย', 'meaning_english' => 'abundant'],
            ['hanzi' => '观', 'radical' => '见', 'pinyin' => 'guān', 'pinyin_eng' => 'guan', 'meaning_thai' => 'สังเกต', 'meaning_english' => 'to observe'],
            ['hanzi' => '码', 'radical' => '石', 'pinyin' => 'mǎ', 'pinyin_eng' => 'ma', 'meaning_thai' => 'รหัส', 'meaning_english' => 'code'],
            ['hanzi' => '恐', 'radical' => '心', 'pinyin' => 'kǒng', 'pinyin_eng' => 'kong', 'meaning_thai' => 'ความกลัว', 'meaning_english' => 'fear'],
            ['hanzi' => '普', 'radical' => '日', 'pinyin' => 'pǔ', 'pinyin_eng' => 'pu', 'meaning_thai' => 'ทั่วไป', 'meaning_english' => 'general'],
            ['hanzi' => '价', 'radical' => '亻', 'pinyin' => 'jià', 'pinyin_eng' => 'jia', 'meaning_thai' => 'ราคา', 'meaning_english' => 'price'],
            ['hanzi' => '怀', 'radical' => '忄', 'pinyin' => 'huái', 'pinyin_eng' => 'huai', 'meaning_thai' => 'รัก', 'meaning_english' => 'to cherish'],
            ['hanzi' => '验', 'radical' => '马', 'pinyin' => 'yàn', 'pinyin_eng' => 'yan', 'meaning_thai' => 'ตรวจสอบ', 'meaning_english' => 'to examine'],
            ['hanzi' => '呼', 'radical' => '口', 'pinyin' => 'hū', 'pinyin_eng' => 'hu', 'meaning_thai' => 'เรียก', 'meaning_english' => 'to call'],
            ['hanzi' => '祝', 'radical' => '礻', 'pinyin' => 'zhù', 'pinyin_eng' => 'zhu', 'meaning_thai' => 'อวยพร', 'meaning_english' => 'to wish'],
            ['hanzi' => '剧', 'radical' => '刂', 'pinyin' => 'jù', 'pinyin_eng' => 'ju', 'meaning_thai' => 'ละคร', 'meaning_english' => 'drama'],
            ['hanzi' => '乱', 'radical' => '乙', 'pinyin' => 'luàn', 'pinyin_eng' => 'luan', 'meaning_thai' => 'ความวุ่นวาย', 'meaning_english' => 'chaos'],
            ['hanzi' => '展', 'radical' => '尸', 'pinyin' => 'zhǎn', 'pinyin_eng' => 'zhan', 'meaning_thai' => 'แสดง', 'meaning_english' => 'to exhibit'],
            ['hanzi' => '则', 'radical' => '刂', 'pinyin' => 'zé', 'pinyin_eng' => 'ze', 'meaning_thai' => 'กฎ', 'meaning_english' => 'rule'],
            ['hanzi' => '深', 'radical' => '氵', 'pinyin' => 'shēn', 'pinyin_eng' => 'shen', 'meaning_thai' => 'ลึก', 'meaning_english' => 'deep'],
            ['hanzi' => '迷', 'radical' => '辶', 'pinyin' => 'mí', 'pinyin_eng' => 'mi', 'meaning_thai' => 'หลงทาง', 'meaning_english' => 'lost'],
            ['hanzi' => '具', 'radical' => '目', 'pinyin' => 'jù', 'pinyin_eng' => 'ju', 'meaning_thai' => 'เครื่องมือ', 'meaning_english' => 'tool'],
            ['hanzi' => '福', 'radical' => '礻', 'pinyin' => 'fú', 'pinyin_eng' => 'fu', 'meaning_thai' => 'พร', 'meaning_english' => 'blessing'],
            ['hanzi' => '职', 'radical' => '耳', 'pinyin' => 'zhí', 'pinyin_eng' => 'zhi', 'meaning_thai' => 'งาน', 'meaning_english' => 'job'],
            ['hanzi' => '即', 'radical' => '卩', 'pinyin' => 'jí', 'pinyin_eng' => 'ji', 'meaning_thai' => 'กล่าวคือ', 'meaning_english' => 'namely'],
            ['hanzi' => '挺', 'radical' => '扌', 'pinyin' => 'tǐng', 'pinyin_eng' => 'ting', 'meaning_thai' => 'มาก', 'meaning_english' => 'very'],
            ['hanzi' => '负', 'radical' => '贝', 'pinyin' => 'fù', 'pinyin_eng' => 'fu', 'meaning_thai' => 'แบก', 'meaning_english' => 'to bear'],
            ['hanzi' => '脱', 'radical' => '月', 'pinyin' => 'tuō', 'pinyin_eng' => 'tuo', 'meaning_thai' => 'ถอด', 'meaning_english' => 'to take off'],
            ['hanzi' => '仅', 'radical' => '亻', 'pinyin' => 'jǐn', 'pinyin_eng' => 'jin', 'meaning_thai' => 'เท่านั้น', 'meaning_english' => 'only'],
            ['hanzi' => '资', 'radical' => '贝', 'pinyin' => 'zī', 'pinyin_eng' => 'zi', 'meaning_thai' => 'ทรัพยากร', 'meaning_english' => 'resource'],
            ['hanzi' => '弃', 'radical' => '弓', 'pinyin' => 'qì', 'pinyin_eng' => 'qi', 'meaning_thai' => 'ทิ้ง', 'meaning_english' => 'to abandon'],
            ['hanzi' => '修', 'radical' => '亻', 'pinyin' => 'xiū', 'pinyin_eng' => 'xiu', 'meaning_thai' => 'ซ่อมแซม', 'meaning_english' => 'to repair'],
            ['hanzi' => '危', 'radical' => '厂', 'pinyin' => 'wēi', 'pinyin_eng' => 'wei', 'meaning_thai' => 'อันตราย', 'meaning_english' => 'danger'],
            ['hanzi' => '专', 'radical' => '寸', 'pinyin' => 'zhuān', 'pinyin_eng' => 'zhuan', 'meaning_thai' => 'เฉพาะทาง', 'meaning_english' => 'specialized'],
            ['hanzi' => '甚', 'radical' => '甘', 'pinyin' => 'shén', 'pinyin_eng' => 'shen', 'meaning_thai' => 'อะไร', 'meaning_english' => 'what'],
            ['hanzi' => '苦', 'radical' => '艹', 'pinyin' => 'kǔ', 'pinyin_eng' => 'ku', 'meaning_thai' => 'ขม', 'meaning_english' => 'bitter'],
            ['hanzi' => '适', 'radical' => '辶', 'pinyin' => 'shì', 'pinyin_eng' => 'shi', 'meaning_thai' => 'เหมาะสม', 'meaning_english' => 'suitable'],
            ['hanzi' => '骗', 'radical' => '马', 'pinyin' => 'piàn', 'pinyin_eng' => 'pian', 'meaning_thai' => 'หลอกลวง', 'meaning_english' => 'to deceive'],
            ['hanzi' => '厌', 'radical' => '厂', 'pinyin' => 'yàn', 'pinyin_eng' => 'yan', 'meaning_thai' => 'เกลียด', 'meaning_english' => 'to detest'],
            ['hanzi' => '值', 'radical' => '亻', 'pinyin' => 'zhí', 'pinyin_eng' => 'zhi', 'meaning_thai' => 'ค่า', 'meaning_english' => 'value'],
            ['hanzi' => '众', 'radical' => '人', 'pinyin' => 'zhòng', 'pinyin_eng' => 'zhong', 'meaning_thai' => 'ฝูงชน', 'meaning_english' => 'crowd'],
            ['hanzi' => '预', 'radical' => '讠', 'pinyin' => 'yù', 'pinyin_eng' => 'yu', 'meaning_thai' => 'คาดการณ์', 'meaning_english' => 'to anticipate'],
            ['hanzi' => '际', 'radical' => '阝', 'pinyin' => 'jì', 'pinyin_eng' => 'ji', 'meaning_thai' => 'ชายแดน', 'meaning_english' => 'border'],
            ['hanzi' => '咱', 'radical' => '口', 'pinyin' => 'zán', 'pinyin_eng' => 'zan', 'meaning_thai' => 'เรา', 'meaning_english' => 'we'],
            ['hanzi' => '卫', 'radical' => '卩', 'pinyin' => 'wèi', 'pinyin_eng' => 'wei', 'meaning_thai' => 'เฝ้า', 'meaning_english' => 'to guard'],
            ['hanzi' => '养', 'radical' => '攵', 'pinyin' => 'yǎng', 'pinyin_eng' => 'yang', 'meaning_thai' => 'เลี้ยง', 'meaning_english' => 'to raise'],
            ['hanzi' => '导', 'radical' => '寸', 'pinyin' => 'dǎo', 'pinyin_eng' => 'dao', 'meaning_thai' => 'แนะนำ', 'meaning_english' => 'to guide'],
            ['hanzi' => '虑', 'radical' => '虍', 'pinyin' => 'lǜ', 'pinyin_eng' => 'lu', 'meaning_thai' => 'พิจารณา', 'meaning_english' => 'to consider'],
            ['hanzi' => '戴', 'radical' => '戈', 'pinyin' => 'dài', 'pinyin_eng' => 'dai', 'meaning_thai' => 'สวมใส่', 'meaning_english' => 'to wear'],
            ['hanzi' => '志', 'radical' => '心', 'pinyin' => 'zhì', 'pinyin_eng' => 'zhi', 'meaning_thai' => 'ความใฝ่ฝัน', 'meaning_english' => 'aspiration'],
            ['hanzi' => '杂', 'radical' => '木', 'pinyin' => 'zá', 'pinyin_eng' => 'za', 'meaning_thai' => 'เบ็ดเตล็ด', 'meaning_english' => 'miscellaneous'],
            ['hanzi' => '误', 'radical' => '讠', 'pinyin' => 'wù', 'pinyin_eng' => 'wu', 'meaning_thai' => 'ความผิดพลาด', 'meaning_english' => 'mistake'],
            ['hanzi' => '规', 'radical' => '见', 'pinyin' => 'guī', 'pinyin_eng' => 'gui', 'meaning_thai' => 'กฎ', 'meaning_english' => 'rule'],
            ['hanzi' => '陪', 'radical' => '阝', 'pinyin' => 'péi', 'pinyin_eng' => 'pei', 'meaning_thai' => 'ไปด้วย', 'meaning_english' => 'to accompany'],
            ['hanzi' => '森', 'radical' => '木', 'pinyin' => 'sēn', 'pinyin_eng' => 'sen', 'meaning_thai' => 'ป่า', 'meaning_english' => 'forest'],
            ['hanzi' => '纪', 'radical' => '纟', 'pinyin' => 'jì', 'pinyin_eng' => 'ji', 'meaning_thai' => 'บันทึก', 'meaning_english' => 'record'],
            ['hanzi' => '浪', 'radical' => '氵', 'pinyin' => 'làng', 'pinyin_eng' => 'lang', 'meaning_thai' => 'คลื่น', 'meaning_english' => 'wave'],
            ['hanzi' => '顺', 'radical' => '页', 'pinyin' => 'shùn', 'pinyin_eng' => 'shun', 'meaning_thai' => 'ราบรื่น', 'meaning_english' => 'smooth'],
            ['hanzi' => '举', 'radical' => '手', 'pinyin' => 'jǔ', 'pinyin_eng' => 'ju', 'meaning_thai' => 'ยกขึ้น', 'meaning_english' => 'to lift'],
            ['hanzi' => '按', 'radical' => '扌', 'pinyin' => 'àn', 'pinyin_eng' => 'an', 'meaning_thai' => 'กด', 'meaning_english' => 'to press'],
            ['hanzi' => '坚', 'radical' => '土', 'pinyin' => 'jiān', 'pinyin_eng' => 'jian', 'meaning_thai' => 'มั่นคง', 'meaning_english' => 'firm'],
            ['hanzi' => '免', 'radical' => '儿', 'pinyin' => 'miǎn', 'pinyin_eng' => 'mian', 'meaning_thai' => 'หลีกเลี่ยง', 'meaning_english' => 'to avoid'],
            ['hanzi' => '印', 'radical' => '卩', 'pinyin' => 'yìn', 'pinyin_eng' => 'yin', 'meaning_thai' => 'พิมพ์', 'meaning_english' => 'print'],
            ['hanzi' => '严', 'radical' => '严', 'pinyin' => 'yán', 'pinyin_eng' => 'yan', 'meaning_thai' => 'เข้มงวด', 'meaning_english' => 'strict'],
            ['hanzi' => '推', 'radical' => '扌', 'pinyin' => 'tuī', 'pinyin_eng' => 'tui', 'meaning_thai' => 'ดัน', 'meaning_english' => 'to push'],
            ['hanzi' => '毛', 'radical' => '毛', 'pinyin' => 'máo', 'pinyin_eng' => 'mao', 'meaning_thai' => 'ขน', 'meaning_english' => 'fur'],
            ['hanzi' => '压', 'radical' => '厂', 'pinyin' => 'yā', 'pinyin_eng' => 'ya', 'meaning_thai' => 'กดดัน', 'meaning_english' => 'to press'],
            ['hanzi' => '败', 'radical' => '贝', 'pinyin' => 'bài', 'pinyin_eng' => 'bai', 'meaning_thai' => 'พ่ายแพ้', 'meaning_english' => 'to defeat'],
            ['hanzi' => '究', 'radical' => '穴', 'pinyin' => 'jiū', 'pinyin_eng' => 'jiu', 'meaning_thai' => 'สืบสวน', 'meaning_english' => 'to investigate'],
            ['hanzi' => '评', 'radical' => '讠', 'pinyin' => 'píng', 'pinyin_eng' => 'ping', 'meaning_thai' => 'ประเมิน', 'meaning_english' => 'to evaluate'],
            ['hanzi' => '速', 'radical' => '辶', 'pinyin' => 'sù', 'pinyin_eng' => 'su', 'meaning_thai' => 'รวดเร็ว', 'meaning_english' => 'fast'],
            ['hanzi' => '获', 'radical' => '艹', 'pinyin' => 'huò', 'pinyin_eng' => 'huo', 'meaning_thai' => 'ได้รับ', 'meaning_english' => 'to obtain'],
            ['hanzi' => '细', 'radical' => '纟', 'pinyin' => 'xì', 'pinyin_eng' => 'xi', 'meaning_thai' => 'ละเอียด', 'meaning_english' => 'fine'],
            ['hanzi' => '丢', 'radical' => '丿', 'pinyin' => 'diū', 'pinyin_eng' => 'diu', 'meaning_thai' => 'ทำหาย', 'meaning_english' => 'to lose'],
            ['hanzi' => '态', 'radical' => '心', 'pinyin' => 'tài', 'pinyin_eng' => 'tai', 'meaning_thai' => 'สถานะ', 'meaning_english' => 'state'],
            ['hanzi' => '判', 'radical' => '刂', 'pinyin' => 'pàn', 'pinyin_eng' => 'pan', 'meaning_thai' => 'ตัดสิน', 'meaning_english' => 'to judge'],
            ['hanzi' => '货', 'radical' => '贝', 'pinyin' => 'huò', 'pinyin_eng' => 'huo', 'meaning_thai' => 'สินค้า', 'meaning_english' => 'goods'],
            ['hanzi' => '围', 'radical' => '囗', 'pinyin' => 'wéi', 'pinyin_eng' => 'wei', 'meaning_thai' => 'ล้อมรอบ', 'meaning_english' => 'to surround'],
            ['hanzi' => '签', 'radical' => '竹', 'pinyin' => 'qiān', 'pinyin_eng' => 'qian', 'meaning_thai' => 'เซ็นชื่อ', 'meaning_english' => 'to sign'],
            ['hanzi' => '牌', 'radical' => '片', 'pinyin' => 'pái', 'pinyin_eng' => 'pai', 'meaning_thai' => 'ยี่ห้อ', 'meaning_english' => 'brand'],
            ['hanzi' => '户', 'radical' => '户', 'pinyin' => 'hù', 'pinyin_eng' => 'hu', 'meaning_thai' => 'ครัวเรือน', 'meaning_english' => 'household'],
            ['hanzi' => '质', 'radical' => '贝', 'pinyin' => 'zhì', 'pinyin_eng' => 'zhi', 'meaning_thai' => 'คุณภาพ', 'meaning_english' => 'quality'],
            ['hanzi' => '供', 'radical' => '亻', 'pinyin' => 'gōng', 'pinyin_eng' => 'gong', 'meaning_thai' => 'จัดหา', 'meaning_english' => 'to provide'],
            ['hanzi' => '奖', 'radical' => '大', 'pinyin' => 'jiǎng', 'pinyin_eng' => 'jiang', 'meaning_thai' => 'รางวัล', 'meaning_english' => 'prize'],
            ['hanzi' => '袋', 'radical' => '衤', 'pinyin' => 'dài', 'pinyin_eng' => 'dai', 'meaning_thai' => 'กระเป๋า', 'meaning_english' => 'bag'],
            ['hanzi' => '脏', 'radical' => '月', 'pinyin' => 'zāng', 'pinyin_eng' => 'zang', 'meaning_thai' => 'สกปรก', 'meaning_english' => 'dirty'],
            ['hanzi' => '效', 'radical' => '攵', 'pinyin' => 'xiào', 'pinyin_eng' => 'xiao', 'meaning_thai' => 'ผลกระทบ', 'meaning_english' => 'effect'],
            ['hanzi' => '座', 'radical' => '广', 'pinyin' => 'zuò', 'pinyin_eng' => 'zuo', 'meaning_thai' => 'ที่นั่ง', 'meaning_english' => 'seat'],
            ['hanzi' => '沙', 'radical' => '氵', 'pinyin' => 'shā', 'pinyin_eng' => 'sha', 'meaning_thai' => 'ทราย', 'meaning_english' => 'sand'],
            ['hanzi' => '扰', 'radical' => '扌', 'pinyin' => 'rǎo', 'pinyin_eng' => 'rao', 'meaning_thai' => 'รบกวน', 'meaning_english' => 'to disturb'],
            ['hanzi' => '困', 'radical' => '囗', 'pinyin' => 'kùn', 'pinyin_eng' => 'kun', 'meaning_thai' => 'ติดอยู่', 'meaning_english' => 'to be trapped'],
            ['hanzi' => '概', 'radical' => '木', 'pinyin' => 'gài', 'pinyin_eng' => 'gai', 'meaning_thai' => 'ทั่วไป', 'meaning_english' => 'general'],
            ['hanzi' => '登', 'radical' => '癶', 'pinyin' => 'dēng', 'pinyin_eng' => 'deng', 'meaning_thai' => 'ปีน', 'meaning_english' => 'to climb'],
            ['hanzi' => '竟', 'radical' => '立', 'pinyin' => 'jìng', 'pinyin_eng' => 'jing', 'meaning_thai' => 'อย่างไม่คาดคิด', 'meaning_english' => 'unexpectedly'],
            ['hanzi' => '彩', 'radical' => '彡', 'pinyin' => 'cǎi', 'pinyin_eng' => 'cai', 'meaning_thai' => 'สี', 'meaning_english' => 'color'],
            ['hanzi' => '招', 'radical' => '扌', 'pinyin' => 'zhāo', 'pinyin_eng' => 'zhao', 'meaning_thai' => 'รับสมัคร', 'meaning_english' => 'to recruit'],
            ['hanzi' => '巧', 'radical' => '工', 'pinyin' => 'qiǎo', 'pinyin_eng' => 'qiao', 'meaning_thai' => 'ชำนาญ', 'meaning_english' => 'skillful'],
            ['hanzi' => '剩', 'radical' => '刂', 'pinyin' => 'shèng', 'pinyin_eng' => 'sheng', 'meaning_thai' => 'เหลืออยู่', 'meaning_english' => 'to remain'],
            ['hanzi' => '烟', 'radical' => '火', 'pinyin' => 'yān', 'pinyin_eng' => 'yan', 'meaning_thai' => 'ควัน', 'meaning_english' => 'smoke'],
            ['hanzi' => '封', 'radical' => '寸', 'pinyin' => 'fēng', 'pinyin_eng' => 'feng', 'meaning_thai' => 'ปิดผนึก', 'meaning_english' => 'to seal'],
            ['hanzi' => '低', 'radical' => '亻', 'pinyin' => 'dī', 'pinyin_eng' => 'di', 'meaning_thai' => 'ต่ำ', 'meaning_english' => 'low'],
            ['hanzi' => '技', 'radical' => '扌', 'pinyin' => 'jì', 'pinyin_eng' => 'ji', 'meaning_thai' => 'ทักษะ', 'meaning_english' => 'skill'],
            ['hanzi' => '输', 'radical' => '车', 'pinyin' => 'shū', 'pinyin_eng' => 'shu', 'meaning_thai' => 'ขนส่ง', 'meaning_english' => 'to transport'],
            ['hanzi' => '仍', 'radical' => '亻', 'pinyin' => 'réng', 'pinyin_eng' => 'reng', 'meaning_thai' => 'ยังคง', 'meaning_english' => 'still'],
            ['hanzi' => '扔', 'radical' => '扌', 'pinyin' => 'rēng', 'pinyin_eng' => 'reng', 'meaning_thai' => 'ขว้าง', 'meaning_english' => 'to throw'],
            ['hanzi' => '社', 'radical' => '示', 'pinyin' => 'shè', 'pinyin_eng' => 'she', 'meaning_thai' => 'สังคม', 'meaning_english' => 'society'],
            ['hanzi' => '秀', 'radical' => '禾', 'pinyin' => 'xiù', 'pinyin_eng' => 'xiu', 'meaning_thai' => 'แสดง', 'meaning_english' => 'to show'],
            ['hanzi' => '刀', 'radical' => '刂', 'pinyin' => 'dāo', 'pinyin_eng' => 'dao', 'meaning_thai' => 'มีด', 'meaning_english' => 'knife'],
            ['hanzi' => '族', 'radical' => '方', 'pinyin' => 'zú', 'pinyin_eng' => 'zu', 'meaning_thai' => 'ตระกูล', 'meaning_english' => 'clan'],
            ['hanzi' => '广', 'radical' => '广', 'pinyin' => 'guǎng', 'pinyin_eng' => 'guang', 'meaning_thai' => 'กว้าง', 'meaning_english' => 'wide'],
            ['hanzi' => '镜', 'radical' => '钅', 'pinyin' => 'jìng', 'pinyin_eng' => 'jing', 'meaning_thai' => 'กระจก', 'meaning_english' => 'mirror'],
            ['hanzi' => '播', 'radical' => '扌', 'pinyin' => 'bō', 'pinyin_eng' => 'bo', 'meaning_thai' => 'ออกอากาศ', 'meaning_english' => 'to broadcast'],
            ['hanzi' => '温', 'radical' => '氵', 'pinyin' => 'wēn', 'pinyin_eng' => 'wen', 'meaning_thai' => 'อุ่น', 'meaning_english' => 'warm'],
            ['hanzi' => '遍', 'radical' => '辶', 'pinyin' => 'biàn', 'pinyin_eng' => 'bian', 'meaning_thai' => 'ทั่ว', 'meaning_english' => 'all over'],
            ['hanzi' => '尝', 'radical' => '小', 'pinyin' => 'cháng', 'pinyin_eng' => 'chang', 'meaning_thai' => 'ชิม', 'meaning_english' => 'to taste'],
            ['hanzi' => '列', 'radical' => '刂', 'pinyin' => 'liè', 'pinyin_eng' => 'lie', 'meaning_thai' => 'รายชื่อ', 'meaning_english' => 'to list'],
            ['hanzi' => '毕', 'radical' => '比', 'pinyin' => 'bì', 'pinyin_eng' => 'bi', 'meaning_thai' => 'จบ', 'meaning_english' => 'to finish'],
            ['hanzi' => '聚', 'radical' => '耂', 'pinyin' => 'jù', 'pinyin_eng' => 'ju', 'meaning_thai' => 'รวมตัว', 'meaning_english' => 'to gather'],
            ['hanzi' => '尊', 'radical' => '寸', 'pinyin' => 'zūn', 'pinyin_eng' => 'zun', 'meaning_thai' => 'เคารพ', 'meaning_english' => 'to respect'],
            ['hanzi' => '汤', 'radical' => '氵', 'pinyin' => 'tāng', 'pinyin_eng' => 'tang', 'meaning_thai' => 'ซุป', 'meaning_english' => 'soup'],
            ['hanzi' => '优', 'radical' => '亻', 'pinyin' => 'yōu', 'pinyin_eng' => 'you', 'meaning_thai' => 'ยอดเยี่ยม', 'meaning_english' => 'excellent'],
            ['hanzi' => '偶', 'radical' => '亻', 'pinyin' => 'ǒu', 'pinyin_eng' => 'ou', 'meaning_thai' => 'บังเอิญ', 'meaning_english' => 'by chance'],
            ['hanzi' => '熟', 'radical' => '灬', 'pinyin' => 'shú', 'pinyin_eng' => 'shu', 'meaning_thai' => 'คุ้นเคย', 'meaning_english' => 'familiar'],
            ['hanzi' => '微', 'radical' => '彳', 'pinyin' => 'wēi', 'pinyin_eng' => 'wei', 'meaning_thai' => 'เล็กน้อย', 'meaning_english' => 'tiny'],
            ['hanzi' => '抽', 'radical' => '扌', 'pinyin' => 'chōu', 'pinyin_eng' => 'chou', 'meaning_thai' => 'วาด', 'meaning_english' => 'to draw'],
            ['hanzi' => '艺', 'radical' => '艹', 'pinyin' => 'yì', 'pinyin_eng' => 'yi', 'meaning_thai' => 'ศิลปะ', 'meaning_english' => 'art'],
            ['hanzi' => '研', 'radical' => '石', 'pinyin' => 'yán', 'pinyin_eng' => 'yan', 'meaning_thai' => 'วิจัย', 'meaning_english' => 'to research'],
            ['hanzi' => '散', 'radical' => '攵', 'pinyin' => 'sàn', 'pinyin_eng' => 'san', 'meaning_thai' => 'กระจาย', 'meaning_english' => 'to scatter'],
            ['hanzi' => '饼', 'radical' => '饣', 'pinyin' => 'bǐng', 'pinyin_eng' => 'bing', 'meaning_thai' => 'คุกกี้', 'meaning_english' => 'cookie'],
            ['hanzi' => '糖', 'radical' => '米', 'pinyin' => 'táng', 'pinyin_eng' => 'tang', 'meaning_thai' => 'น้ำตาล', 'meaning_english' => 'sugar'],
            ['hanzi' => '富', 'radical' => '宀', 'pinyin' => 'fù', 'pinyin_eng' => 'fu', 'meaning_thai' => 'รวย', 'meaning_english' => 'rich'],
            ['hanzi' => '降', 'radical' => '阝', 'pinyin' => 'jiàng', 'pinyin_eng' => 'jiang', 'meaning_thai' => 'ตก', 'meaning_english' => 'to drop'],
            ['hanzi' => '怜', 'radical' => '心', 'pinyin' => 'lián', 'pinyin_eng' => 'lian', 'meaning_thai' => 'สงสาร', 'meaning_english' => 'to pity'],
            ['hanzi' => '既', 'radical' => '旡', 'pinyin' => 'jì', 'pinyin_eng' => 'ji', 'meaning_thai' => 'แล้ว', 'meaning_english' => 'already'],
            ['hanzi' => '笨', 'radical' => '竹', 'pinyin' => 'bèn', 'pinyin_eng' => 'ben', 'meaning_thai' => 'โง่', 'meaning_english' => 'stupid'],
            ['hanzi' => '航', 'radical' => '舟', 'pinyin' => 'háng', 'pinyin_eng' => 'hang', 'meaning_thai' => 'แล่นเรือ', 'meaning_english' => 'to sail'],
            ['hanzi' => '匙', 'radical' => '匚', 'pinyin' => 'chí', 'pinyin_eng' => 'chi', 'meaning_thai' => 'ช้อน', 'meaning_english' => 'spoon'],
            ['hanzi' => '秒', 'radical' => '禾', 'pinyin' => 'miǎo', 'pinyin_eng' => 'miao', 'meaning_thai' => 'วินาที', 'meaning_english' => 'second (time)'],
            ['hanzi' => '挂', 'radical' => '扌', 'pinyin' => 'guà', 'pinyin_eng' => 'gua', 'meaning_thai' => 'แขวน', 'meaning_english' => 'to hang'],
            ['hanzi' => '勇', 'radical' => '力', 'pinyin' => 'yǒng', 'pinyin_eng' => 'yong', 'meaning_thai' => 'กล้า', 'meaning_english' => 'brave'],
            ['hanzi' => '钥', 'radical' => '钅', 'pinyin' => 'yuè', 'pinyin_eng' => 'yue', 'meaning_thai' => 'กุญแจ', 'meaning_english' => 'key'],
            ['hanzi' => '奋', 'radical' => '大', 'pinyin' => 'fèn', 'pinyin_eng' => 'fen', 'meaning_thai' => 'พยายาม', 'meaning_english' => 'to strive'],
            ['hanzi' => '忆', 'radical' => '心', 'pinyin' => 'yì', 'pinyin_eng' => 'yi', 'meaning_thai' => 'จำ', 'meaning_english' => 'to remember'],
            ['hanzi' => '折', 'radical' => '扌', 'pinyin' => 'zhé', 'pinyin_eng' => 'zhe', 'meaning_thai' => 'พับ', 'meaning_english' => 'to fold'],
            ['hanzi' => '景', 'radical' => '日', 'pinyin' => 'jǐng', 'pinyin_eng' => 'jing', 'meaning_thai' => 'ทิวทัศน์', 'meaning_english' => 'scenery'],
            ['hanzi' => '默', 'radical' => '黑', 'pinyin' => 'mò', 'pinyin_eng' => 'mo', 'meaning_thai' => 'เงียบ', 'meaning_english' => 'silent'],
            ['hanzi' => '禁', 'radical' => '禾', 'pinyin' => 'jìn', 'pinyin_eng' => 'jin', 'meaning_thai' => 'ห้าม', 'meaning_english' => 'to prohibit'],
            ['hanzi' => '诚', 'radical' => '讠', 'pinyin' => 'chéng', 'pinyin_eng' => 'cheng', 'meaning_thai' => 'จริงใจ', 'meaning_english' => 'sincere'],
            ['hanzi' => '谅', 'radical' => '讠', 'pinyin' => 'liàng', 'pinyin_eng' => 'liang', 'meaning_thai' => 'ให้อภัย', 'meaning_english' => 'to forgive'],
            ['hanzi' => '厅', 'radical' => '厂', 'pinyin' => 'tīng', 'pinyin_eng' => 'ting', 'meaning_thai' => 'ห้องโถง', 'meaning_english' => 'hall'],
            ['hanzi' => '稍', 'radical' => '禾', 'pinyin' => 'shāo', 'pinyin_eng' => 'shao', 'meaning_thai' => 'นิดหน่อย', 'meaning_english' => 'a little'],
            ['hanzi' => '窗', 'radical' => '穴', 'pinyin' => 'chuāng', 'pinyin_eng' => 'chuang', 'meaning_thai' => 'หน้าต่าง', 'meaning_english' => 'window'],
            ['hanzi' => '章', 'radical' => '立', 'pinyin' => 'zhāng', 'pinyin_eng' => 'zhang', 'meaning_thai' => 'บท', 'meaning_english' => 'chapter'],
            ['hanzi' => '仔', 'radical' => '亻', 'pinyin' => 'zǎi', 'pinyin_eng' => 'zai', 'meaning_thai' => 'ลูกสัตว์', 'meaning_english' => 'young animal'],
            ['hanzi' => '款', 'radical' => '欠', 'pinyin' => 'kuǎn', 'pinyin_eng' => 'kuan', 'meaning_thai' => 'เงิน', 'meaning_english' => 'money'],
            ['hanzi' => '拒', 'radical' => '扌', 'pinyin' => 'jù', 'pinyin_eng' => 'ju', 'meaning_thai' => 'ปฏิเสธ', 'meaning_english' => 'to refuse'],
            ['hanzi' => '童', 'radical' => '立', 'pinyin' => 'tóng', 'pinyin_eng' => 'tong', 'meaning_thai' => 'เด็ก', 'meaning_english' => 'child'],
            ['hanzi' => '翻', 'radical' => '羽', 'pinyin' => 'fān', 'pinyin_eng' => 'fan', 'meaning_thai' => 'พลิก', 'meaning_english' => 'to flip'],
            ['hanzi' => '洲', 'radical' => '氵', 'pinyin' => 'zhōu', 'pinyin_eng' => 'zhou', 'meaning_thai' => 'ทวีป', 'meaning_english' => 'continent'],
            ['hanzi' => '互', 'radical' => '二', 'pinyin' => 'hù', 'pinyin_eng' => 'hu', 'meaning_thai' => 'ซึ่งกันและกัน', 'meaning_english' => 'mutual'],
            ['hanzi' => '例', 'radical' => '亻', 'pinyin' => 'lì', 'pinyin_eng' => 'li', 'meaning_thai' => 'ตัวอย่าง', 'meaning_english' => 'example'],
            ['hanzi' => '垃', 'radical' => '土', 'pinyin' => 'lā', 'pinyin_eng' => 'la', 'meaning_thai' => 'ขยะ', 'meaning_english' => 'garbage'],
            ['hanzi' => '染', 'radical' => '木', 'pinyin' => 'rǎn', 'pinyin_eng' => 'ran', 'meaning_thai' => 'ย้อม', 'meaning_english' => 'to dye'],
            ['hanzi' => '漫', 'radical' => '氵', 'pinyin' => 'màn', 'pinyin_eng' => 'man', 'meaning_thai' => 'ล้น', 'meaning_english' => 'to overflow'],
            ['hanzi' => '圾', 'radical' => '土', 'pinyin' => 'jī', 'pinyin_eng' => 'ji', 'meaning_thai' => 'ขยะ', 'meaning_english' => 'trash'],
            ['hanzi' => '缺', 'radical' => '缶', 'pinyin' => 'quē', 'pinyin_eng' => 'que', 'meaning_thai' => 'ขาด', 'meaning_english' => 'to lack'],
            ['hanzi' => '针', 'radical' => '钅', 'pinyin' => 'zhēn', 'pinyin_eng' => 'zhen', 'meaning_thai' => 'เข็ม', 'meaning_english' => 'needle'],
            ['hanzi' => '扮', 'radical' => '扌', 'pinyin' => 'bàn', 'pinyin_eng' => 'ban', 'meaning_thai' => 'แต่งตัว', 'meaning_english' => 'to dress up'],
            ['hanzi' => '邀', 'radical' => '阝', 'pinyin' => 'yāo', 'pinyin_eng' => 'yao', 'meaning_thai' => 'เชิญ', 'meaning_english' => 'to invite'],
            ['hanzi' => '闹', 'radical' => '门', 'pinyin' => 'nào', 'pinyin_eng' => 'nao', 'meaning_thai' => 'เสียงดัง', 'meaning_english' => 'noisy'],
            ['hanzi' => '辛', 'radical' => '辛', 'pinyin' => 'xīn', 'pinyin_eng' => 'xin', 'meaning_thai' => 'เผ็ด', 'meaning_english' => 'spicy'],
            ['hanzi' => '竞', 'radical' => '立', 'pinyin' => 'jìng', 'pinyin_eng' => 'jing', 'meaning_thai' => 'แข่งขัน', 'meaning_english' => 'to compete'],
            ['hanzi' => '厉', 'radical' => '厂', 'pinyin' => 'lì', 'pinyin_eng' => 'li', 'meaning_thai' => 'รุนแรง', 'meaning_english' => 'severe'],
            ['hanzi' => '厨', 'radical' => '厂', 'pinyin' => 'chú', 'pinyin_eng' => 'chu', 'meaning_thai' => 'ห้องครัว', 'meaning_english' => 'kitchen'],
            ['hanzi' => '允', 'radical' => '儿', 'pinyin' => 'yǔn', 'pinyin_eng' => 'yun', 'meaning_thai' => 'อนุญาต', 'meaning_english' => 'to permit'],
            ['hanzi' => '授', 'radical' => '扌', 'pinyin' => 'shòu', 'pinyin_eng' => 'shou', 'meaning_thai' => 'ให้', 'meaning_english' => 'to grant'],
            ['hanzi' => '估', 'radical' => '亻', 'pinyin' => 'gū', 'pinyin_eng' => 'gu', 'meaning_thai' => 'ประมาณ', 'meaning_english' => 'to estimate'],
            ['hanzi' => '帅', 'radical' => '巾', 'pinyin' => 'shuài', 'pinyin_eng' => 'shuai', 'meaning_thai' => 'หล่อ', 'meaning_english' => 'handsome'],
            ['hanzi' => '键', 'radical' => '钅', 'pinyin' => 'jiàn', 'pinyin_eng' => 'jian', 'meaning_thai' => 'กุญแจ', 'meaning_english' => 'key'],
            ['hanzi' => '傲', 'radical' => '亻', 'pinyin' => 'ào', 'pinyin_eng' => 'ao', 'meaning_thai' => 'ภูมิใจ', 'meaning_english' => 'proud'],
            ['hanzi' => '减', 'radical' => '冫', 'pinyin' => 'jiǎn', 'pinyin_eng' => 'jian', 'meaning_thai' => 'ลดลง', 'meaning_english' => 'to reduce'],
            ['hanzi' => '著', 'radical' => '艹', 'pinyin' => 'zhù', 'pinyin_eng' => 'zhu', 'meaning_thai' => 'เขียน', 'meaning_english' => 'to write'],
            ['hanzi' => '鼓', 'radical' => '鼓', 'pinyin' => 'gǔ', 'pinyin_eng' => 'gu', 'meaning_thai' => 'กลอง', 'meaning_english' => 'drum'],
            ['hanzi' => '盒', 'radical' => '皿', 'pinyin' => 'hé', 'pinyin_eng' => 'he', 'meaning_thai' => 'กล่อง', 'meaning_english' => 'box'],
            ['hanzi' => '寄', 'radical' => '宀', 'pinyin' => 'jì', 'pinyin_eng' => 'ji', 'meaning_thai' => 'ส่ง', 'meaning_english' => 'to send'],
            ['hanzi' => '赚', 'radical' => '贝', 'pinyin' => 'zhuàn', 'pinyin_eng' => 'zhuan', 'meaning_thai' => 'หาเงิน', 'meaning_english' => 'to earn'],
            ['hanzi' => '材', 'radical' => '木', 'pinyin' => 'cái', 'pinyin_eng' => 'cai', 'meaning_thai' => 'วัสดุ', 'meaning_english' => 'material'],
            ['hanzi' => '尤', 'radical' => '尢', 'pinyin' => 'yóu', 'pinyin_eng' => 'you', 'meaning_thai' => 'โดยเฉพาะ', 'meaning_english' => 'especially'],
            ['hanzi' => '愉', 'radical' => '忄', 'pinyin' => 'yú', 'pinyin_eng' => 'yu', 'meaning_thai' => 'มีความสุข', 'meaning_english' => 'happy'],
            ['hanzi' => '序', 'radical' => '广', 'pinyin' => 'xù', 'pinyin_eng' => 'xu', 'meaning_thai' => 'ลำดับ', 'meaning_english' => 'order'],
            ['hanzi' => '烤', 'radical' => '火', 'pinyin' => 'kǎo', 'pinyin_eng' => 'kao', 'meaning_thai' => 'ย่าง', 'meaning_english' => 'to roast'],
            ['hanzi' => '悔', 'radical' => '忄', 'pinyin' => 'huǐ', 'pinyin_eng' => 'hui', 'meaning_thai' => 'เสียใจ', 'meaning_english' => 'to regret'],
            ['hanzi' => '暂', 'radical' => '日', 'pinyin' => 'zàn', 'pinyin_eng' => 'zan', 'meaning_thai' => 'ชั่วคราว', 'meaning_english' => 'temporary'],
            ['hanzi' => '惜', 'radical' => '忄', 'pinyin' => 'xī', 'pinyin_eng' => 'xi', 'meaning_thai' => 'หวงแหน', 'meaning_english' => 'to cherish'],
            ['hanzi' => '拾', 'radical' => '扌', 'pinyin' => 'shí', 'pinyin_eng' => 'shi', 'meaning_thai' => 'หยิบขึ้น', 'meaning_english' => 'to pick up'],
            ['hanzi' => '申', 'radical' => '田', 'pinyin' => 'shēn', 'pinyin_eng' => 'shen', 'meaning_thai' => 'ประกาศ', 'meaning_english' => 'to declare'],
            ['hanzi' => '批', 'radical' => '扌', 'pinyin' => 'pī', 'pinyin_eng' => 'pi', 'meaning_thai' => 'อนุมัติ', 'meaning_english' => 'to approve'],
            ['hanzi' => '乘', 'radical' => '乘', 'pinyin' => 'chéng', 'pinyin_eng' => 'cheng', 'meaning_thai' => 'ขี่', 'meaning_english' => 'to ride'],
            ['hanzi' => '辣', 'radical' => '辛', 'pinyin' => 'là', 'pinyin_eng' => 'la', 'meaning_thai' => 'เผ็ด', 'meaning_english' => 'spicy'],
            ['hanzi' => '躺', 'radical' => '身', 'pinyin' => 'tǎng', 'pinyin_eng' => 'tang', 'meaning_thai' => 'นอนลง', 'meaning_english' => 'to lie down'],
            ['hanzi' => '肥', 'radical' => '月', 'pinyin' => 'féi', 'pinyin_eng' => 'fei', 'meaning_thai' => 'อ้วน', 'meaning_english' => 'fat'],
            ['hanzi' => '址', 'radical' => '土', 'pinyin' => 'zhǐ', 'pinyin_eng' => 'zhi', 'meaning_thai' => 'ที่ตั้ง', 'meaning_english' => 'site'],
            ['hanzi' => '占', 'radical' => '占', 'pinyin' => 'zhàn', 'pinyin_eng' => 'zhan', 'meaning_thai' => 'ยึดครอง', 'meaning_english' => 'to occupy'],
            ['hanzi' => '省', 'radical' => '目', 'pinyin' => 'shěng', 'pinyin_eng' => 'sheng', 'meaning_thai' => 'จังหวัด', 'meaning_english' => 'province'],
            ['hanzi' => '增', 'radical' => '土', 'pinyin' => 'zēng', 'pinyin_eng' => 'zeng', 'meaning_thai' => 'เพิ่ม', 'meaning_english' => 'to increase'],
            ['hanzi' => '擦', 'radical' => '扌', 'pinyin' => 'cā', 'pinyin_eng' => 'ca', 'meaning_thai' => 'เช็ด', 'meaning_english' => 'to wipe'],
            ['hanzi' => '洋', 'radical' => '氵', 'pinyin' => 'yáng', 'pinyin_eng' => 'yang', 'meaning_thai' => 'มหาสมุทร', 'meaning_english' => 'ocean'],
            ['hanzi' => '符', 'radical' => '竹', 'pinyin' => 'fú', 'pinyin_eng' => 'fu', 'meaning_thai' => 'สัญลักษณ์', 'meaning_english' => 'symbol'],
            ['hanzi' => '骄', 'radical' => '马', 'pinyin' => 'jiāo', 'pinyin_eng' => 'jiao', 'meaning_thai' => 'ภูมิใจ', 'meaning_english' => 'proud'],
            ['hanzi' => '羞', 'radical' => '羊', 'pinyin' => 'xiū', 'pinyin_eng' => 'xiu', 'meaning_thai' => 'อาย', 'meaning_english' => 'shy'],
            ['hanzi' => '贺', 'radical' => '贝', 'pinyin' => 'hè', 'pinyin_eng' => 'he', 'meaning_thai' => 'แสดงความยินดี', 'meaning_english' => 'to congratulate'],
            ['hanzi' => '敲', 'radical' => '攵', 'pinyin' => 'qiāo', 'pinyin_eng' => 'qiao', 'meaning_thai' => 'เคาะ', 'meaning_english' => 'to knock'],
            ['hanzi' => '购', 'radical' => '贝', 'pinyin' => 'gòu', 'pinyin_eng' => 'gou', 'meaning_thai' => 'ซื้อ', 'meaning_english' => 'to purchase'],
            ['hanzi' => '售', 'radical' => '口', 'pinyin' => 'shòu', 'pinyin_eng' => 'shou', 'meaning_thai' => 'ขาย', 'meaning_english' => 'to sell'],
            ['hanzi' => '耐', 'radical' => '而', 'pinyin' => 'nài', 'pinyin_eng' => 'nai', 'meaning_thai' => 'อดทน', 'meaning_english' => 'to endure'],
            ['hanzi' => '琴', 'radical' => '玉', 'pinyin' => 'qín', 'pinyin_eng' => 'qin', 'meaning_thai' => 'เปียโน', 'meaning_english' => 'piano'],
            ['hanzi' => '貌', 'radical' => '貝', 'pinyin' => 'mào', 'pinyin_eng' => 'mao', 'meaning_thai' => 'ลักษณะ', 'meaning_english' => 'appearance'],
            ['hanzi' => '倍', 'radical' => '亻', 'pinyin' => 'bèi', 'pinyin_eng' => 'bei', 'meaning_thai' => 'เท่า', 'meaning_english' => 'times'],
            ['hanzi' => '桥', 'radical' => '木', 'pinyin' => 'qiáo', 'pinyin_eng' => 'qiao', 'meaning_thai' => 'สะพาน', 'meaning_english' => 'bridge'],
            ['hanzi' => '肤', 'radical' => '月', 'pinyin' => 'fū', 'pinyin_eng' => 'fu', 'meaning_thai' => 'ผิวหนัง', 'meaning_english' => 'skin'],
            ['hanzi' => '厕', 'radical' => '厂', 'pinyin' => 'cè', 'pinyin_eng' => 'ce', 'meaning_thai' => 'ห้องน้ำ', 'meaning_english' => 'toilet'],
            ['hanzi' => '植', 'radical' => '木', 'pinyin' => 'zhí', 'pinyin_eng' => 'zhi', 'meaning_thai' => 'ปลูก', 'meaning_english' => 'to plant'],
            ['hanzi' => '距', 'radical' => '足', 'pinyin' => 'jù', 'pinyin_eng' => 'ju', 'meaning_thai' => 'ระยะทาง', 'meaning_english' => 'distance'],
            ['hanzi' => '虎', 'radical' => '虍', 'pinyin' => 'hǔ', 'pinyin_eng' => 'hu', 'meaning_thai' => 'เสือ', 'meaning_english' => 'tiger'],
            ['hanzi' => '济', 'radical' => '氵', 'pinyin' => 'jì', 'pinyin_eng' => 'ji', 'meaning_thai' => 'ช่วยเหลือ', 'meaning_english' => 'to aid'],
            ['hanzi' => '粗', 'radical' => '米', 'pinyin' => 'cū', 'pinyin_eng' => 'cu', 'meaning_thai' => 'หยาบ', 'meaning_english' => 'coarse'],
            ['hanzi' => '肚', 'radical' => '月', 'pinyin' => 'dù', 'pinyin_eng' => 'du', 'meaning_thai' => 'ท้อง', 'meaning_english' => 'belly'],
            ['hanzi' => '暖', 'radical' => '日', 'pinyin' => 'nuǎn', 'pinyin_eng' => 'nuan', 'meaning_thai' => 'อบอุ่น', 'meaning_english' => 'warm'],
            ['hanzi' => '励', 'radical' => '力', 'pinyin' => 'lì', 'pinyin_eng' => 'li', 'meaning_thai' => 'สนับสนุน', 'meaning_english' => 'to encourage'],
            ['hanzi' => '积', 'radical' => '禾', 'pinyin' => 'jī', 'pinyin_eng' => 'ji', 'meaning_thai' => 'สะสม', 'meaning_english' => 'to accumulate'],
            ['hanzi' => '云', 'radical' => '云', 'pinyin' => 'yún', 'pinyin_eng' => 'yun', 'meaning_thai' => 'เมฆ', 'meaning_english' => 'cloud'],
            ['hanzi' => '幽', 'radical' => '幺', 'pinyin' => 'yōu', 'pinyin_eng' => 'you', 'meaning_thai' => 'เงียบ', 'meaning_english' => 'quiet'],
            ['hanzi' => '龄', 'radical' => '龍', 'pinyin' => 'líng', 'pinyin_eng' => 'ling', 'meaning_thai' => 'อายุ', 'meaning_english' => 'age'],
            ['hanzi' => '汁', 'radical' => '氵', 'pinyin' => 'zhī', 'pinyin_eng' => 'zhi', 'meaning_thai' => 'น้ำผลไม้', 'meaning_english' => 'juice'],
            ['hanzi' => '钢', 'radical' => '钅', 'pinyin' => 'gāng', 'pinyin_eng' => 'gang', 'meaning_thai' => 'เหล็ก', 'meaning_english' => 'steel'],
            ['hanzi' => '篇', 'radical' => '竹', 'pinyin' => 'piān', 'pinyin_eng' => 'pian', 'meaning_thai' => 'บทความ', 'meaning_english' => 'article'],
            ['hanzi' => '汗', 'radical' => '氵', 'pinyin' => 'hàn', 'pinyin_eng' => 'han', 'meaning_thai' => 'เหงื่อ', 'meaning_english' => 'sweat'],
            ['hanzi' => '酸', 'radical' => '酉', 'pinyin' => 'suān', 'pinyin_eng' => 'suan', 'meaning_thai' => 'เปรี้ยว', 'meaning_english' => 'sour'],
            ['hanzi' => '叶', 'radical' => '口', 'pinyin' => 'yè', 'pinyin_eng' => 'ye', 'meaning_thai' => 'ใบไม้', 'meaning_english' => 'leaf'],
            ['hanzi' => '趟', 'radical' => '走', 'pinyin' => 'tàng', 'pinyin_eng' => 'tang', 'meaning_thai' => 'การเดินทาง', 'meaning_english' => 'trip'],
            ['hanzi' => '抬', 'radical' => '扌', 'pinyin' => 'tái', 'pinyin_eng' => 'tai', 'meaning_thai' => 'ยกขึ้น', 'meaning_english' => 'to lift'],
            ['hanzi' => '悉', 'radical' => '忄', 'pinyin' => 'xī', 'pinyin_eng' => 'xi', 'meaning_thai' => 'รู้ดี', 'meaning_english' => 'to know well'],
            ['hanzi' => '页', 'radical' => '页', 'pinyin' => 'yè', 'pinyin_eng' => 'ye', 'meaning_thai' => 'หน้าหนังสือ', 'meaning_english' => 'page'],
            ['hanzi' => '桶', 'radical' => '木', 'pinyin' => 'tǒng', 'pinyin_eng' => 'tong', 'meaning_thai' => 'ถัง', 'meaning_english' => 'barrel'],
            ['hanzi' => '巾', 'radical' => '巾', 'pinyin' => 'jīn', 'pinyin_eng' => 'jin', 'meaning_thai' => 'ผ้าขนหนู', 'meaning_english' => 'towel'],
            ['hanzi' => '穷', 'radical' => '穴', 'pinyin' => 'qióng', 'pinyin_eng' => 'qiong', 'meaning_thai' => 'จน', 'meaning_english' => 'poor'],
            ['hanzi' => '扬', 'radical' => '扌', 'pinyin' => 'yáng', 'pinyin_eng' => 'yang', 'meaning_thai' => 'ยกขึ้น', 'meaning_english' => 'to raise'],
            ['hanzi' => '污', 'radical' => '氵', 'pinyin' => 'wū', 'pinyin_eng' => 'wu', 'meaning_thai' => 'สกปรก', 'meaning_english' => 'dirty'],
            ['hanzi' => '填', 'radical' => '土', 'pinyin' => 'tián', 'pinyin_eng' => 'tian', 'meaning_thai' => 'เติม', 'meaning_english' => 'to fill'],
            ['hanzi' => '塑', 'radical' => '土', 'pinyin' => 'sù', 'pinyin_eng' => 'su', 'meaning_thai' => 'พลาสติก', 'meaning_english' => 'plastic'],
            ['hanzi' => '丰', 'radical' => '丬', 'pinyin' => 'fēng', 'pinyin_eng' => 'feng', 'meaning_thai' => 'อุดมสมบูรณ์', 'meaning_english' => 'abundant'],
            ['hanzi' => '孙', 'radical' => '子', 'pinyin' => 'sūn', 'pinyin_eng' => 'sun', 'meaning_thai' => 'หลาน', 'meaning_english' => 'grandchild'],
            ['hanzi' => '恼', 'radical' => '忄', 'pinyin' => 'nǎo', 'pinyin_eng' => 'nao', 'meaning_thai' => 'รำคาญ', 'meaning_english' => 'annoyed'],
            ['hanzi' => '详', 'radical' => '讠', 'pinyin' => 'xiáng', 'pinyin_eng' => 'xiang', 'meaning_thai' => 'รายละเอียด', 'meaning_english' => 'detailed'],
            ['hanzi' => '葡', 'radical' => '艹', 'pinyin' => 'pú', 'pinyin_eng' => 'pu', 'meaning_thai' => 'องุ่น', 'meaning_english' => 'grape'],
            ['hanzi' => '萄', 'radical' => '艹', 'pinyin' => 'táo', 'pinyin_eng' => 'tao', 'meaning_thai' => 'องุ่น', 'meaning_english' => 'grape'],
            ['hanzi' => '脾', 'radical' => '月', 'pinyin' => 'pí', 'pinyin_eng' => 'pi', 'meaning_thai' => 'ม้าม', 'meaning_english' => 'spleen'],
            ['hanzi' => '凉', 'radical' => '冫', 'pinyin' => 'liáng', 'pinyin_eng' => 'liang', 'meaning_thai' => 'เย็น', 'meaning_english' => 'cool'],
            ['hanzi' => '厚', 'radical' => '厂', 'pinyin' => 'hòu', 'pinyin_eng' => 'hou', 'meaning_thai' => 'หนา', 'meaning_english' => 'thick'],
            ['hanzi' => '矿', 'radical' => '石', 'pinyin' => 'kuàng', 'pinyin_eng' => 'kuang', 'meaning_thai' => 'เหมือง', 'meaning_english' => 'mine'],
            ['hanzi' => '逛', 'radical' => '辶', 'pinyin' => 'guàng', 'pinyin_eng' => 'guang', 'meaning_thai' => 'เดินเล่น', 'meaning_english' => 'to stroll'],
            ['hanzi' => '堵', 'radical' => '土', 'pinyin' => 'dǔ', 'pinyin_eng' => 'du', 'meaning_thai' => 'ขวาง', 'meaning_english' => 'to block'],
            ['hanzi' => '胳', 'radical' => '月', 'pinyin' => 'gē', 'pinyin_eng' => 'ge', 'meaning_thai' => 'แขน', 'meaning_english' => 'arm'],
            ['hanzi' => '谊', 'radical' => '讠', 'pinyin' => 'yì', 'pinyin_eng' => 'yi', 'meaning_thai' => 'มิตรภาพ', 'meaning_english' => 'friendship'],
            ['hanzi' => '泉', 'radical' => '水', 'pinyin' => 'quán', 'pinyin_eng' => 'quan', 'meaning_thai' => 'น้ำพุ', 'meaning_english' => 'spring (water)'],
            ['hanzi' => '袜', 'radical' => '衤', 'pinyin' => 'wà', 'pinyin_eng' => 'wa', 'meaning_thai' => 'ถุงเท้า', 'meaning_english' => 'sock'],
            ['hanzi' => '膊', 'radical' => '月', 'pinyin' => 'bó', 'pinyin_eng' => 'bo', 'meaning_thai' => 'แขนบน', 'meaning_english' => 'upper arm'],
            ['hanzi' => '懒', 'radical' => '忄', 'pinyin' => 'lǎn', 'pinyin_eng' => 'lan', 'meaning_thai' => 'ขี้เกียจ', 'meaning_english' => 'lazy'],
            ['hanzi' => '盐', 'radical' => '卤', 'pinyin' => 'yán', 'pinyin_eng' => 'yan', 'meaning_thai' => 'เกลือ', 'meaning_english' => 'salt'],
            ['hanzi' => '江', 'radical' => '氵', 'pinyin' => 'jiāng', 'pinyin_eng' => 'jiang', 'meaning_thai' => 'แม่น้ำ', 'meaning_english' => 'river'],
            ['hanzi' => '鸭', 'radical' => '鸟', 'pinyin' => 'yā', 'pinyin_eng' => 'ya', 'meaning_thai' => 'เป็ด', 'meaning_english' => 'duck'],
            ['hanzi' => '膏', 'radical' => '月', 'pinyin' => 'gāo', 'pinyin_eng' => 'gao', 'meaning_thai' => 'ขี้ผึ้ง', 'meaning_english' => 'paste'],
            ['hanzi' => '慕', 'radical' => '忄', 'pinyin' => 'mù', 'pinyin_eng' => 'mu', 'meaning_thai' => 'ชื่นชม', 'meaning_english' => 'to admire'],
            ['hanzi' => '阅', 'radical' => '门', 'pinyin' => 'yuè', 'pinyin_eng' => 'yue', 'meaning_thai' => 'อ่าน', 'meaning_english' => 'to read'],
            ['hanzi' => '寒', 'radical' => '宀', 'pinyin' => 'hán', 'pinyin_eng' => 'han', 'meaning_thai' => 'หนาว', 'meaning_english' => 'cold'],
            ['hanzi' => '棵', 'radical' => '木', 'pinyin' => 'kē', 'pinyin_eng' => 'ke', 'meaning_thai' => 'ต้นไม้', 'meaning_english' => 'tree (measure word)'],
            ['hanzi' => '橡', 'radical' => '木', 'pinyin' => 'xiàng', 'pinyin_eng' => 'xiang', 'meaning_thai' => 'ยาง', 'meaning_english' => 'rubber'],
            ['hanzi' => '泼', 'radical' => '氵', 'pinyin' => 'pō', 'pinyin_eng' => 'po', 'meaning_thai' => 'กระเซ็น', 'meaning_english' => 'to splash'],
            ['hanzi' => '础', 'radical' => '石', 'pinyin' => 'chǔ', 'pinyin_eng' => 'chu', 'meaning_thai' => 'พื้นฐาน', 'meaning_english' => 'foundation'],
            ['hanzi' => '戚', 'radical' => '戈', 'pinyin' => 'qī', 'pinyin_eng' => 'qi', 'meaning_thai' => 'ญาติ', 'meaning_english' => 'relative'],
            ['hanzi' => '暑', 'radical' => '日', 'pinyin' => 'shǔ', 'pinyin_eng' => 'shu', 'meaning_thai' => 'ความร้อนในฤดูร้อน', 'meaning_english' => 'summer heat'],
            ['hanzi' => '咳', 'radical' => '口', 'pinyin' => 'ké', 'pinyin_eng' => 'ke', 'meaning_thai' => 'ไอ', 'meaning_english' => 'to cough'],
            ['hanzi' => '聘', 'radical' => '耳', 'pinyin' => 'pìn', 'pinyin_eng' => 'pin', 'meaning_thai' => 'จ้าง', 'meaning_english' => 'to hire'],
            ['hanzi' => '郊', 'radical' => '阝', 'pinyin' => 'jiāo', 'pinyin_eng' => 'jiao', 'meaning_thai' => 'ชานเมือง', 'meaning_english' => 'suburb'],
            ['hanzi' => '傅', 'radical' => '亻', 'pinyin' => 'fù', 'pinyin_eng' => 'fu', 'meaning_thai' => 'ผู้สอน', 'meaning_english' => 'tutor'],
            ['hanzi' => '羽', 'radical' => '羽', 'pinyin' => 'yǔ', 'pinyin_eng' => 'yu', 'meaning_thai' => 'ขนนก', 'meaning_english' => 'feather'],
            ['hanzi' => '籍', 'radical' => '竹', 'pinyin' => 'jí', 'pinyin_eng' => 'ji', 'meaning_thai' => 'สัญชาติ', 'meaning_english' => 'nationality'],
            ['hanzi' => '勺', 'radical' => '勹', 'pinyin' => 'sháo', 'pinyin_eng' => 'shao', 'meaning_thai' => 'ช้อน', 'meaning_english' => 'spoon'],
            ['hanzi' => '羡', 'radical' => '羊', 'pinyin' => 'xiàn', 'pinyin_eng' => 'xian', 'meaning_thai' => 'อิจฉา', 'meaning_english' => 'to envy'],
            ['hanzi' => '硕', 'radical' => '石', 'pinyin' => 'shuò', 'pinyin_eng' => 'shuo', 'meaning_thai' => 'ใหญ่', 'meaning_english' => 'large'],
            ['hanzi' => '咸', 'radical' => '口', 'pinyin' => 'xián', 'pinyin_eng' => 'xian', 'meaning_thai' => 'เค็ม', 'meaning_english' => 'salty'],
            ['hanzi' => '译', 'radical' => '讠', 'pinyin' => 'yì', 'pinyin_eng' => 'yi', 'meaning_thai' => 'แปล', 'meaning_english' => 'to translate'],
            ['hanzi' => '乓', 'radical' => '丿', 'pinyin' => 'pāng', 'pinyin_eng' => 'pang', 'meaning_thai' => 'ปิงปอง', 'meaning_english' => 'pong (ping pong)'],
            ['hanzi' => '嗽', 'radical' => '口', 'pinyin' => 'sòu', 'pinyin_eng' => 'sou', 'meaning_thai' => 'ไอ', 'meaning_english' => 'cough'],
            ['hanzi' => '乒', 'radical' => '丿', 'pinyin' => 'pīng', 'pinyin_eng' => 'ping', 'meaning_thai' => 'ปิงปอง', 'meaning_english' => 'ping (ping pong)'],
            ['hanzi' => '柿', 'radical' => '木', 'pinyin' => 'shì', 'pinyin_eng' => 'shi', 'meaning_thai' => 'ลูกพลับ', 'meaning_english' => 'persimmon'],
            ['hanzi' => '饺', 'radical' => '饣', 'pinyin' => 'jiǎo', 'pinyin_eng' => 'jiao', 'meaning_thai' => 'เกี๊ยว', 'meaning_english' => 'dumpling'],
        ]);

        // hanzi_categories HSK 4 (447)
        DB::table('hanzi_categories')->insert([
            ['hanzi_id' => 618, 'category_id' => 4],
            ['hanzi_id' => 619, 'category_id' => 4],
            ['hanzi_id' => 620, 'category_id' => 4],
            ['hanzi_id' => 621, 'category_id' => 4],
            ['hanzi_id' => 622, 'category_id' => 4],
            ['hanzi_id' => 623, 'category_id' => 4],
            ['hanzi_id' => 624, 'category_id' => 4],
            ['hanzi_id' => 625, 'category_id' => 4],
            ['hanzi_id' => 626, 'category_id' => 4],
            ['hanzi_id' => 627, 'category_id' => 4],
            ['hanzi_id' => 628, 'category_id' => 4],
            ['hanzi_id' => 629, 'category_id' => 4],
            ['hanzi_id' => 630, 'category_id' => 4],
            ['hanzi_id' => 631, 'category_id' => 4],
            ['hanzi_id' => 632, 'category_id' => 4],
            ['hanzi_id' => 633, 'category_id' => 4],
            ['hanzi_id' => 634, 'category_id' => 4],
            ['hanzi_id' => 635, 'category_id' => 4],
            ['hanzi_id' => 636, 'category_id' => 4],
            ['hanzi_id' => 637, 'category_id' => 4],
            ['hanzi_id' => 638, 'category_id' => 4],
            ['hanzi_id' => 639, 'category_id' => 4],
            ['hanzi_id' => 640, 'category_id' => 4],
            ['hanzi_id' => 641, 'category_id' => 4],
            ['hanzi_id' => 642, 'category_id' => 4],
            ['hanzi_id' => 643, 'category_id' => 4],
            ['hanzi_id' => 644, 'category_id' => 4],
            ['hanzi_id' => 645, 'category_id' => 4],
            ['hanzi_id' => 646, 'category_id' => 4],
            ['hanzi_id' => 647, 'category_id' => 4],
            ['hanzi_id' => 648, 'category_id' => 4],
            ['hanzi_id' => 649, 'category_id' => 4],
            ['hanzi_id' => 650, 'category_id' => 4],
            ['hanzi_id' => 651, 'category_id' => 4],
            ['hanzi_id' => 652, 'category_id' => 4],
            ['hanzi_id' => 653, 'category_id' => 4],
            ['hanzi_id' => 654, 'category_id' => 4],
            ['hanzi_id' => 655, 'category_id' => 4],
            ['hanzi_id' => 656, 'category_id' => 4],
            ['hanzi_id' => 657, 'category_id' => 4],
            ['hanzi_id' => 658, 'category_id' => 4],
            ['hanzi_id' => 659, 'category_id' => 4],
            ['hanzi_id' => 660, 'category_id' => 4],
            ['hanzi_id' => 661, 'category_id' => 4],
            ['hanzi_id' => 662, 'category_id' => 4],
            ['hanzi_id' => 663, 'category_id' => 4],
            ['hanzi_id' => 664, 'category_id' => 4],
            ['hanzi_id' => 665, 'category_id' => 4],
            ['hanzi_id' => 666, 'category_id' => 4],
            ['hanzi_id' => 667, 'category_id' => 4],
            ['hanzi_id' => 668, 'category_id' => 4],
            ['hanzi_id' => 669, 'category_id' => 4],
            ['hanzi_id' => 670, 'category_id' => 4],
            ['hanzi_id' => 671, 'category_id' => 4],
            ['hanzi_id' => 672, 'category_id' => 4],
            ['hanzi_id' => 673, 'category_id' => 4],
            ['hanzi_id' => 674, 'category_id' => 4],
            ['hanzi_id' => 675, 'category_id' => 4],
            ['hanzi_id' => 676, 'category_id' => 4],
            ['hanzi_id' => 677, 'category_id' => 4],
            ['hanzi_id' => 678, 'category_id' => 4],
            ['hanzi_id' => 679, 'category_id' => 4],
            ['hanzi_id' => 680, 'category_id' => 4],
            ['hanzi_id' => 681, 'category_id' => 4],
            ['hanzi_id' => 682, 'category_id' => 4],
            ['hanzi_id' => 683, 'category_id' => 4],
            ['hanzi_id' => 684, 'category_id' => 4],
            ['hanzi_id' => 685, 'category_id' => 4],
            ['hanzi_id' => 686, 'category_id' => 4],
            ['hanzi_id' => 687, 'category_id' => 4],
            ['hanzi_id' => 688, 'category_id' => 4],
            ['hanzi_id' => 689, 'category_id' => 4],
            ['hanzi_id' => 690, 'category_id' => 4],
            ['hanzi_id' => 691, 'category_id' => 4],
            ['hanzi_id' => 692, 'category_id' => 4],
            ['hanzi_id' => 693, 'category_id' => 4],
            ['hanzi_id' => 694, 'category_id' => 4],
            ['hanzi_id' => 695, 'category_id' => 4],
            ['hanzi_id' => 696, 'category_id' => 4],
            ['hanzi_id' => 697, 'category_id' => 4],
            ['hanzi_id' => 698, 'category_id' => 4],
            ['hanzi_id' => 699, 'category_id' => 4],
            ['hanzi_id' => 700, 'category_id' => 4],
            ['hanzi_id' => 701, 'category_id' => 4],
            ['hanzi_id' => 702, 'category_id' => 4],
            ['hanzi_id' => 703, 'category_id' => 4],
            ['hanzi_id' => 704, 'category_id' => 4],
            ['hanzi_id' => 705, 'category_id' => 4],
            ['hanzi_id' => 706, 'category_id' => 4],
            ['hanzi_id' => 707, 'category_id' => 4],
            ['hanzi_id' => 708, 'category_id' => 4],
            ['hanzi_id' => 709, 'category_id' => 4],
            ['hanzi_id' => 710, 'category_id' => 4],
            ['hanzi_id' => 711, 'category_id' => 4],
            ['hanzi_id' => 712, 'category_id' => 4],
            ['hanzi_id' => 713, 'category_id' => 4],
            ['hanzi_id' => 714, 'category_id' => 4],
            ['hanzi_id' => 715, 'category_id' => 4],
            ['hanzi_id' => 716, 'category_id' => 4],
            ['hanzi_id' => 717, 'category_id' => 4],
            ['hanzi_id' => 718, 'category_id' => 4],
            ['hanzi_id' => 719, 'category_id' => 4],
            ['hanzi_id' => 720, 'category_id' => 4],
            ['hanzi_id' => 721, 'category_id' => 4],
            ['hanzi_id' => 722, 'category_id' => 4],
            ['hanzi_id' => 723, 'category_id' => 4],
            ['hanzi_id' => 724, 'category_id' => 4],
            ['hanzi_id' => 725, 'category_id' => 4],
            ['hanzi_id' => 726, 'category_id' => 4],
            ['hanzi_id' => 727, 'category_id' => 4],
            ['hanzi_id' => 728, 'category_id' => 4],
            ['hanzi_id' => 729, 'category_id' => 4],
            ['hanzi_id' => 730, 'category_id' => 4],
            ['hanzi_id' => 731, 'category_id' => 4],
            ['hanzi_id' => 732, 'category_id' => 4],
            ['hanzi_id' => 733, 'category_id' => 4],
            ['hanzi_id' => 734, 'category_id' => 4],
            ['hanzi_id' => 735, 'category_id' => 4],
            ['hanzi_id' => 736, 'category_id' => 4],
            ['hanzi_id' => 737, 'category_id' => 4],
            ['hanzi_id' => 738, 'category_id' => 4],
            ['hanzi_id' => 739, 'category_id' => 4],
            ['hanzi_id' => 740, 'category_id' => 4],
            ['hanzi_id' => 741, 'category_id' => 4],
            ['hanzi_id' => 742, 'category_id' => 4],
            ['hanzi_id' => 743, 'category_id' => 4],
            ['hanzi_id' => 744, 'category_id' => 4],
            ['hanzi_id' => 745, 'category_id' => 4],
            ['hanzi_id' => 746, 'category_id' => 4],
            ['hanzi_id' => 747, 'category_id' => 4],
            ['hanzi_id' => 748, 'category_id' => 4],
            ['hanzi_id' => 749, 'category_id' => 4],
            ['hanzi_id' => 750, 'category_id' => 4],
            ['hanzi_id' => 751, 'category_id' => 4],
            ['hanzi_id' => 752, 'category_id' => 4],
            ['hanzi_id' => 753, 'category_id' => 4],
            ['hanzi_id' => 754, 'category_id' => 4],
            ['hanzi_id' => 755, 'category_id' => 4],
            ['hanzi_id' => 756, 'category_id' => 4],
            ['hanzi_id' => 757, 'category_id' => 4],
            ['hanzi_id' => 758, 'category_id' => 4],
            ['hanzi_id' => 759, 'category_id' => 4],
            ['hanzi_id' => 760, 'category_id' => 4],
            ['hanzi_id' => 761, 'category_id' => 4],
            ['hanzi_id' => 762, 'category_id' => 4],
            ['hanzi_id' => 763, 'category_id' => 4],
            ['hanzi_id' => 764, 'category_id' => 4],
            ['hanzi_id' => 765, 'category_id' => 4],
            ['hanzi_id' => 766, 'category_id' => 4],
            ['hanzi_id' => 767, 'category_id' => 4],
            ['hanzi_id' => 768, 'category_id' => 4],
            ['hanzi_id' => 769, 'category_id' => 4],
            ['hanzi_id' => 770, 'category_id' => 4],
            ['hanzi_id' => 771, 'category_id' => 4],
            ['hanzi_id' => 772, 'category_id' => 4],
            ['hanzi_id' => 773, 'category_id' => 4],
            ['hanzi_id' => 774, 'category_id' => 4],
            ['hanzi_id' => 775, 'category_id' => 4],
            ['hanzi_id' => 776, 'category_id' => 4],
            ['hanzi_id' => 777, 'category_id' => 4],
            ['hanzi_id' => 778, 'category_id' => 4],
            ['hanzi_id' => 779, 'category_id' => 4],
            ['hanzi_id' => 780, 'category_id' => 4],
            ['hanzi_id' => 781, 'category_id' => 4],
            ['hanzi_id' => 782, 'category_id' => 4],
            ['hanzi_id' => 783, 'category_id' => 4],
            ['hanzi_id' => 784, 'category_id' => 4],
            ['hanzi_id' => 785, 'category_id' => 4],
            ['hanzi_id' => 786, 'category_id' => 4],
            ['hanzi_id' => 787, 'category_id' => 4],
            ['hanzi_id' => 788, 'category_id' => 4],
            ['hanzi_id' => 789, 'category_id' => 4],
            ['hanzi_id' => 790, 'category_id' => 4],
            ['hanzi_id' => 791, 'category_id' => 4],
            ['hanzi_id' => 792, 'category_id' => 4],
            ['hanzi_id' => 793, 'category_id' => 4],
            ['hanzi_id' => 794, 'category_id' => 4],
            ['hanzi_id' => 795, 'category_id' => 4],
            ['hanzi_id' => 796, 'category_id' => 4],
            ['hanzi_id' => 797, 'category_id' => 4],
            ['hanzi_id' => 798, 'category_id' => 4],
            ['hanzi_id' => 799, 'category_id' => 4],
            ['hanzi_id' => 800, 'category_id' => 4],
            ['hanzi_id' => 801, 'category_id' => 4],
            ['hanzi_id' => 802, 'category_id' => 4],
            ['hanzi_id' => 803, 'category_id' => 4],
            ['hanzi_id' => 804, 'category_id' => 4],
            ['hanzi_id' => 805, 'category_id' => 4],
            ['hanzi_id' => 806, 'category_id' => 4],
            ['hanzi_id' => 807, 'category_id' => 4],
            ['hanzi_id' => 808, 'category_id' => 4],
            ['hanzi_id' => 809, 'category_id' => 4],
            ['hanzi_id' => 810, 'category_id' => 4],
            ['hanzi_id' => 811, 'category_id' => 4],
            ['hanzi_id' => 812, 'category_id' => 4],
            ['hanzi_id' => 813, 'category_id' => 4],
            ['hanzi_id' => 814, 'category_id' => 4],
            ['hanzi_id' => 815, 'category_id' => 4],
            ['hanzi_id' => 816, 'category_id' => 4],
            ['hanzi_id' => 817, 'category_id' => 4],
            ['hanzi_id' => 818, 'category_id' => 4],
            ['hanzi_id' => 819, 'category_id' => 4],
            ['hanzi_id' => 820, 'category_id' => 4],
            ['hanzi_id' => 821, 'category_id' => 4],
            ['hanzi_id' => 822, 'category_id' => 4],
            ['hanzi_id' => 823, 'category_id' => 4],
            ['hanzi_id' => 824, 'category_id' => 4],
            ['hanzi_id' => 825, 'category_id' => 4],
            ['hanzi_id' => 826, 'category_id' => 4],
            ['hanzi_id' => 827, 'category_id' => 4],
            ['hanzi_id' => 828, 'category_id' => 4],
            ['hanzi_id' => 829, 'category_id' => 4],
            ['hanzi_id' => 830, 'category_id' => 4],
            ['hanzi_id' => 831, 'category_id' => 4],
            ['hanzi_id' => 832, 'category_id' => 4],
            ['hanzi_id' => 833, 'category_id' => 4],
            ['hanzi_id' => 834, 'category_id' => 4],
            ['hanzi_id' => 835, 'category_id' => 4],
            ['hanzi_id' => 836, 'category_id' => 4],
            ['hanzi_id' => 837, 'category_id' => 4],
            ['hanzi_id' => 838, 'category_id' => 4],
            ['hanzi_id' => 839, 'category_id' => 4],
            ['hanzi_id' => 840, 'category_id' => 4],
            ['hanzi_id' => 841, 'category_id' => 4],
            ['hanzi_id' => 842, 'category_id' => 4],
            ['hanzi_id' => 843, 'category_id' => 4],
            ['hanzi_id' => 844, 'category_id' => 4],
            ['hanzi_id' => 845, 'category_id' => 4],
            ['hanzi_id' => 846, 'category_id' => 4],
            ['hanzi_id' => 847, 'category_id' => 4],
            ['hanzi_id' => 848, 'category_id' => 4],
            ['hanzi_id' => 849, 'category_id' => 4],
            ['hanzi_id' => 850, 'category_id' => 4],
            ['hanzi_id' => 851, 'category_id' => 4],
            ['hanzi_id' => 852, 'category_id' => 4],
            ['hanzi_id' => 853, 'category_id' => 4],
            ['hanzi_id' => 854, 'category_id' => 4],
            ['hanzi_id' => 855, 'category_id' => 4],
            ['hanzi_id' => 856, 'category_id' => 4],
            ['hanzi_id' => 857, 'category_id' => 4],
            ['hanzi_id' => 858, 'category_id' => 4],
            ['hanzi_id' => 859, 'category_id' => 4],
            ['hanzi_id' => 860, 'category_id' => 4],
            ['hanzi_id' => 861, 'category_id' => 4],
            ['hanzi_id' => 862, 'category_id' => 4],
            ['hanzi_id' => 863, 'category_id' => 4],
            ['hanzi_id' => 864, 'category_id' => 4],
            ['hanzi_id' => 865, 'category_id' => 4],
            ['hanzi_id' => 866, 'category_id' => 4],
            ['hanzi_id' => 867, 'category_id' => 4],
            ['hanzi_id' => 868, 'category_id' => 4],
            ['hanzi_id' => 869, 'category_id' => 4],
            ['hanzi_id' => 870, 'category_id' => 4],
            ['hanzi_id' => 871, 'category_id' => 4],
            ['hanzi_id' => 872, 'category_id' => 4],
            ['hanzi_id' => 873, 'category_id' => 4],
            ['hanzi_id' => 874, 'category_id' => 4],
            ['hanzi_id' => 875, 'category_id' => 4],
            ['hanzi_id' => 876, 'category_id' => 4],
            ['hanzi_id' => 877, 'category_id' => 4],
            ['hanzi_id' => 878, 'category_id' => 4],
            ['hanzi_id' => 879, 'category_id' => 4],
            ['hanzi_id' => 880, 'category_id' => 4],
            ['hanzi_id' => 881, 'category_id' => 4],
            ['hanzi_id' => 882, 'category_id' => 4],
            ['hanzi_id' => 883, 'category_id' => 4],
            ['hanzi_id' => 884, 'category_id' => 4],
            ['hanzi_id' => 885, 'category_id' => 4],
            ['hanzi_id' => 886, 'category_id' => 4],
            ['hanzi_id' => 887, 'category_id' => 4],
            ['hanzi_id' => 888, 'category_id' => 4],
            ['hanzi_id' => 889, 'category_id' => 4],
            ['hanzi_id' => 890, 'category_id' => 4],
            ['hanzi_id' => 891, 'category_id' => 4],
            ['hanzi_id' => 892, 'category_id' => 4],
            ['hanzi_id' => 893, 'category_id' => 4],
            ['hanzi_id' => 894, 'category_id' => 4],
            ['hanzi_id' => 895, 'category_id' => 4],
            ['hanzi_id' => 896, 'category_id' => 4],
            ['hanzi_id' => 897, 'category_id' => 4],
            ['hanzi_id' => 898, 'category_id' => 4],
            ['hanzi_id' => 899, 'category_id' => 4],
            ['hanzi_id' => 900, 'category_id' => 4],
            ['hanzi_id' => 901, 'category_id' => 4],
            ['hanzi_id' => 902, 'category_id' => 4],
            ['hanzi_id' => 903, 'category_id' => 4],
            ['hanzi_id' => 904, 'category_id' => 4],
            ['hanzi_id' => 905, 'category_id' => 4],
            ['hanzi_id' => 906, 'category_id' => 4],
            ['hanzi_id' => 907, 'category_id' => 4],
            ['hanzi_id' => 908, 'category_id' => 4],
            ['hanzi_id' => 909, 'category_id' => 4],
            ['hanzi_id' => 910, 'category_id' => 4],
            ['hanzi_id' => 911, 'category_id' => 4],
            ['hanzi_id' => 912, 'category_id' => 4],
            ['hanzi_id' => 913, 'category_id' => 4],
            ['hanzi_id' => 914, 'category_id' => 4],
            ['hanzi_id' => 915, 'category_id' => 4],
            ['hanzi_id' => 916, 'category_id' => 4],
            ['hanzi_id' => 917, 'category_id' => 4],
            ['hanzi_id' => 918, 'category_id' => 4],
            ['hanzi_id' => 919, 'category_id' => 4],
            ['hanzi_id' => 920, 'category_id' => 4],
            ['hanzi_id' => 921, 'category_id' => 4],
            ['hanzi_id' => 922, 'category_id' => 4],
            ['hanzi_id' => 923, 'category_id' => 4],
            ['hanzi_id' => 924, 'category_id' => 4],
            ['hanzi_id' => 925, 'category_id' => 4],
            ['hanzi_id' => 926, 'category_id' => 4],
            ['hanzi_id' => 927, 'category_id' => 4],
            ['hanzi_id' => 928, 'category_id' => 4],
            ['hanzi_id' => 929, 'category_id' => 4],
            ['hanzi_id' => 930, 'category_id' => 4],
            ['hanzi_id' => 931, 'category_id' => 4],
            ['hanzi_id' => 932, 'category_id' => 4],
            ['hanzi_id' => 933, 'category_id' => 4],
            ['hanzi_id' => 934, 'category_id' => 4],
            ['hanzi_id' => 935, 'category_id' => 4],
            ['hanzi_id' => 936, 'category_id' => 4],
            ['hanzi_id' => 937, 'category_id' => 4],
            ['hanzi_id' => 938, 'category_id' => 4],
            ['hanzi_id' => 939, 'category_id' => 4],
            ['hanzi_id' => 940, 'category_id' => 4],
            ['hanzi_id' => 941, 'category_id' => 4],
            ['hanzi_id' => 942, 'category_id' => 4],
            ['hanzi_id' => 943, 'category_id' => 4],
            ['hanzi_id' => 944, 'category_id' => 4],
            ['hanzi_id' => 945, 'category_id' => 4],
            ['hanzi_id' => 946, 'category_id' => 4],
            ['hanzi_id' => 947, 'category_id' => 4],
            ['hanzi_id' => 948, 'category_id' => 4],
            ['hanzi_id' => 949, 'category_id' => 4],
            ['hanzi_id' => 950, 'category_id' => 4],
            ['hanzi_id' => 951, 'category_id' => 4],
            ['hanzi_id' => 952, 'category_id' => 4],
            ['hanzi_id' => 953, 'category_id' => 4],
            ['hanzi_id' => 954, 'category_id' => 4],
            ['hanzi_id' => 955, 'category_id' => 4],
            ['hanzi_id' => 956, 'category_id' => 4],
            ['hanzi_id' => 957, 'category_id' => 4],
            ['hanzi_id' => 958, 'category_id' => 4],
            ['hanzi_id' => 959, 'category_id' => 4],
            ['hanzi_id' => 960, 'category_id' => 4],
            ['hanzi_id' => 961, 'category_id' => 4],
            ['hanzi_id' => 962, 'category_id' => 4],
            ['hanzi_id' => 963, 'category_id' => 4],
            ['hanzi_id' => 964, 'category_id' => 4],
            ['hanzi_id' => 965, 'category_id' => 4],
            ['hanzi_id' => 966, 'category_id' => 4],
            ['hanzi_id' => 967, 'category_id' => 4],
            ['hanzi_id' => 968, 'category_id' => 4],
            ['hanzi_id' => 969, 'category_id' => 4],
            ['hanzi_id' => 970, 'category_id' => 4],
            ['hanzi_id' => 971, 'category_id' => 4],
            ['hanzi_id' => 972, 'category_id' => 4],
            ['hanzi_id' => 973, 'category_id' => 4],
            ['hanzi_id' => 974, 'category_id' => 4],
            ['hanzi_id' => 975, 'category_id' => 4],
            ['hanzi_id' => 976, 'category_id' => 4],
            ['hanzi_id' => 977, 'category_id' => 4],
            ['hanzi_id' => 978, 'category_id' => 4],
            ['hanzi_id' => 979, 'category_id' => 4],
            ['hanzi_id' => 980, 'category_id' => 4],
            ['hanzi_id' => 981, 'category_id' => 4],
            ['hanzi_id' => 982, 'category_id' => 4],
            ['hanzi_id' => 983, 'category_id' => 4],
            ['hanzi_id' => 984, 'category_id' => 4],
            ['hanzi_id' => 985, 'category_id' => 4],
            ['hanzi_id' => 986, 'category_id' => 4],
            ['hanzi_id' => 987, 'category_id' => 4],
            ['hanzi_id' => 988, 'category_id' => 4],
            ['hanzi_id' => 989, 'category_id' => 4],
            ['hanzi_id' => 990, 'category_id' => 4],
            ['hanzi_id' => 991, 'category_id' => 4],
            ['hanzi_id' => 992, 'category_id' => 4],
            ['hanzi_id' => 993, 'category_id' => 4],
            ['hanzi_id' => 994, 'category_id' => 4],
            ['hanzi_id' => 995, 'category_id' => 4],
            ['hanzi_id' => 996, 'category_id' => 4],
            ['hanzi_id' => 997, 'category_id' => 4],
            ['hanzi_id' => 998, 'category_id' => 4],
            ['hanzi_id' => 999, 'category_id' => 4],
            ['hanzi_id' => 1000, 'category_id' => 4],
            ['hanzi_id' => 1001, 'category_id' => 4],
            ['hanzi_id' => 1002, 'category_id' => 4],
            ['hanzi_id' => 1003, 'category_id' => 4],
            ['hanzi_id' => 1004, 'category_id' => 4],
            ['hanzi_id' => 1005, 'category_id' => 4],
            ['hanzi_id' => 1006, 'category_id' => 4],
            ['hanzi_id' => 1007, 'category_id' => 4],
            ['hanzi_id' => 1008, 'category_id' => 4],
            ['hanzi_id' => 1009, 'category_id' => 4],
            ['hanzi_id' => 1010, 'category_id' => 4],
            ['hanzi_id' => 1011, 'category_id' => 4],
            ['hanzi_id' => 1012, 'category_id' => 4],
            ['hanzi_id' => 1013, 'category_id' => 4],
            ['hanzi_id' => 1014, 'category_id' => 4],
            ['hanzi_id' => 1015, 'category_id' => 4],
            ['hanzi_id' => 1016, 'category_id' => 4],
            ['hanzi_id' => 1017, 'category_id' => 4],
            ['hanzi_id' => 1018, 'category_id' => 4],
            ['hanzi_id' => 1019, 'category_id' => 4],
            ['hanzi_id' => 1020, 'category_id' => 4],
            ['hanzi_id' => 1021, 'category_id' => 4],
            ['hanzi_id' => 1022, 'category_id' => 4],
            ['hanzi_id' => 1023, 'category_id' => 4],
            ['hanzi_id' => 1024, 'category_id' => 4],
            ['hanzi_id' => 1025, 'category_id' => 4],
            ['hanzi_id' => 1026, 'category_id' => 4],
            ['hanzi_id' => 1027, 'category_id' => 4],
            ['hanzi_id' => 1028, 'category_id' => 4],
            ['hanzi_id' => 1029, 'category_id' => 4],
            ['hanzi_id' => 1030, 'category_id' => 4],
            ['hanzi_id' => 1031, 'category_id' => 4],
            ['hanzi_id' => 1032, 'category_id' => 4],
            ['hanzi_id' => 1033, 'category_id' => 4],
            ['hanzi_id' => 1034, 'category_id' => 4],
            ['hanzi_id' => 1035, 'category_id' => 4],
            ['hanzi_id' => 1036, 'category_id' => 4],
            ['hanzi_id' => 1037, 'category_id' => 4],
            ['hanzi_id' => 1038, 'category_id' => 4],
            ['hanzi_id' => 1039, 'category_id' => 4],
            ['hanzi_id' => 1040, 'category_id' => 4],
            ['hanzi_id' => 1041, 'category_id' => 4],
            ['hanzi_id' => 1042, 'category_id' => 4],
            ['hanzi_id' => 1043, 'category_id' => 4],
            ['hanzi_id' => 1044, 'category_id' => 4],
            ['hanzi_id' => 1045, 'category_id' => 4],
            ['hanzi_id' => 1046, 'category_id' => 4],
            ['hanzi_id' => 1047, 'category_id' => 4],
            ['hanzi_id' => 1048, 'category_id' => 4],
            ['hanzi_id' => 1049, 'category_id' => 4],
            ['hanzi_id' => 1050, 'category_id' => 4],
            ['hanzi_id' => 1051, 'category_id' => 4],
            ['hanzi_id' => 1052, 'category_id' => 4],
            ['hanzi_id' => 1053, 'category_id' => 4],
            ['hanzi_id' => 1054, 'category_id' => 4],
            ['hanzi_id' => 1055, 'category_id' => 4],
            ['hanzi_id' => 1056, 'category_id' => 4],
            ['hanzi_id' => 1057, 'category_id' => 4],
            ['hanzi_id' => 1058, 'category_id' => 4],
            ['hanzi_id' => 1059, 'category_id' => 4],
            ['hanzi_id' => 1060, 'category_id' => 4],
            ['hanzi_id' => 1061, 'category_id' => 4],
            ['hanzi_id' => 1062, 'category_id' => 4],
            ['hanzi_id' => 1063, 'category_id' => 4],
            ['hanzi_id' => 1064, 'category_id' => 4],
        ]);
    }
}
