<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HanziHSK1Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // hanzi HSK 1 (174)
        DB::table('hanzi')->insert([
            ['hanzi' => '我', 'radical' => '戈', 'pinyin' => 'wǒ', 'pinyin_eng' => 'wo', 'meaning_thai' => 'ฉัน, ผม', 'meaning_english' => 'I, me'],
            ['hanzi' => '的', 'radical' => '白', 'pinyin' => 'de', 'pinyin_eng' => 'de', 'meaning_thai' => 'ของ', 'meaning_english' => 'possessive particle'],
            ['hanzi' => '你', 'radical' => '亻', 'pinyin' => 'nǐ', 'pinyin_eng' => 'ni', 'meaning_thai' => 'คุณ', 'meaning_english' => 'you'],
            ['hanzi' => '是', 'radical' => '日', 'pinyin' => 'shì', 'pinyin_eng' => 'shi', 'meaning_thai' => 'เป็น, คือ', 'meaning_english' => 'is, are, am'],
            ['hanzi' => '了', 'radical' => '亅', 'pinyin' => 'le', 'pinyin_eng' => 'le', 'meaning_thai' => 'แล้ว', 'meaning_english' => 'past tense marker'],
            ['hanzi' => '不', 'radical' => '一', 'pinyin' => 'bù', 'pinyin_eng' => 'bu', 'meaning_thai' => 'ไม่', 'meaning_english' => 'not, no'],
            ['hanzi' => '们', 'radical' => '亻', 'pinyin' => 'men', 'pinyin_eng' => 'men', 'meaning_thai' => 'พวก', 'meaning_english' => 'plural marker'],
            ['hanzi' => '这', 'radical' => '辶', 'pinyin' => 'zhè', 'pinyin_eng' => 'zhe', 'meaning_thai' => 'นี้', 'meaning_english' => 'this'],
            ['hanzi' => '一', 'radical' => '一', 'pinyin' => 'yī', 'pinyin_eng' => 'yi', 'meaning_thai' => 'หนึ่ง', 'meaning_english' => 'one'],
            ['hanzi' => '他', 'radical' => '亻', 'pinyin' => 'tā', 'pinyin_eng' => 'ta', 'meaning_thai' => 'เขา', 'meaning_english' => 'he, him'],
            ['hanzi' => '么', 'radical' => '丿', 'pinyin' => 'me', 'pinyin_eng' => 'me', 'meaning_thai' => 'ไหม', 'meaning_english' => 'interrogative particle'],
            ['hanzi' => '在', 'radical' => '土', 'pinyin' => 'zài', 'pinyin_eng' => 'zai', 'meaning_thai' => 'อยู่', 'meaning_english' => 'at, in, on'],
            ['hanzi' => '有', 'radical' => '月', 'pinyin' => 'yǒu', 'pinyin_eng' => 'you', 'meaning_thai' => 'มี', 'meaning_english' => 'have, there is'],
            ['hanzi' => '个', 'radical' => '丨', 'pinyin' => 'gè', 'pinyin_eng' => 'ge', 'meaning_thai' => 'อัน', 'meaning_english' => 'measure word'],
            ['hanzi' => '好', 'radical' => '女', 'pinyin' => 'hǎo', 'pinyin_eng' => 'hao', 'meaning_thai' => 'ดี', 'meaning_english' => 'good'],
            ['hanzi' => '来', 'radical' => '木', 'pinyin' => 'lái', 'pinyin_eng' => 'lai', 'meaning_thai' => 'มา', 'meaning_english' => 'come'],
            ['hanzi' => '人', 'radical' => '人', 'pinyin' => 'rén', 'pinyin_eng' => 'ren', 'meaning_thai' => 'คน', 'meaning_english' => 'person'],
            ['hanzi' => '那', 'radical' => '阝', 'pinyin' => 'nà', 'pinyin_eng' => 'na', 'meaning_thai' => 'นั้น', 'meaning_english' => 'that'],
            ['hanzi' => '会', 'radical' => '人', 'pinyin' => 'huì', 'pinyin_eng' => 'hui', 'meaning_thai' => 'สามารถ', 'meaning_english' => 'can, will'],
            ['hanzi' => '什', 'radical' => '亻', 'pinyin' => 'shén', 'pinyin_eng' => 'shen', 'meaning_thai' => 'อะไร', 'meaning_english' => 'what'],
            ['hanzi' => '没', 'radical' => '氵', 'pinyin' => 'méi', 'pinyin_eng' => 'mei', 'meaning_thai' => 'ไม่มี', 'meaning_english' => 'not have'],
            ['hanzi' => '说', 'radical' => '讠', 'pinyin' => 'shuō', 'pinyin_eng' => 'shuo', 'meaning_thai' => 'พูด', 'meaning_english' => 'say, speak'],
            ['hanzi' => '吗', 'radical' => '口', 'pinyin' => 'ma', 'pinyin_eng' => 'ma', 'meaning_thai' => 'ไหม', 'meaning_english' => 'question particle'],
            ['hanzi' => '想', 'radical' => '心', 'pinyin' => 'xiǎng', 'pinyin_eng' => 'xiang', 'meaning_thai' => 'คิด, ต้องการ', 'meaning_english' => 'want, think'],
            ['hanzi' => '能', 'radical' => '月', 'pinyin' => 'néng', 'pinyin_eng' => 'neng', 'meaning_thai' => 'สามารถ', 'meaning_english' => 'can, able to'],
            ['hanzi' => '上', 'radical' => '一', 'pinyin' => 'shàng', 'pinyin_eng' => 'shang', 'meaning_thai' => 'ขึ้น, บน', 'meaning_english' => 'up, above'],
            ['hanzi' => '去', 'radical' => '厶', 'pinyin' => 'qù', 'pinyin_eng' => 'qu', 'meaning_thai' => 'ไป', 'meaning_english' => 'go'],
            ['hanzi' => '她', 'radical' => '女', 'pinyin' => 'tā', 'pinyin_eng' => 'ta', 'meaning_thai' => 'เธอ', 'meaning_english' => 'she, her'],
            ['hanzi' => '很', 'radical' => '彳', 'pinyin' => 'hěn', 'pinyin_eng' => 'hen', 'meaning_thai' => 'มาก', 'meaning_english' => 'very'],
            ['hanzi' => '看', 'radical' => '目', 'pinyin' => 'kàn', 'pinyin_eng' => 'kan', 'meaning_thai' => 'ดู, เห็น', 'meaning_english' => 'look, see'],
            ['hanzi' => '对', 'radical' => '寸', 'pinyin' => 'duì', 'pinyin_eng' => 'dui', 'meaning_thai' => 'ถูกต้อง, ต่อ', 'meaning_english' => 'correct, to'],
            ['hanzi' => '里', 'radical' => '里', 'pinyin' => 'lǐ', 'pinyin_eng' => 'li', 'meaning_thai' => 'ใน', 'meaning_english' => 'inside'],
            ['hanzi' => '都', 'radical' => '阝', 'pinyin' => 'dōu', 'pinyin_eng' => 'dou', 'meaning_thai' => 'ทั้งหมด', 'meaning_english' => 'all, both'],
            ['hanzi' => '子', 'radical' => '子', 'pinyin' => 'zǐ', 'pinyin_eng' => 'zi', 'meaning_thai' => 'เด็ก, ลูกชาย', 'meaning_english' => 'child, son'],
            ['hanzi' => '生', 'radical' => '生', 'pinyin' => 'shēng', 'pinyin_eng' => 'sheng', 'meaning_thai' => 'ชีวิต, เกิด', 'meaning_english' => 'life, give birth'],
            ['hanzi' => '时', 'radical' => '日', 'pinyin' => 'shí', 'pinyin_eng' => 'shi', 'meaning_thai' => 'เวลา', 'meaning_english' => 'time'],
            ['hanzi' => '样', 'radical' => '木', 'pinyin' => 'yàng', 'pinyin_eng' => 'yang', 'meaning_thai' => 'ประเภท', 'meaning_english' => 'kind, type'],
            ['hanzi' => '和', 'radical' => '口', 'pinyin' => 'hé', 'pinyin_eng' => 'he', 'meaning_thai' => 'และ', 'meaning_english' => 'and, with'],
            ['hanzi' => '下', 'radical' => '一', 'pinyin' => 'xià', 'pinyin_eng' => 'xia', 'meaning_thai' => 'ลง, ข้างล่าง', 'meaning_english' => 'down, below'],
            ['hanzi' => '现', 'radical' => '王', 'pinyin' => 'xiàn', 'pinyin_eng' => 'xian', 'meaning_thai' => 'ปรากฏ, ตอนนี้', 'meaning_english' => 'appear, now'],
            ['hanzi' => '做', 'radical' => '亻', 'pinyin' => 'zuò', 'pinyin_eng' => 'zuo', 'meaning_thai' => 'ทำ', 'meaning_english' => 'do, make'],
            ['hanzi' => '大', 'radical' => '大', 'pinyin' => 'dà', 'pinyin_eng' => 'da', 'meaning_thai' => 'ใหญ่', 'meaning_english' => 'big, large'],
            ['hanzi' => '怎', 'radical' => '心', 'pinyin' => 'zěn', 'pinyin_eng' => 'zen', 'meaning_thai' => 'อย่างไร', 'meaning_english' => 'how'],
            ['hanzi' => '出', 'radical' => '凵', 'pinyin' => 'chū', 'pinyin_eng' => 'chu', 'meaning_thai' => 'ออก', 'meaning_english' => 'out, exit'],
            ['hanzi' => '点', 'radical' => '灬', 'pinyin' => 'diǎn', 'pinyin_eng' => 'dian', 'meaning_thai' => 'จุด', 'meaning_english' => 'dot, point'],
            ['hanzi' => '起', 'radical' => '走', 'pinyin' => 'qǐ', 'pinyin_eng' => 'qi', 'meaning_thai' => 'ขึ้น, เริ่ม', 'meaning_english' => 'rise, start'],
            ['hanzi' => '天', 'radical' => '大', 'pinyin' => 'tiān', 'pinyin_eng' => 'tian', 'meaning_thai' => 'ท้องฟ้า, วัน', 'meaning_english' => 'sky, day'],
            ['hanzi' => '开', 'radical' => '廾', 'pinyin' => 'kāi', 'pinyin_eng' => 'kai', 'meaning_thai' => 'เปิด', 'meaning_english' => 'open'],
            ['hanzi' => '谢', 'radical' => '讠', 'pinyin' => 'xiè', 'pinyin_eng' => 'xie', 'meaning_thai' => 'ขอบคุณ', 'meaning_english' => 'thank'],
            ['hanzi' => '些', 'radical' => '二', 'pinyin' => 'xiē', 'pinyin_eng' => 'xie', 'meaning_thai' => 'บาง', 'meaning_english' => 'some'],
            ['hanzi' => '家', 'radical' => '宀', 'pinyin' => 'jiā', 'pinyin_eng' => 'jia', 'meaning_thai' => 'บ้าน, ครอบครัว', 'meaning_english' => 'home, family'],
            ['hanzi' => '后', 'radical' => '厂', 'pinyin' => 'hòu', 'pinyin_eng' => 'hou', 'meaning_thai' => 'หลังจาก, ข้างหลัง', 'meaning_english' => 'after, behind'],
            ['hanzi' => '儿', 'radical' => '儿', 'pinyin' => 'ér', 'pinyin_eng' => 'er', 'meaning_thai' => 'เด็ก', 'meaning_english' => 'child'],
            ['hanzi' => '多', 'radical' => '夕', 'pinyin' => 'duō', 'pinyin_eng' => 'duo', 'meaning_thai' => 'มาก', 'meaning_english' => 'many, much'],
            ['hanzi' => '话', 'radical' => '讠', 'pinyin' => 'huà', 'pinyin_eng' => 'hua', 'meaning_thai' => 'คำพูด, พูด', 'meaning_english' => 'word, talk'],
            ['hanzi' => '小', 'radical' => '小', 'pinyin' => 'xiǎo', 'pinyin_eng' => 'xiao', 'meaning_thai' => 'เล็ก', 'meaning_english' => 'small, little'],
            ['hanzi' => '回', 'radical' => '囗', 'pinyin' => 'huí', 'pinyin_eng' => 'hui', 'meaning_thai' => 'กลับ', 'meaning_english' => 'return, go back'],
            ['hanzi' => '果', 'radical' => '木', 'pinyin' => 'guǒ', 'pinyin_eng' => 'guo', 'meaning_thai' => 'ผลไม้, ผล', 'meaning_english' => 'fruit, result'],
            ['hanzi' => '见', 'radical' => '见', 'pinyin' => 'jiàn', 'pinyin_eng' => 'jian', 'meaning_thai' => 'เห็น', 'meaning_english' => 'see'],
            ['hanzi' => '听', 'radical' => '口', 'pinyin' => 'tīng', 'pinyin_eng' => 'ting', 'meaning_thai' => 'ฟัง', 'meaning_english' => 'listen'],
            ['hanzi' => '觉', 'radical' => '见', 'pinyin' => 'jué', 'pinyin_eng' => 'jue', 'meaning_thai' => 'รู้สึก', 'meaning_english' => 'feel, sense'],
            ['hanzi' => '太', 'radical' => '大', 'pinyin' => 'tài', 'pinyin_eng' => 'tai', 'meaning_thai' => 'มากเกินไป', 'meaning_english' => 'too, very'],
            ['hanzi' => '妈', 'radical' => '女', 'pinyin' => 'mā', 'pinyin_eng' => 'ma', 'meaning_thai' => 'แม่', 'meaning_english' => 'mom'],
            ['hanzi' => '打', 'radical' => '扌', 'pinyin' => 'dǎ', 'pinyin_eng' => 'da', 'meaning_thai' => 'ตี, เล่น', 'meaning_english' => 'hit, play'],
            ['hanzi' => '再', 'radical' => '冂', 'pinyin' => 'zài', 'pinyin_eng' => 'zai', 'meaning_thai' => 'อีกครั้ง', 'meaning_english' => 'again'],
            ['hanzi' => '呢', 'radical' => '口', 'pinyin' => 'ne', 'pinyin_eng' => 'ne', 'meaning_thai' => 'ล่ะ', 'meaning_english' => 'question particle'],
            ['hanzi' => '女', 'radical' => '女', 'pinyin' => 'nǚ', 'pinyin_eng' => 'nu', 'meaning_thai' => 'ผู้หญิง', 'meaning_english' => 'woman'],
            ['hanzi' => '前', 'radical' => '刂', 'pinyin' => 'qián', 'pinyin_eng' => 'qian', 'meaning_thai' => 'ก่อน, ข้างหน้า', 'meaning_english' => 'before, front'],
            ['hanzi' => '先', 'radical' => '儿', 'pinyin' => 'xiān', 'pinyin_eng' => 'xian', 'meaning_thai' => 'ก่อน', 'meaning_english' => 'first, before'],
            ['hanzi' => '明', 'radical' => '日', 'pinyin' => 'míng', 'pinyin_eng' => 'ming', 'meaning_thai' => 'สว่าง, ชัดเจน', 'meaning_english' => 'bright, clear'],
            ['hanzi' => '中', 'radical' => '丨', 'pinyin' => 'zhōng', 'pinyin_eng' => 'zhong', 'meaning_thai' => 'กลาง', 'meaning_english' => 'middle, center'],
            ['hanzi' => '作', 'radical' => '亻', 'pinyin' => 'zuò', 'pinyin_eng' => 'zuo', 'meaning_thai' => 'ทำ', 'meaning_english' => 'do, make'],
            ['hanzi' => '面', 'radical' => '面', 'pinyin' => 'miàn', 'pinyin_eng' => 'mian', 'meaning_thai' => 'หน้า, พื้นผิว', 'meaning_english' => 'face, surface'],
            ['hanzi' => '爱', 'radical' => '爫', 'pinyin' => 'ài', 'pinyin_eng' => 'ai', 'meaning_thai' => 'รัก', 'meaning_english' => 'love'],
            ['hanzi' => '电', 'radical' => '田', 'pinyin' => 'diàn', 'pinyin_eng' => 'dian', 'meaning_thai' => 'ไฟฟ้า', 'meaning_english' => 'electric'],
            ['hanzi' => '哪', 'radical' => '口', 'pinyin' => 'nǎ', 'pinyin_eng' => 'na', 'meaning_thai' => 'อันไหน', 'meaning_english' => 'which'],
            ['hanzi' => '西', 'radical' => '覀', 'pinyin' => 'xī', 'pinyin_eng' => 'xi', 'meaning_thai' => 'ตะวันตก', 'meaning_english' => 'west'],
            ['hanzi' => '候', 'radical' => '亻', 'pinyin' => 'hòu', 'pinyin_eng' => 'hou', 'meaning_thai' => 'เวลา, รอ', 'meaning_english' => 'time, wait'],
            ['hanzi' => '欢', 'radical' => '欠', 'pinyin' => 'huān', 'pinyin_eng' => 'huan', 'meaning_thai' => 'ยินดี', 'meaning_english' => 'happy'],
            ['hanzi' => '关', 'radical' => '丷', 'pinyin' => 'guān', 'pinyin_eng' => 'guan', 'meaning_thai' => 'ปิด, ความสัมพันธ์', 'meaning_english' => 'close, relation'],
            ['hanzi' => '车', 'radical' => '车', 'pinyin' => 'chē', 'pinyin_eng' => 'che', 'meaning_thai' => 'รถ', 'meaning_english' => 'car, vehicle'],
            ['hanzi' => '年', 'radical' => '干', 'pinyin' => 'nián', 'pinyin_eng' => 'nian', 'meaning_thai' => 'ปี', 'meaning_english' => 'year'],
            ['hanzi' => '喜', 'radical' => '口', 'pinyin' => 'xǐ', 'pinyin_eng' => 'xi', 'meaning_thai' => 'ยินดี', 'meaning_english' => 'happy'],
            ['hanzi' => '认', 'radical' => '讠', 'pinyin' => 'rèn', 'pinyin_eng' => 'ren', 'meaning_thai' => 'รู้จัก', 'meaning_english' => 'recognize, know'],
            ['hanzi' => '爸', 'radical' => '父', 'pinyin' => 'bà', 'pinyin_eng' => 'ba', 'meaning_thai' => 'พ่อ', 'meaning_english' => 'dad'],
            ['hanzi' => '谁', 'radical' => '讠', 'pinyin' => 'shuí', 'pinyin_eng' => 'shui', 'meaning_thai' => 'ใคร', 'meaning_english' => 'who'],
            ['hanzi' => '老', 'radical' => '老', 'pinyin' => 'lǎo', 'pinyin_eng' => 'lao', 'meaning_thai' => 'แก่', 'meaning_english' => 'old'],
            ['hanzi' => '机', 'radical' => '木', 'pinyin' => 'jī', 'pinyin_eng' => 'ji', 'meaning_thai' => 'เครื่องจักร, โอกาส', 'meaning_english' => 'machine, opportunity'],
            ['hanzi' => '分', 'radical' => '刀', 'pinyin' => 'fēn', 'pinyin_eng' => 'fen', 'meaning_thai' => 'แบ่ง, นาที', 'meaning_english' => 'divide, minute'],
            ['hanzi' => '今', 'radical' => '人', 'pinyin' => 'jīn', 'pinyin_eng' => 'jin', 'meaning_thai' => 'ตอนนี้, วันนี้', 'meaning_english' => 'now, today'],
            ['hanzi' => '工', 'radical' => '工', 'pinyin' => 'gōng', 'pinyin_eng' => 'gong', 'meaning_thai' => 'งาน, คนงาน', 'meaning_english' => 'work, worker'],
            ['hanzi' => '东', 'radical' => '一', 'pinyin' => 'dōng', 'pinyin_eng' => 'dong', 'meaning_thai' => 'ตะวันออก', 'meaning_english' => 'east'],
            ['hanzi' => '名', 'radical' => '口', 'pinyin' => 'míng', 'pinyin_eng' => 'ming', 'meaning_thai' => 'ชื่อ', 'meaning_english' => 'name'],
            ['hanzi' => '同', 'radical' => '口', 'pinyin' => 'tóng', 'pinyin_eng' => 'tong', 'meaning_thai' => 'เหมือนกัน, ด้วยกัน', 'meaning_english' => 'same, together'],
            ['hanzi' => '学', 'radical' => '子', 'pinyin' => 'xué', 'pinyin_eng' => 'xue', 'meaning_thai' => 'เรียนรู้', 'meaning_english' => 'study, learn'],
            ['hanzi' => '叫', 'radical' => '口', 'pinyin' => 'jiào', 'pinyin_eng' => 'jiao', 'meaning_thai' => 'เรียก, ตะโกน', 'meaning_english' => 'call, shout'],
            ['hanzi' => '本', 'radical' => '木', 'pinyin' => 'běn', 'pinyin_eng' => 'ben', 'meaning_thai' => 'ต้นกำเนิด, หนังสือ', 'meaning_english' => 'origin, book'],
            ['hanzi' => '国', 'radical' => '囗', 'pinyin' => 'guó', 'pinyin_eng' => 'guo', 'meaning_thai' => 'ประเทศ', 'meaning_english' => 'country'],
            ['hanzi' => '友', 'radical' => '又', 'pinyin' => 'yǒu', 'pinyin_eng' => 'you', 'meaning_thai' => 'เพื่อน', 'meaning_english' => 'friend'],
            ['hanzi' => '高', 'radical' => '高', 'pinyin' => 'gāo', 'pinyin_eng' => 'gao', 'meaning_thai' => 'สูง', 'meaning_english' => 'high, tall'],
            ['hanzi' => '请', 'radical' => '讠', 'pinyin' => 'qǐng', 'pinyin_eng' => 'qing', 'meaning_thai' => 'โปรด, เชิญ', 'meaning_english' => 'please, invite'],
            ['hanzi' => '住', 'radical' => '亻', 'pinyin' => 'zhù', 'pinyin_eng' => 'zhu', 'meaning_thai' => 'อาศัย', 'meaning_english' => 'live, reside'],
            ['hanzi' => '钱', 'radical' => '钅', 'pinyin' => 'qián', 'pinyin_eng' => 'qian', 'meaning_thai' => 'เงิน', 'meaning_english' => 'money'],
            ['hanzi' => '吃', 'radical' => '口', 'pinyin' => 'chī', 'pinyin_eng' => 'chi', 'meaning_thai' => 'กิน', 'meaning_english' => 'eat'],
            ['hanzi' => '朋', 'radical' => '月', 'pinyin' => 'péng', 'pinyin_eng' => 'peng', 'meaning_thai' => 'เพื่อน', 'meaning_english' => 'friend'],
            ['hanzi' => '系', 'radical' => '糸', 'pinyin' => 'xì', 'pinyin_eng' => 'xi', 'meaning_thai' => 'ระบบ, ผูก', 'meaning_english' => 'system, tie'],
            ['hanzi' => '几', 'radical' => '几', 'pinyin' => 'jǐ', 'pinyin_eng' => 'ji', 'meaning_thai' => 'ไม่กี่, หลาย', 'meaning_english' => 'few, several'],
            ['hanzi' => '气', 'radical' => '气', 'pinyin' => 'qì', 'pinyin_eng' => 'qi', 'meaning_thai' => 'อากาศ, แก๊ส', 'meaning_english' => 'air, gas'],
            ['hanzi' => '少', 'radical' => '小', 'pinyin' => 'shǎo', 'pinyin_eng' => 'shao', 'meaning_thai' => 'น้อย, น้อยลง', 'meaning_english' => 'few, less'],
            ['hanzi' => '医', 'radical' => '匚', 'pinyin' => 'yī', 'pinyin_eng' => 'yi', 'meaning_thai' => 'หมอ', 'meaning_english' => 'doctor'],
            ['hanzi' => '三', 'radical' => '一', 'pinyin' => 'sān', 'pinyin_eng' => 'san', 'meaning_thai' => 'สาม', 'meaning_english' => 'three'],
            ['hanzi' => '兴', 'radical' => '八', 'pinyin' => 'xìng', 'pinyin_eng' => 'xing', 'meaning_thai' => 'ความสนใจ, ความตื่นเต้น', 'meaning_english' => 'interest, excitement'],
            ['hanzi' => '服', 'radical' => '月', 'pinyin' => 'fú', 'pinyin_eng' => 'fu', 'meaning_thai' => 'เสื้อผ้า, บริการ', 'meaning_english' => 'clothes, serve'],
            ['hanzi' => '字', 'radical' => '宀', 'pinyin' => 'zì', 'pinyin_eng' => 'zi', 'meaning_thai' => 'ตัวอักษร, คำ', 'meaning_english' => 'character, word'],
            ['hanzi' => '水', 'radical' => '水', 'pinyin' => 'shuǐ', 'pinyin_eng' => 'shui', 'meaning_thai' => 'น้ำ', 'meaning_english' => 'water'],
            ['hanzi' => '号', 'radical' => '口', 'pinyin' => 'hào', 'pinyin_eng' => 'hao', 'meaning_thai' => 'หมายเลข', 'meaning_english' => 'number'],
            ['hanzi' => '师', 'radical' => '巾', 'pinyin' => 'shī', 'pinyin_eng' => 'shi', 'meaning_thai' => 'ครู, อาจารย์', 'meaning_english' => 'teacher, master'],
            ['hanzi' => '星', 'radical' => '日', 'pinyin' => 'xīng', 'pinyin_eng' => 'xing', 'meaning_thai' => 'ดาว', 'meaning_english' => 'star'],
            ['hanzi' => '识', 'radical' => '讠', 'pinyin' => 'shí', 'pinyin_eng' => 'shi', 'meaning_thai' => 'รู้จัก', 'meaning_english' => 'know, recognize'],
            ['hanzi' => '坐', 'radical' => '土', 'pinyin' => 'zuò', 'pinyin_eng' => 'zuo', 'meaning_thai' => 'นั่ง', 'meaning_english' => 'sit'],
            ['hanzi' => '期', 'radical' => '月', 'pinyin' => 'qī', 'pinyin_eng' => 'qi', 'meaning_thai' => 'ช่วงเวลา', 'meaning_english' => 'period, phase'],
            ['hanzi' => '买', 'radical' => '乛', 'pinyin' => 'mǎi', 'pinyin_eng' => 'mai', 'meaning_thai' => 'ซื้อ', 'meaning_english' => 'buy'],
            ['hanzi' => '影', 'radical' => '彡', 'pinyin' => 'yǐng', 'pinyin_eng' => 'ying', 'meaning_thai' => 'เงา, ภาพ', 'meaning_english' => 'shadow, image'],
            ['hanzi' => '二', 'radical' => '二', 'pinyin' => 'èr', 'pinyin_eng' => 'er', 'meaning_thai' => 'สอง', 'meaning_english' => 'two'],
            ['hanzi' => '喝', 'radical' => '口', 'pinyin' => 'hē', 'pinyin_eng' => 'he', 'meaning_thai' => 'ดื่ม', 'meaning_english' => 'drink'],
            ['hanzi' => '月', 'radical' => '月', 'pinyin' => 'yuè', 'pinyin_eng' => 'yue', 'meaning_thai' => 'เดือน, พระจันทร์', 'meaning_english' => 'month, moon'],
            ['hanzi' => '写', 'radical' => '冖', 'pinyin' => 'xiě', 'pinyin_eng' => 'xie', 'meaning_thai' => 'เขียน', 'meaning_english' => 'write'],
            ['hanzi' => '姐', 'radical' => '女', 'pinyin' => 'jiě', 'pinyin_eng' => 'jie', 'meaning_thai' => 'พี่สาว', 'meaning_english' => 'older sister'],
            ['hanzi' => '飞', 'radical' => '飞', 'pinyin' => 'fēi', 'pinyin_eng' => 'fei', 'meaning_thai' => 'บิน', 'meaning_english' => 'fly'],
            ['hanzi' => '视', 'radical' => '见', 'pinyin' => 'shì', 'pinyin_eng' => 'shi', 'meaning_thai' => 'ดู, มอง', 'meaning_english' => 'look, view'],
            ['hanzi' => '衣', 'radical' => '衤', 'pinyin' => 'yī', 'pinyin_eng' => 'yi', 'meaning_thai' => 'เสื้อผ้า', 'meaning_english' => 'clothes'],
            ['hanzi' => '钟', 'radical' => '钅', 'pinyin' => 'zhōng', 'pinyin_eng' => 'zhong', 'meaning_thai' => 'นาฬิกา, ระฆัง', 'meaning_english' => 'clock, bell'],
            ['hanzi' => '十', 'radical' => '十', 'pinyin' => 'shí', 'pinyin_eng' => 'shi', 'meaning_thai' => 'สิบ', 'meaning_english' => 'ten'],
            ['hanzi' => '睡', 'radical' => '目', 'pinyin' => 'shuì', 'pinyin_eng' => 'shui', 'meaning_thai' => 'นอนหลับ', 'meaning_english' => 'sleep'],
            ['hanzi' => '亮', 'radical' => '亠', 'pinyin' => 'liàng', 'pinyin_eng' => 'liang', 'meaning_thai' => 'สว่าง, ส่องแสง', 'meaning_english' => 'bright, shine'],
            ['hanzi' => '狗', 'radical' => '犭', 'pinyin' => 'gǒu', 'pinyin_eng' => 'gou', 'meaning_thai' => 'สุนัข', 'meaning_english' => 'dog'],
            ['hanzi' => '脑', 'radical' => '月', 'pinyin' => 'nǎo', 'pinyin_eng' => 'nao', 'meaning_thai' => 'สมอง', 'meaning_english' => 'brain'],
            ['hanzi' => '院', 'radical' => '阝', 'pinyin' => 'yuàn', 'pinyin_eng' => 'yuan', 'meaning_thai' => 'สนาม, โรงพยาบาล', 'meaning_english' => 'courtyard, hospital'],
            ['hanzi' => '书', 'radical' => '书', 'pinyin' => 'shū', 'pinyin_eng' => 'shu', 'meaning_thai' => 'หนังสือ', 'meaning_english' => 'book'],
            ['hanzi' => '四', 'radical' => '囗', 'pinyin' => 'sì', 'pinyin_eng' => 'si', 'meaning_thai' => 'สี่', 'meaning_english' => 'four'],
            ['hanzi' => '米', 'radical' => '米', 'pinyin' => 'mǐ', 'pinyin_eng' => 'mi', 'meaning_thai' => 'ข้าว, เมตร', 'meaning_english' => 'rice, meter'],
            ['hanzi' => '校', 'radical' => '木', 'pinyin' => 'xiào', 'pinyin_eng' => 'xiao', 'meaning_thai' => 'โรงเรียน', 'meaning_english' => 'school'],
            ['hanzi' => '客', 'radical' => '宀', 'pinyin' => 'kè', 'pinyin_eng' => 'ke', 'meaning_thai' => 'แขก', 'meaning_english' => 'guest'],
            ['hanzi' => '岁', 'radical' => '山', 'pinyin' => 'suì', 'pinyin_eng' => 'sui', 'meaning_thai' => 'อายุ, ปี', 'meaning_english' => 'age, years old'],
            ['hanzi' => '五', 'radical' => '二', 'pinyin' => 'wǔ', 'pinyin_eng' => 'wu', 'meaning_thai' => 'ห้า', 'meaning_english' => 'five'],
            ['hanzi' => '漂', 'radical' => '氵', 'pinyin' => 'piào', 'pinyin_eng' => 'piao', 'meaning_thai' => 'สวย', 'meaning_english' => 'pretty'],
            ['hanzi' => '喂', 'radical' => '口', 'pinyin' => 'wèi', 'pinyin_eng' => 'wei', 'meaning_thai' => 'ให้อาหาร, ฮัลโหล', 'meaning_english' => 'feed, hello (phone)'],
            ['hanzi' => '块', 'radical' => '土', 'pinyin' => 'kuài', 'pinyin_eng' => 'kuai', 'meaning_thai' => 'ชิ้น, ก้อน', 'meaning_english' => 'piece, chunk'],
            ['hanzi' => '店', 'radical' => '广', 'pinyin' => 'diàn', 'pinyin_eng' => 'dian', 'meaning_thai' => 'ร้านค้า', 'meaning_english' => 'shop, store'],
            ['hanzi' => '语', 'radical' => '讠', 'pinyin' => 'yǔ', 'pinyin_eng' => 'yu', 'meaning_thai' => 'ภาษา, คำพูด', 'meaning_english' => 'language, speech'],
            ['hanzi' => '热', 'radical' => '灬', 'pinyin' => 'rè', 'pinyin_eng' => 're', 'meaning_thai' => 'ร้อน', 'meaning_english' => 'hot, heat'],
            ['hanzi' => '杯', 'radical' => '木', 'pinyin' => 'bēi', 'pinyin_eng' => 'bei', 'meaning_thai' => 'ถ้วย', 'meaning_english' => 'cup'],
            ['hanzi' => '昨', 'radical' => '日', 'pinyin' => 'zuó', 'pinyin_eng' => 'zuo', 'meaning_thai' => 'เมื่อวาน', 'meaning_english' => 'yesterday'],
            ['hanzi' => '饭', 'radical' => '饣', 'pinyin' => 'fàn', 'pinyin_eng' => 'fan', 'meaning_thai' => 'ข้าว, อาหาร', 'meaning_english' => 'rice, meal'],
            ['hanzi' => '冷', 'radical' => '冫', 'pinyin' => 'lěng', 'pinyin_eng' => 'leng', 'meaning_thai' => 'หนาว', 'meaning_english' => 'cold'],
            ['hanzi' => '午', 'radical' => '十', 'pinyin' => 'wǔ', 'pinyin_eng' => 'wu', 'meaning_thai' => 'เที่ยง', 'meaning_english' => 'noon'],
            ['hanzi' => '习', 'radical' => '习', 'pinyin' => 'xí', 'pinyin_eng' => 'xi', 'meaning_thai' => 'ฝึกฝน, เรียนรู้', 'meaning_english' => 'practice, study'],
            ['hanzi' => '六', 'radical' => '六', 'pinyin' => 'liù', 'pinyin_eng' => 'liu', 'meaning_thai' => 'หก', 'meaning_english' => 'six'],
            ['hanzi' => '读', 'radical' => '讠', 'pinyin' => 'dú', 'pinyin_eng' => 'du', 'meaning_thai' => 'อ่าน, ศึกษา', 'meaning_english' => 'read, study'],
            ['hanzi' => '商', 'radical' => '口', 'pinyin' => 'shāng', 'pinyin_eng' => 'shang', 'meaning_thai' => 'การค้า, ธุรกิจ', 'meaning_english' => 'commerce, business'],
            ['hanzi' => '八', 'radical' => '八', 'pinyin' => 'bā', 'pinyin_eng' => 'ba', 'meaning_thai' => 'แปด', 'meaning_english' => 'eight'],
            ['hanzi' => '汉', 'radical' => '氵', 'pinyin' => 'hàn', 'pinyin_eng' => 'han', 'meaning_thai' => 'จีน, ฮั่น', 'meaning_english' => 'Chinese, Han'],
            ['hanzi' => '租', 'radical' => '禾', 'pinyin' => 'zū', 'pinyin_eng' => 'zu', 'meaning_thai' => 'เช่า', 'meaning_english' => 'rent'],
            ['hanzi' => '猫', 'radical' => '犭', 'pinyin' => 'māo', 'pinyin_eng' => 'mao', 'meaning_thai' => 'แมว', 'meaning_english' => 'cat'],
            ['hanzi' => '七', 'radical' => '一', 'pinyin' => 'qī', 'pinyin_eng' => 'qi', 'meaning_thai' => 'เจ็ด', 'meaning_english' => 'seven'],
            ['hanzi' => '菜', 'radical' => '艹', 'pinyin' => 'cài', 'pinyin_eng' => 'cai', 'meaning_thai' => 'จาน, ผัก', 'meaning_english' => 'dish, vegetable'],
            ['hanzi' => '北', 'radical' => '匕', 'pinyin' => 'běi', 'pinyin_eng' => 'bei', 'meaning_thai' => 'เหนือ', 'meaning_english' => 'north'],
            ['hanzi' => '桌', 'radical' => '木', 'pinyin' => 'zhuō', 'pinyin_eng' => 'zhuo', 'meaning_thai' => 'โต๊ะ', 'meaning_english' => 'table'],
            ['hanzi' => '雨', 'radical' => '雨', 'pinyin' => 'yǔ', 'pinyin_eng' => 'yu', 'meaning_thai' => 'ฝน', 'meaning_english' => 'rain'],
            ['hanzi' => '九', 'radical' => '丨', 'pinyin' => 'jiǔ', 'pinyin_eng' => 'jiu', 'meaning_thai' => 'เก้า', 'meaning_english' => 'nine'],
            ['hanzi' => '椅', 'radical' => '木', 'pinyin' => 'yǐ', 'pinyin_eng' => 'yi', 'meaning_thai' => 'เก้าอี้', 'meaning_english' => 'chair'],
            ['hanzi' => '茶', 'radical' => '艹', 'pinyin' => 'chá', 'pinyin_eng' => 'cha', 'meaning_thai' => 'ชา', 'meaning_english' => 'tea'],
            ['hanzi' => '京', 'radical' => '亠', 'pinyin' => 'jīng', 'pinyin_eng' => 'jing', 'meaning_thai' => 'เมืองหลวง (ปักกิ่ง)', 'meaning_english' => 'capital (Beijing)'],
            ['hanzi' => '苹', 'radical' => '艹', 'pinyin' => 'píng', 'pinyin_eng' => 'ping', 'meaning_thai' => 'แอปเปิ้ล', 'meaning_english' => 'apple'],
        ]);

        // hanzi_categories HSK 1 (174)
        DB::table('hanzi_categories')->insert([
            ['hanzi_id' => 1, 'category_id' => 1],
            ['hanzi_id' => 2, 'category_id' => 1],
            ['hanzi_id' => 3, 'category_id' => 1],
            ['hanzi_id' => 4, 'category_id' => 1],
            ['hanzi_id' => 5, 'category_id' => 1],
            ['hanzi_id' => 6, 'category_id' => 1],
            ['hanzi_id' => 7, 'category_id' => 1],
            ['hanzi_id' => 8, 'category_id' => 1],
            ['hanzi_id' => 9, 'category_id' => 1],
            ['hanzi_id' => 10, 'category_id' => 1],
            ['hanzi_id' => 11, 'category_id' => 1],
            ['hanzi_id' => 12, 'category_id' => 1],
            ['hanzi_id' => 13, 'category_id' => 1],
            ['hanzi_id' => 14, 'category_id' => 1],
            ['hanzi_id' => 15, 'category_id' => 1],
            ['hanzi_id' => 16, 'category_id' => 1],
            ['hanzi_id' => 17, 'category_id' => 1],
            ['hanzi_id' => 18, 'category_id' => 1],
            ['hanzi_id' => 19, 'category_id' => 1],
            ['hanzi_id' => 20, 'category_id' => 1],
            ['hanzi_id' => 21, 'category_id' => 1],
            ['hanzi_id' => 22, 'category_id' => 1],
            ['hanzi_id' => 23, 'category_id' => 1],
            ['hanzi_id' => 24, 'category_id' => 1],
            ['hanzi_id' => 25, 'category_id' => 1],
            ['hanzi_id' => 26, 'category_id' => 1],
            ['hanzi_id' => 27, 'category_id' => 1],
            ['hanzi_id' => 28, 'category_id' => 1],
            ['hanzi_id' => 29, 'category_id' => 1],
            ['hanzi_id' => 30, 'category_id' => 1],
            ['hanzi_id' => 31, 'category_id' => 1],
            ['hanzi_id' => 32, 'category_id' => 1],
            ['hanzi_id' => 33, 'category_id' => 1],
            ['hanzi_id' => 34, 'category_id' => 1],
            ['hanzi_id' => 35, 'category_id' => 1],
            ['hanzi_id' => 36, 'category_id' => 1],
            ['hanzi_id' => 37, 'category_id' => 1],
            ['hanzi_id' => 38, 'category_id' => 1],
            ['hanzi_id' => 39, 'category_id' => 1],
            ['hanzi_id' => 40, 'category_id' => 1],
            ['hanzi_id' => 41, 'category_id' => 1],
            ['hanzi_id' => 42, 'category_id' => 1],
            ['hanzi_id' => 43, 'category_id' => 1],
            ['hanzi_id' => 44, 'category_id' => 1],
            ['hanzi_id' => 45, 'category_id' => 1],
            ['hanzi_id' => 46, 'category_id' => 1],
            ['hanzi_id' => 47, 'category_id' => 1],
            ['hanzi_id' => 48, 'category_id' => 1],
            ['hanzi_id' => 49, 'category_id' => 1],
            ['hanzi_id' => 50, 'category_id' => 1],
            ['hanzi_id' => 51, 'category_id' => 1],
            ['hanzi_id' => 52, 'category_id' => 1],
            ['hanzi_id' => 53, 'category_id' => 1],
            ['hanzi_id' => 54, 'category_id' => 1],
            ['hanzi_id' => 55, 'category_id' => 1],
            ['hanzi_id' => 56, 'category_id' => 1],
            ['hanzi_id' => 57, 'category_id' => 1],
            ['hanzi_id' => 58, 'category_id' => 1],
            ['hanzi_id' => 59, 'category_id' => 1],
            ['hanzi_id' => 60, 'category_id' => 1],
            ['hanzi_id' => 61, 'category_id' => 1],
            ['hanzi_id' => 62, 'category_id' => 1],
            ['hanzi_id' => 63, 'category_id' => 1],
            ['hanzi_id' => 64, 'category_id' => 1],
            ['hanzi_id' => 65, 'category_id' => 1],
            ['hanzi_id' => 66, 'category_id' => 1],
            ['hanzi_id' => 67, 'category_id' => 1],
            ['hanzi_id' => 68, 'category_id' => 1],
            ['hanzi_id' => 69, 'category_id' => 1],
            ['hanzi_id' => 70, 'category_id' => 1],
            ['hanzi_id' => 71, 'category_id' => 1],
            ['hanzi_id' => 72, 'category_id' => 1],
            ['hanzi_id' => 73, 'category_id' => 1],
            ['hanzi_id' => 74, 'category_id' => 1],
            ['hanzi_id' => 75, 'category_id' => 1],
            ['hanzi_id' => 76, 'category_id' => 1],
            ['hanzi_id' => 77, 'category_id' => 1],
            ['hanzi_id' => 78, 'category_id' => 1],
            ['hanzi_id' => 79, 'category_id' => 1],
            ['hanzi_id' => 80, 'category_id' => 1],
            ['hanzi_id' => 81, 'category_id' => 1],
            ['hanzi_id' => 82, 'category_id' => 1],
            ['hanzi_id' => 83, 'category_id' => 1],
            ['hanzi_id' => 84, 'category_id' => 1],
            ['hanzi_id' => 85, 'category_id' => 1],
            ['hanzi_id' => 86, 'category_id' => 1],
            ['hanzi_id' => 87, 'category_id' => 1],
            ['hanzi_id' => 88, 'category_id' => 1],
            ['hanzi_id' => 89, 'category_id' => 1],
            ['hanzi_id' => 90, 'category_id' => 1],
            ['hanzi_id' => 91, 'category_id' => 1],
            ['hanzi_id' => 92, 'category_id' => 1],
            ['hanzi_id' => 93, 'category_id' => 1],
            ['hanzi_id' => 94, 'category_id' => 1],
            ['hanzi_id' => 95, 'category_id' => 1],
            ['hanzi_id' => 96, 'category_id' => 1],
            ['hanzi_id' => 97, 'category_id' => 1],
            ['hanzi_id' => 98, 'category_id' => 1],
            ['hanzi_id' => 99, 'category_id' => 1],
            ['hanzi_id' => 100, 'category_id' => 1],
            ['hanzi_id' => 101, 'category_id' => 1],
            ['hanzi_id' => 102, 'category_id' => 1],
            ['hanzi_id' => 103, 'category_id' => 1],
            ['hanzi_id' => 104, 'category_id' => 1],
            ['hanzi_id' => 105, 'category_id' => 1],
            ['hanzi_id' => 106, 'category_id' => 1],
            ['hanzi_id' => 107, 'category_id' => 1],
            ['hanzi_id' => 108, 'category_id' => 1],
            ['hanzi_id' => 109, 'category_id' => 1],
            ['hanzi_id' => 110, 'category_id' => 1],
            ['hanzi_id' => 111, 'category_id' => 1],
            ['hanzi_id' => 112, 'category_id' => 1],
            ['hanzi_id' => 113, 'category_id' => 1],
            ['hanzi_id' => 114, 'category_id' => 1],
            ['hanzi_id' => 115, 'category_id' => 1],
            ['hanzi_id' => 116, 'category_id' => 1],
            ['hanzi_id' => 117, 'category_id' => 1],
            ['hanzi_id' => 118, 'category_id' => 1],
            ['hanzi_id' => 119, 'category_id' => 1],
            ['hanzi_id' => 120, 'category_id' => 1],
            ['hanzi_id' => 121, 'category_id' => 1],
            ['hanzi_id' => 122, 'category_id' => 1],
            ['hanzi_id' => 123, 'category_id' => 1],
            ['hanzi_id' => 124, 'category_id' => 1],
            ['hanzi_id' => 125, 'category_id' => 1],
            ['hanzi_id' => 126, 'category_id' => 1],
            ['hanzi_id' => 127, 'category_id' => 1],
            ['hanzi_id' => 128, 'category_id' => 1],
            ['hanzi_id' => 129, 'category_id' => 1],
            ['hanzi_id' => 130, 'category_id' => 1],
            ['hanzi_id' => 131, 'category_id' => 1],
            ['hanzi_id' => 132, 'category_id' => 1],
            ['hanzi_id' => 133, 'category_id' => 1],
            ['hanzi_id' => 134, 'category_id' => 1],
            ['hanzi_id' => 135, 'category_id' => 1],
            ['hanzi_id' => 136, 'category_id' => 1],
            ['hanzi_id' => 137, 'category_id' => 1],
            ['hanzi_id' => 138, 'category_id' => 1],
            ['hanzi_id' => 139, 'category_id' => 1],
            ['hanzi_id' => 140, 'category_id' => 1],
            ['hanzi_id' => 141, 'category_id' => 1],
            ['hanzi_id' => 142, 'category_id' => 1],
            ['hanzi_id' => 143, 'category_id' => 1],
            ['hanzi_id' => 144, 'category_id' => 1],
            ['hanzi_id' => 145, 'category_id' => 1],
            ['hanzi_id' => 146, 'category_id' => 1],
            ['hanzi_id' => 147, 'category_id' => 1],
            ['hanzi_id' => 148, 'category_id' => 1],
            ['hanzi_id' => 149, 'category_id' => 1],
            ['hanzi_id' => 150, 'category_id' => 1],
            ['hanzi_id' => 151, 'category_id' => 1],
            ['hanzi_id' => 152, 'category_id' => 1],
            ['hanzi_id' => 153, 'category_id' => 1],
            ['hanzi_id' => 154, 'category_id' => 1],
            ['hanzi_id' => 155, 'category_id' => 1],
            ['hanzi_id' => 156, 'category_id' => 1],
            ['hanzi_id' => 157, 'category_id' => 1],
            ['hanzi_id' => 158, 'category_id' => 1],
            ['hanzi_id' => 159, 'category_id' => 1],
            ['hanzi_id' => 160, 'category_id' => 1],
            ['hanzi_id' => 161, 'category_id' => 1],
            ['hanzi_id' => 162, 'category_id' => 1],
            ['hanzi_id' => 163, 'category_id' => 1],
            ['hanzi_id' => 164, 'category_id' => 1],
            ['hanzi_id' => 165, 'category_id' => 1],
            ['hanzi_id' => 166, 'category_id' => 1],
            ['hanzi_id' => 167, 'category_id' => 1],
            ['hanzi_id' => 168, 'category_id' => 1],
            ['hanzi_id' => 169, 'category_id' => 1],
            ['hanzi_id' => 170, 'category_id' => 1],
            ['hanzi_id' => 171, 'category_id' => 1],
            ['hanzi_id' => 172, 'category_id' => 1],
            ['hanzi_id' => 173, 'category_id' => 1],
            ['hanzi_id' => 174, 'category_id' => 1]
        ]);
    }
}
